### ISSUE TITLE
Request: Ability to use gamepad buttons as lightgun buttons

### ISSUE THREAD

**Issue by ziltama** [argonlefou/DemulShooter#1]
Demulshooter works well so far. However, for those of us with arcade style trackballs (U-trak as example) in arcade cabinet setups, by default, there are no mouse buttons hooked up to it.

So, in games, I would then use a joystick / gamepad button for the various actions.

Wondering if this feature (using gamepad / joystick buttons as mouse buttons) can be added to future versions. I also noticed that for gamepad mode, Demulshooter didn't detect my fight stick controllers but only my two trackballs (as mouse) and 2 xbox controllers. Otherwise, I have to use something like joy2key. Thanks.

**Comment by argonlefou** [comment]
This is a very specific situation, indeed
The core of DemulShooter is not made to merge multiple devices (i.e separate axis and buttons) into one emulated Lightgun, so your request is unfortunately unlikely to happen in the future.

As for GamePad detection, I don't know how is your FightStick set up in windows (Dinput ? Xinput ? Anything else ?) but in theory, DemulShooter should detect any Xinput device.

Finally, with all due respect, working on fight stick controllers (or even, as I was asked recently, making DemulShooter compatible with Racing Wheels -- not joking !! --) is not something relevant to me
