### ISSUE TITLE
Transformes Human Aliance  JVS I/O error 6401

### ISSUE THREAD

**Issue by jhonipin** [argonlefou/DemulShooter#10]
I'm having this error when trying to play this game with two x360 joystck, when loading the game everything works perfectly more than at certain times of the game happens the error 6401 tried everything else solves now I don't know if this error is from demulshooter or the tecknoparrot

**Comment by argonlefou** [comment]
Hello, 
I'm personnally not using joysticks, so I can only answer that I never had any issue with Aimtraks
And that so far, you're the only one telling me about this kind of error

**Comment by Cristian2294-ccsp** [comment]
Hi argonlefou

Thanks for your great job.

I´m having this error 6401 JVS IO NOT CONNECTED when i use DEMULSHOOTER. Can you help us with this error?

Thanks for all!!
