### ISSUE TITLE
HOTD Remake

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#101]
Salut l'ami...deja grand merci..tu as fait un boulo de malade!
2 questions : 
1 - je sais je fais le lourd....on en veut tjrs plus...mais pourquoi le mode Horde ne marche pas?
2 - si tu arrives à faire ca tu peux le faire avec d'autres jeux windows? :)
merci

**Comment by argonlefou** [comment]
> 1 - je sais je fais le lourd....on en veut tjrs plus...mais pourquoi le mode Horde ne marche pas? 

Réponse simple : C'est un mod "Arcade" .... et le mode Horde ne fait pas partie du jeu initial en arcade.

> 2 - si tu arrives à faire ca tu peux le faire avec d'autres jeux windows? :) merci

Il n'y a pas de règle, tout dépend du jeu.
Il n'y en a pas d'autre de prévu pour le moment
