### ISSUE TITLE
DemulShooter is not hooking Fright Fear Land

### ISSUE THREAD

**Issue by drewjbx1** [argonlefou/DemulShooter#105]
Game patcher shows "Game Loader All RH" Fright Fear Land game.exe detected

I Tried both:
`DemulShooter.exe -target=ttx -rom=hmuseum2`
`DemulShooter.exe -target=globalvr -rom=fearland`

Running DemulShooter 10.9.0
Checked system tray while game is running and DemulShooter icon remains red. Possibly broken as I tried 3 different dumps.

**Comment by argonlefou** [comment]
Can you get a debug file and share it here ?
https://github.com/argonlefou/DemulShooter/wiki/Debugging#step-3

**Comment by drewjbx1** [comment]
Ok, here it is

08:29:15.025467 : 
08:29:15.921457 : ---------------- Program Start -- DemulShooter v10.8.3.0 ----------------
08:29:15.955520 : Cmdline arg 0 : -target=ttx
08:29:15.966576 : Cmdline arg 1 : -rom=hmuseum2
08:29:15.977641 : Cmdline arg 2 : -v
08:29:16.003347 : Error: Impossible to get Value Capabilities for device \\?\HID#VID_046D&PID_C534&MI_01&Col05#8&2239974a&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
08:29:16.028388 : Error: Impossible to get Value Capabilities for device \\?\HID#VID_046D&PID_C534&MI_01&Col04#8&2239974a&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
08:29:16.040773 : Error: Impossible to get Value Capabilities for device \\?\HID#VID_046D&PID_C534&MI_01&Col02#8&2239974a&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
08:29:16.041444 : Error: Impossible to get Output Value Capabilities for device \\?\HID#VID_045E&PID_028E&IG_00#8&2f322b15&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
08:29:16.125265 : Found 7 available RawInput devices :
08:29:16.126149 :  + [RIM_TYPEHID] \\?\HID#VID_046D&PID_C534&MI_01&Col05#8&2239974a&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
08:29:16.126836 :  + [RIM_TYPEHID] \\?\HID#VID_046D&PID_C534&MI_01&Col04#8&2239974a&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
08:29:16.127086 :  + [RIM_TYPEHID] \\?\HID#VID_046D&PID_C534&MI_01&Col02#8&2239974a&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
08:29:16.128061 :  + [RIM_TYPEHID] \\?\HID#VID_045E&PID_028E&IG_00#8&2f322b15&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
08:29:16.128061 :  + [RIM_TYPEMOUSE] \\?\HID#VID_16C0&PID_0F39&MI_02&Col02#9&69a49e3&0&0001#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
08:29:16.129062 :  + [RIM_TYPEMOUSE] \\?\HID#VID_046D&PID_C534&MI_01&Col01#8&2239974a&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
08:29:16.129062 :  + [RIM_TYPEMOUSE] \\?\HID#VID_16C0&PID_0F38&MI_02&Col02#9&290b5653&0&0001#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
08:29:16.136064 : Configuration file succesfuly loaded
08:29:16.138725 : P1 mode = RAWINPUT
08:29:16.139274 : P1 device = \\?\HID#VID_16C0&PID_0F38&MI_02&Col02#9&290b5653&0&0001#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
08:29:16.140060 : P1 device plugged and found, Handle = 0x65593
08:29:16.140739 : P1 device : Unknown / SindenLightgun
08:29:16.141273 : P2 mode = RAWINPUT
08:29:16.141804 : P2 device = \\?\HID#VID_16C0&PID_0F39&MI_02&Col02#9&69a49e3&0&0001#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
08:29:16.142587 : P2 device plugged and found, Handle = 0x65582
08:29:16.143113 : P2 device : Unknown / SindenLightgun
08:29:16.143615 : P3 mode = RAWINPUT
08:29:16.144087 : P3 device = 
08:29:16.144885 : P4 mode = RAWINPUT
08:29:16.145421 : P4 device = 
08:29:16.169942 : Monitor maximum resolution = 1920 x 1080 x 4294967296 colors @ 60 Hertz
08:29:16.172966 : LowLevelMouseHook installed !
08:29:16.173282 : LowLevel-KeyboardHook installed !
08:29:16.177277 : Waiting for Taito type X hmuseum2 game to hook.....
08:29:27.370442 : Error trying to hook game.exe
08:29:27.882037 : Error trying to hook game.exe
08:29:28.381879 : Error trying to hook game.exe
08:29:28.891456 : Error trying to hook game.exe
(Many more duplicate lines)

**Comment by argonlefou** [comment]
DemulShooter is not able to attach to the process.

Are you sure you are running it with as an admin ?

**Comment by drewjbx1** [comment]
Silly me.. I double checked and it was not set to admin. The PC happens to be a new gun build I am doing. So demulshooter in fact hooked the game....  but now the problem is I get no mouse movement from guns. The crosshairs are frozen... to confirm I restarted game without demulshooter and my crosshair movement is back. The log is here at pastebin, anything stand out to you?

[https://pastebin.com/raw/xhiiN9mD](url)

**Comment by drewjbx1** [comment]
Ok I figured it out, thanks for your quick responses. The problem was with the game.exe being an unknown md5 hash. I got a good game.exe and all is well.
