### ISSUE TITLE
HOTD Remake - Arcade plugin guns calibration problem in MULTIPLAYER mode

### ISSUE THREAD

**Issue by benclau** [argonlefou/DemulShooter#106]
When i use 2 lightguns and set the arcade mod plugin to MULTIPLAYER, the guns are not calibrated. This problem doesn't occur with the SINGLEPLAYER mode. The guns a aligned on the left side but the offset is getting worst while dragging the crosshair on the right side.

I have 2 Sinden Lightgun.

**Comment by argonlefou** [comment]
Hi,
HOTD remake has been tested by a lot of people these past few days, and all of them reported 100% working without any issue.
So it is not DemulShooter related, you'll have to look on your OS / Sinden configuration.

Using SINGLEPLAYER mode, coordinates are read from the mouse cursor position directly by the Unity engine, given by Windows
On the other  hand, using MULTIPLAYER + DemulShooter requires a good sinden configuration as the values are read directly from the guns.

On your case, the most common issue is the window scaling display option that may be at 125%, but you need to set it to 100% to make DemulShooter work correctly

I highly advise you to join the Sinden discord, where you'll get any needed help on that matter.
A similar issue has been answered a couple of days ago (the scaling option was the culprit)
