### ISSUE TITLE
Problem with Tomb Raider

### ISSUE THREAD

**Issue by Metheny39** [argonlefou/DemulShooter#107]
Hi,
I use Sinden lightgun, I apply your procedure  for Tomb Raider (Rabbids works very well)...I can select mission bit when I arrive in game, no cross and no trigger...
Thanks for helping! :)

**Comment by argonlefou** [comment]
Hi,
This looks like a configuration/hooking issue. You can try to share a debug file (https://github.com/argonlefou/DemulShooter/wiki/Debugging#step-3) and verify that DemulShooter is properly hooked (green icon on the tray menu)

But this github repo beeing about bugs and functionnalitues, chances are high that I'll have to forward you to Sinden community/discord to get help on how to configure your setup

**Comment by popo69200** [comment]
Salit moi avec TP , ça hooked nickel mais pas de gun en jeu.
Si je lance le jeu sans tp j'ai les guns. Et avec le retour de force. Par contre ça fait comme.les première version de terminator. Je trouve le gun avec un retour pas très précis.. le ffb aussi ça marche quand ça veut.
Voilà si ça peut aider.En tout cas merci d'avoir pondu un truc si vite.

**Comment by popo69200** [comment]
probleme réglé pour moi. j'ai mis en intensité 4 ca regle le soucis....je n'ai pas joué au jeu original...mais je crois qu'il se joue au gun...donc forcement le mode mitraillette est peut etre pas adapté non plus.
Merci
