### ISSUE TITLE
issue with demulshooter x64 on house of the dead remake 

### ISSUE THREAD

**Issue by vdeolive** [argonlefou/DemulShooter#108]
Hello

thank you for the arcade patch released some weeks ago.
i would like to play 2players on hotdra but following the procedure, it seems that demulshooterx64 does not hook
i am running it as administrator but i still have ¨Impossible to get Value Capabilities for device¨ issue on log

i am using a bat to launch it and the demulshooter icon remains red

@echo OFF

REM HERE MODIFY YOUR STEAM APPID:
Start "" DemulShooterX64.exe -target=windows -rom=hotdra -v
Start "" hotdra.exe

TIMEOUT /t 10
:RUNNING

REM HERE YOU MUST ENTER THE RIGHT NAME OF THE EXECUTABLE, FOR EXAMPLE: "emulator_multicpu.exe"
tasklist|findstr "hotdra.exe" > nul

if %errorlevel%==1 timeout /t 2 & GOTO ENDLOOP
timeout /t 2
GOTO RUNNING
:ENDLOOP

Any advice please?

thanking you

**Comment by vdeolive** [comment]
10:09:11.032369 : 
10:09:11.032369 : ---------------- Program Start -- DemulShooterX64 v10.9.1.0 ----------------
10:09:11.033368 : Cmdline arg 0 : -target=windows
10:09:11.033368 : Cmdline arg 1 : -rom=hotdra
10:09:11.033368 : Cmdline arg 2 : -v
10:09:11.046361 : Error: Impossible to get Value Capabilities for device \\?\HID#{00001124-0000-1000-8000-00805f9b34fb}_VID&0002045e_PID&0790&Col02#8&9ba4de4&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.047361 : Error: Impossible to get Output Value Capabilities for device \\?\HID#VID_045E&PID_028E&IG_03#3&31042e6&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.047361 : Error: Impossible to get Output Value Capabilities for device \\?\HID#VID_045E&PID_028E&IG_00#3&8968588&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.048359 : Error: Impossible to get Value Capabilities for device \\?\HID#VID_046D&PID_C52B&MI_01&Col04#7&3986d2b&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.049359 : Error: Impossible to get Value Capabilities for device \\?\HID#VID_0079&PID_1802&MI_01&Col02#7&19a9df72&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.050359 : Error: Impossible to get Value Capabilities for device \\?\HID#VID_046D&PID_C52B&MI_01&Col02#7&3986d2b&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.052357 : Error: Impossible to get Value Capabilities for device \\?\HID#VID_0079&PID_1802&MI_01&Col02#7&101ca601&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.052357 : Error: Impossible to get Value Capabilities for device \\?\HID#VID_046D&PID_C52B&REV_1201&MI_02&Col02#8&31ff778e&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.052357 : Error: Impossible to get Value Capabilities for device \\?\HID#VID_046D&PID_C52B&REV_1201&MI_02&Col01#8&31ff778e&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.061352 : Found 14 available RawInput devices :
10:09:11.061352 :  + [RIM_TYPEHID] \\?\HID#{00001124-0000-1000-8000-00805f9b34fb}_VID&0002045e_PID&0790&Col02#8&9ba4de4&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.061352 :  + [RIM_TYPEHID] \\?\HID#VID_045E&PID_028E&IG_03#3&31042e6&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.061352 :  + [RIM_TYPEHID] \\?\HID#VID_045E&PID_028E&IG_00#3&8968588&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.062352 :  + [RIM_TYPEHID] \\?\HID#VID_046D&PID_C52B&MI_01&Col04#7&3986d2b&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.062352 :  + [RIM_TYPEHID] \\?\HID#VID_0079&PID_1802&MI_01&Col02#7&19a9df72&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.062352 :  + [RIM_TYPEHID] \\?\HID#VID_046D&PID_C52B&MI_01&Col02#7&3986d2b&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.062352 :  + [RIM_TYPEHID] \\?\HID#VID_0079&PID_1802&MI_01&Col02#7&101ca601&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.062352 :  + [RIM_TYPEHID] \\?\HID#VID_046D&PID_C52B&REV_1201&MI_02&Col02#8&31ff778e&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.062352 :  + [RIM_TYPEHID] \\?\HID#VID_046D&PID_C52B&REV_1201&MI_02&Col01#8&31ff778e&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
10:09:11.062352 :  + [RIM_TYPEMOUSE] \\?\HID#VID_0079&PID_1802&MI_01&Col01#7&101ca601&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
10:09:11.063351 :  + [RIM_TYPEMOUSE] \\?\HID#VID_0079&PID_1802&MI_01&Col01#7&19a9df72&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
10:09:11.063351 :  + [RIM_TYPEMOUSE] \\?\HID#VID_046D&PID_C52B&MI_01&Col01#7&3986d2b&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
10:09:11.063351 :  + [RIM_TYPEMOUSE] \\?\HID#VID_03F0&PID_1041#6&27c5075f&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
10:09:11.063351 :  + [RIM_TYPEMOUSE] \\?\HID#VID_046D&PID_C52B&REV_1201&MI_02&Qid_1017&WI_01&Class_00000004#8&920192d&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
10:09:11.080342 : Configuration file succesfuly loaded
10:09:11.080342 : P1 mode = RAWINPUT
10:09:11.080342 : P1 device = \\?\HID#VID_0079&PID_1802&MI_01&Col01#7&19a9df72&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
10:09:11.081341 : P1 device plugged and found, Handle = 0x65599
10:09:11.081341 : P2 mode = RAWINPUT
10:09:11.081341 : P2 device = \\?\HID#VID_0079&PID_1802&MI_01&Col01#7&19a9df72&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
10:09:11.081341 : P2 device plugged and found, Handle = 0x65599
10:09:11.081341 : P3 mode = RAWINPUT
10:09:11.081341 : P3 device = 
10:09:11.081341 : P4 mode = RAWINPUT
10:09:11.082346 : P4 device = 
10:09:11.088336 : Starting Output daemon...
10:09:11.094333 : LowLevelMouseHook installed !
10:09:11.096333 : LowLevel-KeyboardHook installed !
10:09:11.102331 : Waiting for Windows game hotdra game to hook.....

**Comment by argonlefou** [comment]
The game process is named after the exe filename, so renaming this file to hotdra.exe instead of the original filename ("The House of the Dead Remake.exe") will prevent Demulshooter from finding the process to hook it.

> thank you for the arcade patch released some weeks ago. i would like to play 2players on hotdra but following the procedure, it seems that demulshooterx64 does not hook i am running it as administrator but i still have ¨Impossible to get Value Capabilities for device¨ issue on log

This is not important, some USB devices can't be compatible, that's why they are yelling errors.
The inportant part for your devices is :  

>10:09:11.080342 : P1 mode = RAWINPUT
>10:09:11.080342 : P1 device = \?\HID#VID_0079&PID_1802&MI_01&Col01#7&19a9df72&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
>10:09:11.081341 : P1 device plugged and found, Handle = 0x65599
>10:09:11.081341 : P2 mode = RAWINPUT
>10:09:11.081341 : P2 device = \?\HID#VID_0079&PID_1802&MI_01&Col01#7&19a9df72&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
>10:09:11.081341 : P2 device plugged and found, Handle = 0x65599

**Comment by vdeolive** [comment]
yes you're right. i messed with hotdra.exe. now it works. many thanks
