### ISSUE TITLE
When playing Rabbids Hollywood Arcade, all four crosses flash the same color.

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#109]
When playing Rabbids Hollywood Arcade, all four crosses flash the same color.

**Comment by argonlefou** [comment]
I can't answer anything, you didn't provide any usefull information.....

What are you using (guns ? How many ?)
How did you run Demulshooter ?
How did you run the game ?
What is the exact behavior ?
Are guns working ?
Demulshooter debug file ?

**Comment by cmjdbb** [comment]
1：4 handfuls of Gun4ir
2：with AutoHotkey：

run, DemulShooterX64.exe -target=aagames -rom=rha
run, game.exe

3：With four guns at the same time, you can hit the target, but the four crosses are the same color, and the four crosses bounce back and forth.

**Comment by cmjdbb** [comment]
1：4 handfuls of Gun4ir
2：with AutoHotkey：

run, DemulShooterX64.exe -target=aagames -rom=rha
run, game.exe

3：With four guns at the same time, you can hit the target, but the four crosses are the same color, and the four crosses bounce back and forth.

**Comment by argonlefou** [comment]
Start by following these instructions : https://github.com/argonlefou/DemulShooter/wiki/Debugging

Remove all scripts, run manually and post the debug file

Also, you didn't answer the important question : is Demulshooter icon green or red in the tray icon ?

And last, what is the content of /BepInEx/plugin folder (in the game directogy)

**Comment by cmjdbb** [comment]
Sorry, I used translation software to write, may not express accurately. Having been reinstalled many times, the tray Demulshooter icon is green. Playing Tomb Raider is normal. /BepInEx/plugin is: RHA_BepInEx_DemulShooter_Plugin.dll and UnityPlugin_BepInEx_RHA.dll

**Comment by cmjdbb** [comment]
Sorry, I used translation software to write, may not express accurately. Having been reinstalled many times, the tray Demulshooter icon is green. Playing Tomb Raider is normal. /BepInEx/plugin is: RHA_BepInEx_DemulShooter_Plugin.dll 。
[Debug_2023-01-30_17-44-52.txt](https://github.com/argonlefou/DemulShooter/files/10534450/Debug_2023-01-30_17-44-52.txt)

**Comment by argonlefou** [comment]
Thanks.
Try to download [this update](https://github.com/argonlefou/DemulShooter/releases/download/v10.9.2/DemulShooter_v10.9.2.zip) I made today

Then remove BepInEx folder from your Rabbids game folder

Then do the install procedure again with [DemulSHooter_GUI](https://github.com/argonlefou/DemulShooter/wiki/Adrenaline-Amusement-Arcade#rabbids-hollywood-arcade)

It may be because of the BepInEx file, that some user may have this kind of issue.

**Comment by cmjdbb** [comment]
Thank you very much. I use your plugin and it works very well on many games. May be updated after the destruction of the previous game. The new DemulShooter can't run Heavy Fire Afghanistan properly, but the old DemulShooter can. Thank you so much. You're really great

**Comment by cmjdbb** [comment]
Thank you, update can be, you really ox. But can Heavy Fire Afghanistan only be played solo? There is no 2P player menu。

**Comment by argonlefou** [comment]
Can you create a different ticket for Heavy Fire Afghanistan and, give again :
- Debug file
- what is not working ?
- exact old version of Demulshooter working ?

Thanks

**Comment by cmjdbb** [comment]
Afghanistan works fine with older versions of 7.4
