### ISSUE TITLE
Request: Lindbergh hooking enhancement

### ISSUE THREAD

**Issue by adamgp** [argonlefou/DemulShooter#11]
Is it possible to abstract any of the hardcoded attributes for the two Lindbergh classes to an INI file so as TeknoParrot is regularly updated - potentially anyone (with the required ability) can determine and populate this INI for continued Lindbergh support without the need for a new release or recompiling, and having to maintain multiple installations?

Thanks.

**Comment by argonlefou** [comment]
Unfortunatelly - and based on how the code is currently working - this solution would not easily work.

All hardcoded values - except one - are not changing.
The only one changingis not value that you can directly use to inject data in memory, but an offset that is used to calculate a Pointer to memory address.

The main issue is that this pointer is sometimes a 3 level pointer, sometimes a 4 level pointer, and even if it's the same level as the previous version, each level offset are changing too.

this just can't be written in an .INI file as you still have to change the maths

**Comment by adamgp** [comment]
Thanks for explaining.

I appreciate how awkward that must be to change as a result - shame it is not an easy thing to update.

Looking forward to the next release ;)

Thanks
