### ISSUE TITLE
mamehooker5.1 electromagnet output is out of sync

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#112]
Hello brother！I used mamehooker5.1 electromagnet output. The DemulShooter_GUI.exe output is selected, the game can see the player's other parameters in mamehooker5.1, but the electromagnet output is not synchronized, I used Gun4ir, com1 and com2 are set, is something not set?

**Comment by argonlefou** [comment]
Hollo,
For any Mamehooker/gun4ir configuration issue, you can ask in GUN4IR discord. We will be happy to help you there.

This is not Demulshooter related
