### ISSUE TITLE
Request: Add Outputs for LLA & Tomb Raider

### ISSUE THREAD

**Issue by bojo5150** [argonlefou/DemulShooter#113]
Argon, would you be able to add outputs to Lost Land Adventure as well as custom recoil outputs for Tomb Raider?

**Comment by argonlefou** [comment]
Tomb Raider already has the usual CtmRecoil output available for all 4 Players (P1_CtmRecoil, P2_CtmRecoil, etc....)

As for LLA, it can be a possibility but this is the same Engine than TC5 and so far it's not the best results (regarding outputs)
I have to go back to TC5 to fix it, LLA may benefit from the solution if I found a decent one.

**Comment by bojo5150** [comment]
My bad, I didn't see Tomb Raider listed in the Wiki so I figured outputs didn't exit. I should have tried before requesting. 

Thanks Argon!
