### ISSUE TITLE
Wild West Shootout P2 fires P1 gun

### ISSUE THREAD

**Issue by bojo5150** [argonlefou/DemulShooter#114]
I've been going through all games and configuring outputs and realized Wild West Shootout isn't working correctly. In a 2 player game, the 2nd player gun fires itself and the P1 gun however firing the P1 gun does not fire the P2 gun until a reload event. When reloading the P1 gun fires 1 shot on the P2 gun.

As note, I was one of several who couldn't run this game at first as the game wouldn't start due to a "NetDLLBroken" error. That said its possible everything works fine for most others that don't receive this error. Since I do, to start the game I use an AHK to launch the game, sleep for 5 sec, and then start demulshooter. For the game start command I use:

Run RunAs /trustlevel:0x20000 "G\Wild West Shootout\NTFS extd - Game\Cowboy.exe"

This allows the game to start without the NetDLL error and I'm wondering if this breaks something with demulshooter.

Misc. notes - Both DS & the game are set to run as administrator. I've tried DS v10.8.1 as well as an older release. 10.7.1 and both versions have the exact same issues.

Anyway I was wondering if this is something you would consider looking into. Thank you!

**Comment by argonlefou** [comment]
I'm running the game on a Windows10 version that needs the same command (runas.exe /trustlevel:0x20000)

But I can't reproduce what you're describing. 
Everything is working as it should (tested with DemulShooter v10.9.2, on a fresh game with plugin installed from the GUI)

Unity plugin demulshooter games are not as easy as native one to debug, errors can come from a different Assembly-CSharp file or anything changed in the game files.

You can still get a DemulShooter debug file (https://github.com/argonlefou/DemulShooter/wiki/Debugging#step-3)
There may be something obvious in it, but if not, at least there will lbe some information about the files you're using in the game

**Comment by bojo5150** [comment]
[Debug_2023-02-04_11-36-53.txt](https://github.com/argonlefou/DemulShooter/files/10610159/Debug_2023-02-04_11-36-53.txt)

Debug file attached. Given its worked well for you I went ahead and deleted the unity plugin files along with demulshooter and installed 10.9.3 but received the same results. As note I'm on Win 7 which I doubt matter but wanted to call that out.

I really appreciate you having a look. I hope its something obvious!

**Comment by argonlefou** [comment]
The most obvious thing is that you seem to have a dump with modified files, at least with a modified  `Assembly-CSharp.dll` file (which is the important part)

Celan dump file should work better.
To check it, check the MD5 hash of the file (there are tools for it) and the original one is `4f543c469818c1db8bc856be84f0131e`

**Comment by bojo5150** [comment]
I have 4f543c469818c1db8bc856be84f0131e and will give that a try today and report back. 

Thanks again for taking your time to look at this!
