### ISSUE TITLE
 Flycast outputs and others

### ISSUE THREAD

**Issue by faluki1983** [argonlefou/DemulShooter#116]
argonlefou, it seems that I have updated flycast to version 2.1 and your outputs have stopped working, could you update it later? One more thing, you will adapt the outputs for the new teknoparrot games (not standalone), Tomb Raider, Time Crisis 5, HOTD Ex, Target Terror Gold. Thank you for your great work.

**Comment by argonlefou** [comment]
Flycast 2.1 has been added in [today's 10.9.5 update ](https://github.com/argonlefou/DemulShooter/releases/tag/v10.9.5)

For the standalone games (Tomb Raider, Time Crisis 5) : I won't touch anything that is Teknoparrot related, as those games are working perfectly on their own without Teknoparrot.

HotdEx : I still have to find time to test it

Target Terror Gold : way too buggy for now to be interesting. But this in on the list for the future

**Comment by carolis15** [comment]
H Argon,

I always use Demulshooter like this:
P1 Sinden
P2 Wiimote with Touchmote as a 360 controller 
And it works great!
Unfortunately Flycast doesn’t recognize the controller as a valid input for a light gun. So only 1 player is possible. Is there any thing that can be done with Demulshooter? Thanks

**Comment by argonlefou** [comment]
Hi,

Nothing can be done regarding Inputs handling for Flycast. For many reasons (some technical, some not)

The best thing you can do is ask for this on [Flycast github](https://github.com/flyinghead/flycast)
Flyinghead is the only one able to add gamepad support to his emulator

**Comment by argonlefou** [comment]
> Hi Argon,
> 
> I always use Demulshooter like this: P1 Sinden P2 Wiimote with Touchmote as a 360 controller And it works great! Unfortunately Flycast doesn’t recognize the controller as a valid input for a light gun. So only 1 player is possible. Is there any thing that can be done with Demulshooter? Thanks

Flycast added gamepad analog stick support for light gun recently in the dev branch of the emulator
https://github.com/flyinghead/flycast/commit/192bbb715ea8efb10985c3fb67aa04e94bfe9ead
