### ISSUE TITLE
Silent Hill cursor exe compatability.

### ISSUE THREAD

**Issue by adamgp** [argonlefou/DemulShooter#12]
Hi, is it possible to also support the cursor version of the Silent Hill exe (KSHA.exe) for those of us that use semi-accurate AimTraks and rely on the on screen cursor instead of line of sight?

Thank you

**Comment by argonlefou** [comment]
Hi,
There are other ways to make have a cursor (mostly by using GameLoader AllRH, which is almost absolutely needed to play this game fullscreen) than using a different EXE 

BTW, I do agree that Aimtraks are not perfect, but "semi-accurate" is not the first thing I'd say about them...;-)
