### ISSUE TITLE
ninja Assault

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#122]
Salut, concernant ce jeux je suis certain d'avoir eu le retour de force avec Mamehooker...pourtant il decouvre bien la Rom donc ca devrait etre good..mais avec les dernières version je n'ai plus rien. il y a une cause à effet?
merci pour ton retour

**Comment by argonlefou** [comment]
Avec quel emulateur ? Demul ? Flycast ?

Que dit Mamehooker ? Il y a la liste des outputs ? La liste a des valeurs qui changent ?

**Comment by popo69200** [comment]
Salut Demul
mamehooker vois bien le jeux arriver et les output...ca bouge mais pas de FFB sur les flingues

**Comment by argonlefou** [comment]
Alors si les infos sont vues par MameHooker et que le Recoil bouge, DemulShooter envoie les données et elles sont lues.

Ce qui se passe ensuite (entre MameHooker et le gun) ....c'est à voir selon le gun qui est utilisé, mais c'est pas DemulShooter qui gère ça.
