### ISSUE TITLE
Virtua Cop 3 change weapon issue

### ISSUE THREAD

**Issue by BroKill** [argonlefou/DemulShooter#123]
Hello,

as title says I have issue changing weapon, doesn't work.

Your wiki says _**Configure START button as well as X gamepad button (Change Weapon) for both controllers.**_

I'm using an xbox controller and I mapped start on x button ( the blue one ). start works but no change weapon

I'm using latest emu build.

Also, I ask if is possible to hook only the axis and not the buttons because I like default mapping in CXBX-R.

Thanks.

**Comment by BroKill** [comment]
Solved, didnt map it in the emu, lol

Anyway, would be nice to have only axis hooked.

Thanks

**Comment by BroKill** [comment]
> If you're using an Xbox controller to play the game thanks to demulshooter, you should be able to use DemulShooter_GUI to map the buttons the same way they are in Cxbx

cant be done because your app doesnt recognize triggers as buttons and on L trigger is mapped what your app map for action button  :P

That's why I asked  :)

**Comment by argonlefou** [comment]
Oh, ok !

I don't own any Xbox controller, so I guess the triggers must be seen as Analog Axis instead of on/off buttons ?
Sadly I can't do much about it if it is the case :(

Thinking about it....does it mean that an Xbox controller is not working directly with an Xbox emulator ? (as you seem to use DemulShooter)

**Comment by BroKill** [comment]
I'm using DemulShooter because without it I get bad aiming.

Yes, triggers are like axis but many emus can bind them as buttons ( TeknoParrot, MAME, FlyCast, etc etc )

Thanks
