### ISSUE TITLE
The shared bullets of two players in Wild West Shoutout.

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#127]
When playing Wild West Shoutout, two players share bullets. Although their cursors are separate, when one player pulls the trigger, the other player also shoots.

**Comment by argonlefou** [comment]
I'm pretty sure it's something like #114 

You can post a debug file,
Check that nothing goes in the way in the game's install/plugins folder

I patched WWS yesterday to remove the whole NetDll error and the need to run the /trustlevel:0x20000 option but this has nothing to do with inputs

**Comment by cmjdbb** [comment]
The menu interface will have two red circular cursor alternately flashing.[
[Debug_2023-04-15_19-11-40.txt](https://github.com/argonlefou/DemulShooter/files/11239207/Debug_2023-04-15_19-11-40.txt)

**Comment by cmjdbb** [comment]
It should be that the mouse is not disabled, because after entering the game, two light guns can be played and the mouse can also be used.

**Comment by argonlefou** [comment]
Taken from your log :

> 11:42.996836 : MD5 hash of F:\光枪游戏\狂野西部射击场\狂野西部射击场免费版\CowBoy_Data\Managed\Assembly-CSharp.dll = b23419f61f323ab5b45300bff4126b80
19:11:42.996836 : /!\ MD5 Hash unknown, DemulShooter may not work correctly with this target /!\

I already told you the answer, look at #114

This is not a place to help people configuring games.
There is no bug related to mouse not beeing disabled, so case closed
