### ISSUE TITLE
Night Hunter

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#128]
Salut et merci pour cette update. tu peux me dire quel version de jeux fonctionne? la version sur virsman ne hook pas demulshooter. merci

**Comment by argonlefou** [comment]
Les 2 versions suivantes sont connues, vérifier le MD5 du fichier **_/qumo2_en_Data/Managed/Assembly-CSharp.dll_** :

Night Hunter v2.0.6 - Clean Dump :  md5 checksum =  1d6cbc2b0ebaf0bacbcbea84aa0f4a27
Night Hunter v2.0.6 - Dongle patched : md5 checksum = d223a04447e84073a178a14d50349da8

**Comment by cmjdbb** [comment]
ROM resources not found.

**Comment by cmjdbb** [comment]
Cannot find Dongle patched.

**Comment by cmjdbb** [comment]
Has been stuck in: Initializing
