### ISSUE TITLE
Has been stuck in: Initializing

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#129]
Has been stuck in: Initializing
[Debug_2023-04-15_22-48-26.txt](https://github.com/argonlefou/DemulShooter/files/11239781/Debug_2023-04-15_22-48-26.txt)

**Comment by argonlefou** [comment]
This is normal, the only available dump is missing files and will nor boot.
I'm not the owner of the good dump so just wait for it to be available to public
