### ISSUE TITLE
Virtua Cop 3 - Aim Issues

### ISSUE THREAD

**Issue by MarceloF1000** [argonlefou/DemulShooter#132]
Using DemulShooter 10.9.7.0 and GUN4IR.

Aim moves in random directions in mission select screen and during missions.

Aim works fine without DemulShooter hooked to the game.

Here is the debug file. Hopefully it will help find what is going on:
[Debug_2023-04-29_23-45-23.zip](https://github.com/argonlefou/DemulShooter/files/11359310/Debug_2023-04-29_23-45-23.zip)

When running with DemulShooter hooked, I use this control config in Cxbx:
![image](https://user-images.githubusercontent.com/108489071/235306470-525a4208-2f22-43bc-97e5-646c97abb390.png)

Without DemulShooter hooked, I use this control config in Cxbx:
![image](https://user-images.githubusercontent.com/108489071/235306526-61f79f27-2a76-4a81-b296-d1d7787f9fc8.png)

**Comment by MarceloF1000** [comment]
Tested with v 10.8.3

Aim is accurate with this version, but there is a huge 3 second input lag for any button pressed (trigger, reload).

**Comment by MarceloF1000** [comment]
Tried another combination: Cxbx Nov 20 2022 and DemulShooter 10.9.8

Aim is accurate, but input lag is still there. It starts with a 1 second lag and gets progressively worse. Unplayable unfortunately.

**Comment by argonlefou** [comment]
> Tried another combination: Cxbx Nov 20 2022 and DemulShooter 10.9.8

This is indeed the specified last known version in the wiki.
Now based of what I can see on your initial debug file, in-game calculated coordinates were good based on the position read from your lightgun and your screen/game position.
Unfortunatelly, it's impossible to have a beter visibility as I can't tell :
- Were the gun data good
- Were the in-game data succesfully written in the emulator memory.

> Aim is accurate, but input lag is still there. It starts with a 1 second lag and gets progressively worse. Unplayable unfortunately.
 
Be sure to remove the -v option from demulshooter if you're not debugging, this is the only cause of lag I can see.

**Comment by MarceloF1000** [comment]
I was careful to remove the -v option. The lag is there regardless. Not sure at this point what could be causing it. It only happens with DemulShooter hooked to the game.

**Comment by argonlefou** [comment]
I didn't get any lag last time I played through the game.

I'll try again within a few weeks if I have time to, to see if I can reproduce the behavior

I'll leave the ticket open if someone has the same issue

**Comment by MarceloF1000** [comment]
I was able to narrow down the issue to the Cxbx video configuration. Disabling v-sync resolved the issue. No more input lag.

**Comment by argonlefou** [comment]
Thanks for the feedback !
