### ISSUE TITLE
Far Cry: Heaven has no output

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#133]
Far Cry: Paradise used DemulShooter 10.9.8, mamehook CtmLmpStart has output all the time, but GunRecoil has no output.

**Comment by argonlefou** [comment]
https://github.com/argonlefou/DemulShooter/wiki/Debugging#step-3

**Comment by cmjdbb** [comment]
[Debug_2023-05-03_22-10-22.txt](https://github.com/argonlefou/DemulShooter/files/11383363/Debug_2023-05-03_22-10-22.txt)

**Comment by argonlefou** [comment]
Looking at the file, your inputs are not working at all (DemulShooter is not able to scale the gun to the game's windows, for an unknown reason)

So cursors won't move, buttons won't be recognized and if no buttons...no shoot and no outputs

**Comment by cmjdbb** [comment]
For some reason, the system was reinstalled, thank you
