### ISSUE TITLE
Change crosshair color in Night Hunter

### ISSUE THREAD

**Issue by carolis15** [argonlefou/DemulShooter#134]
When you press the key to change the color of the crosshair using Demulshooter is very sensitive if like you pressed it like 5 times in a second, so its difficult to be able to change it. I tried with Sinden, wiimote and keyboard and the result is the same. Thanks

**Comment by cmjdbb** [comment]
I know why. You're using mameshooter

**Comment by carolis15** [comment]
> I know why. You're using mameshooter

I´m not using Mamehooker

**Comment by argonlefou** [comment]
Hello, 
I'm still looking for other people having the same problem and a way to reproduce it.

I couldn't make that behavior to happen at home so far

**Comment by argonlefou** [comment]
Small up : I managed to reproduce that behavior, so I'll be able to investigate

**Comment by argonlefou** [comment]
Should be corrected in v10.14 update
Feedbacks are welcomed

**Comment by carolis15** [comment]
Unfortunately the problem continues, it is as if the key had a turbo function activated. Should I install everything from scratch?

**Comment by argonlefou** [comment]
Not from scratch but you will need to replace the unity plugin with the one from the last release package.

Sorry, I forgot to explain that the change was in the DLL plugin and not in DemulShooter itself

**Comment by carolis15** [comment]
I just replaced, the result is the same

**Comment by argonlefou** [comment]
Ok, I'll search for another way to handle that next week

**Comment by argonlefou** [comment]
Is it better with this ?
[NHA2_BepInEx_DemulShooter_Plugin.zip](https://github.com/argonlefou/DemulShooter/files/11721883/NHA2_BepInEx_DemulShooter_Plugin.zip)

**Comment by carolis15** [comment]
Works like a charm! Thanks

**Comment by argonlefou** [comment]
Good ! I'll put the file on the next release
