### ISSUE TITLE
Any chance for RPCS3 demulshooter?

### ISSUE THREAD

**Issue by Dradyoz** [argonlefou/DemulShooter#135]
Any chance for RPCS3 demulshooter?

**Comment by argonlefou** [comment]
DemulShooter is ready for System 357 games on RPCS3 (Deadstorm, Sailor Zombies, Dark Escape)
I jusg didn't have time to publish the release.

Hopefully in the start of the next week

**Comment by cmjdbb** [comment]
The Demulshooter for 357 v10.9.9 plugin does not support Deadstorm Pirates Special Edition. It does not matter whether the cache files are changed or not.The other 357 games are normal
[Debug_2023-05-14_15-23-47.txt](https://github.com/argonlefou/DemulShooter/files/11471364/Debug_2023-05-14_15-23-47.txt)
