### ISSUE TITLE
Demulshooter configure up to 4 players for rabbids hollywood

### ISSUE THREAD

**Issue by Adanas2009** [argonlefou/DemulShooter#136]
Can you configure up to 4 players on arcade games that support up to 4 players on demulshooter? Because I have tried configure my mouse to control all 4 players for Rabbids Hollywood, but it is not working for a certain reason. Can you not use one device to control all 4 players? Do I actually need multiple devices (like Wii remote light guns and/or Sindin light guns) to configure all 4 players? Also, how exactly do you configure all 4 players with demulshooter?

**Comment by argonlefou** [comment]
- Demulshooter already supports 4 players for games that allow if (Wartran Trooper, Gaia Attack 4, Rabbids Hollywood, etc...)

- Simple mouse won't work with DemulShooter. You neeed a lightgun, a touchscreen or a gamepad

- Use DemulShooter_Gui to configure devices for each player. You can set the same device for all player but there's no guarantee that it will work as expecter.
https://github.com/argonlefou/DemulShooter/wiki/Configuration#demulshooter_guiexe
