### ISSUE TITLE
The Demulshooter for 357 v10.9.9 plugin does not support Deadstorm Pirates Special Edition.

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#137]
The Demulshooter for 357 v10.9.9 plugin does not support Deadstorm Pirates Special Edition. It does not matter whether the cache files are changed or not.The other 357 games are normal
[Debug_2023-05-14_15-23-47.txt](https://github.com/argonlefou/DemulShooter/files/11471780/Debug_2023-05-14_15-23-47.txt)

**Comment by argonlefou** [comment]
10.9.9 is not an official release. You might have gotte a work-in progress build.

Official release should be published in the next few days, along with an updated wiki.

That beeing said, looking at the debug file :rpcs3-gun.exe process is not found, that's why demulshooter is waiting

**Comment by cmjdbb** [comment]
Upgraded 10.10.0, cleared the cache, started the game, then shut it down, patched it again, then started the game first, then started DemulShooterX64.exe, still not working
[Debug_2023-05-16_10-29-03.txt](https://github.com/argonlefou/DemulShooter/files/11483463/Debug_2023-05-16_10-29-03.txt)

**Comment by cmjdbb** [comment]
Thank you. That's all right
