### ISSUE TITLE
Namco 357

### ISSUE THREAD

**Issue by faluki1983** [argonlefou/DemulShooter#138]
Could you also support Razing Storm?

**Comment by argonlefou** [comment]
I/O board is not emulated on this one 
No support possible untill the game is made playable by the emulator team

**Comment by glassbox-sco** [comment]
Bumping this. Is it possible to get time crisis 4 outputs. Thx

**Comment by argonlefou** [comment]
> Bumping this. Is it possible to get time crisis 4 outputs. Thx

There is no TC4 arcade game available for RPCS3 (razing storm is a different game)

TC4 console game has - obviously - no outputs
