### ISSUE TITLE
Mouse device not work correctly

### ISSUE THREAD

**Issue by luffytam** [argonlefou/DemulShooter#14]
My Logitech G102 doesn't work correect in Demulshooter
when I test mouse movement in ds_diag.exe, the RawInput always in static value like 
0x0000,FFFFFFFF
0X0000,0001
0xFFFFFFFF,0000
caused DemulShooter never work on all gun shooter game 

here's video explain my issue
https://cdn.discordapp.com/attachments/371717581960118313/680780065704902696/Desktop_2020.02.22_-_22.12.11.01.mp4

is it caused by some joystick emulator such as Vjoy or ppjoy?

**Comment by kim-sama** [comment]
Because it only works for guns and Wii remotes

**Comment by argonlefou** [comment]
Exactly, and this is the purpose of DsDiag.exe  : that way you can see that your device is not compatible.

But usually, regular mice will not work with DemulShooter.
