### ISSUE TITLE
Rambo.The.Video.Game. Hope to add your plan?

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#140]
Sorry to ask you here, because the forum has banned registration: Rambo.The.Video.Game. Is a real light gun game, hope to add your plan?

**Comment by cmjdbb** [comment]
It is a rail shooter game that supports two-player mode. The storyline is relatively long and similar to Afghanistan.

**Comment by argonlefou** [comment]
You already asked the same question 2 month ago : #125 
You already got an answer
