### ISSUE TITLE
PCSX2 and RPCS3 (non arcade!) - will it get demulshooter

### ISSUE THREAD

**Issue by Dradyoz** [argonlefou/DemulShooter#141]
I know that RPSC3 - gun/arcade has it, this is not about that great work. This is about PCSx2 and the non-arcade RPSC3  - needs demulshooter desparately.

**Comment by thatman84** [comment]
PCSX2 has 2p raw input support now, no real need for Demulshooter

**Comment by argonlefou** [comment]
This has been asked and answered already, many time (but not necessary here on github)

There will be no DemulShooter for console game/emulators

**Comment by Dradyoz** [comment]
thanks for the update and thanks for being so awesome on this product
