### ISSUE TITLE
Gundam spirit of zeon in entering a name for the leaderboard, a double clicking occurs

### ISSUE THREAD

**Issue by dante3732** [argonlefou/DemulShooter#142]
After passing the game, you are given to enter a name, when you pull the trigger, 2 letters are pressed at once instead of one. Maybe this is the problem of not working hand-to-hand combat?

For hand-to-hand combat, you need to press the firing button and the bazooka button at the same time.

**Comment by argonlefou** [comment]
Hello,
To be honest I never played it to the end...
I will need to find a way to access quickly that part of the game, it's not possible to spend a full playthrough time just to check that each time I change something

And it's true that Gundam isn't the best job I've done for controls :/
It will definitely need a start from scratch one day (at least to fix the axe control)

**Comment by dante3732** [comment]
> It will definitely need a start from scratch one day (at least to fix the axe control)
Perhaps the axe just doesn't work because of a double click.

**Comment by dante3732** [comment]
If you can't fix the axe in gundam, then please add the optional ability to use demulshooter only to intercept the sight, and the buttons so that you need to reassign from the keyboard and mouse.

**Comment by argonlefou** [comment]
> If you can't fix the axe in gundam, then please add the optional ability to use demulshooter only to intercept the sight and pedal systeam, but buttons so that you need to reassign from the keyboard and mouse.

Sorry, but I don't understand what you are trying to ask

**Comment by dante3732** [comment]
> > If you can't fix the axe in gundam, then please add the optional ability to use demulshooter only to intercept the sight and pedal systeam, but buttons so that you need to reassign from the keyboard and mouse.
> 
> Sorry, but I don't understand what you are trying to ask

In order for the demulshooter  control only the location of the sight, without changing the standard control scheme on keyboard and mouse.

**Comment by argonlefou** [comment]
There is no point in doing that, standard mouse controls are not made to be used with lightguns :  

-Default "Canon" command is Right Mouse button : it's usually done by shooting off-screen, so you won't be able to shoot with the canon on screen while pointing out of screen at the same time to enable it.

-Default "Axe" command is Right+Left mouse button : here again, it's usually shooting in and out of the screen at the same time, which is not possible

**Comment by argonlefou** [comment]
Name entry issue, as well as Axe issue (by pressing Trigger+Canon) fixed in DemulShooter v11.0 release

**Comment by dante3732** [comment]
![metalslug](https://github.com/argonlefou/DemulShooter/assets/66036249/8da9b9ab-97c5-4ed7-a0be-debaaf90ce6b)

**Comment by dante3732** [comment]
> Name entry issue, as well as Axe issue (by pressing Trigger+Canon) fixed in DemulShooter v11.0 release

It works perfectly, the axe works as it should. I played the game again today.
