### ISSUE TITLE
System 357 : Pas de mouvement possible sur Gun Analogique

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#144]
Salut Argonlefou, j'ai 2 alien gun qui marchent avec demulshooter avec tous les jeux. Ici avec ta dernière mouture les jeux system 357 ne marchent pas uniquement pour le mouvement gauche droite haut bas. j'ai bien la fonction de tir.
J'ai 2 sidenlight gun qui eux marchent..je conclue que le pb est le Gun de type analogique ? 
J'ai bien param le gun qui est detecté sur GUI....la souris bouge si je l'utilise en jeux....mais pas les gun....
Y a t'il quelque chose à faire de special en plus?
Merci

**Comment by argonlefou** [comment]
Si il sont détectés dans le GUI et marchent avec d'autres jeux, aucine raison qu'ils ne fonctionnent pas avec rpcs3

Maintenant, avec un fichier debug ce sera plus facile de voir :
https://github.com/argonlefou/DemulShooter/wiki/Debugging#step-3

**Comment by popo69200** [comment]
j'ai pu refaire quelque tests hier. Donc en faite ce qui marche pas c'est avant le game. a la selection du perso dans Sailor Zombie ou de la carte sur Dead pirate. Je suis obligé de prendre la souris. en jeux les gun marchent et avec mamehooker nickel...il faut attribuer la touche de la manette via joy2key pour vraiment avoir un effet mitraillette. 
Dans les deux jeux la meme problématique en jeu justement, c'est que j'ai la souris qui apparait toujours en doublons de mon gun...du coup j'ai deux visée rose...ca fait pas beau a l'ecran...surtout quand tu ajoutes le gun 2 qui ajoute 2 lignée bleu sur l'ecran. Certes on peut les decaller un poil du milieu. mais ca gène dans le jeux...je me demande meme si ca tir pas a certain moment sur la visée de la souris et pas du gun. je te fait passer le log rapido. en tout cas merci...

**Comment by Bandicoot37** [comment]
juste a lire correctement le Wiki , il faut que demulshooter soit lancé apres le jeux donc mettre un delais , tu trouvera des Ahk pour cela

**Comment by popo69200** [comment]
que demulshooter soit lancé avant ou apres j'ai toujours 2 visées rose et bleu....et l a selection des map ou person ne marche qu'a la souris pas au gun...

**Comment by argonlefou** [comment]
Lancer DemulShooter apres c'est pour eviter un ecran noir au demarrage, rien a voir.
J'ai ma petite idée du soucis mais j'attend le log......

**Comment by popo69200** [comment]
[https://we.tl/t-QPvTrZLUaI ]
ci joint le debuf.
encore merci pour l'aide

**Comment by argonlefou** [comment]
Rien de visible dans le log

Le soucis dans l'explication...c'est que si le cache PPU est correctement patché (ce qui a l'air d'être le cas) les controles sont désactivés et la souris ainsi que le clavier ne sont plus fonctionnels (rien à voir avec DemulShooter, ça se vérifie sans le lancer)

Donc étape 1:
Lancer le jeu (sans demulshooter) et vérifier qu'aucun controle ne fonctionne. Si la souris fais bouger le curseur -> il y a un soucid dans le setup de l'emulateur

Si étape 1 est OK, étape 2:
Lancer demulshooter et la souris ne devrait pas mieux fonctionner...vu que le periphérique sélectionné est normalement le gun
Si la souris fonctionne avec Demulshooter de lancé il y a un soucis de configuration ou soucis matériel quelque part.....

**Comment by popo69200** [comment]
Donc je te confirme moi la souris marche dans le jeux. 
J'ai pris le dossier de jeux avec emulateur sur le site de virus..et ca me fait ça sur les 3. 
Il y a qq chose à désactiver qq part?

**Comment by Bandicoot37** [comment]
supprimer les fichiers du dossier cache , relancé l'emu sans demulshooter
patche le jeux avec demulshooter par le GUI de celui
et relancer le jeux puis demulshooter

**Comment by popo69200** [comment]
Bon c'est bien moi le boulet. Merci bandicoot ça marche 
Question sur dead pirate on fait comment pour faire gauche droite en jeu quand ça demande de bouger le bateaux?

**Comment by argonlefou** [comment]
C'est mappé sur la molette de la souris.

Sujet clos pour la suite, ce n'est pas un forum de discussion sur la configuration de l'émulateur
