### ISSUE TITLE
System 357 probleme sur player2

### ISSUE THREAD

**Issue by bromlecornu** [argonlefou/DemulShooter#145]
Salut mister,

J'ai installé deadstorm, sailorz et dark escape, ça marche top avec le player 1 mais quand je met le player 2 le curseur ne bouge pas. 

J'ai loupé qqchose ? 

Tu bosses sur razing storm en ce moment ? 

En tt cas super taff vraiment 

MERCI

**Comment by argonlefou** [comment]
> Salut mister,
> 
> J'ai installé deadstorm, sailorz et dark escape, ça marche top avec le player 1 mais quand je met le player 2 le curseur ne bouge pas.
> 
> J'ai loupé qqchose ?

Il y a une grosses poignée de paramètres qui peuvent expliquer pourquoi (materiel, configuration, installation, utilisation)
Surtout avec ce RPCS3 et le nombre de packs pre configurés qui tournent

La procédure est ici : https://github.com/argonlefou/DemulShooter/wiki/System-357

Pour de l'aide sur le paramétrage, je t'invite à chercher de l'aide sur Discord ou sur les forums 

Il n'y a pas de support de configuration ici


> Tu bosses sur razing storm en ce moment ?
Non
Tant que la team de dev qui bosse sur l'emulation du System 357 n'a pas émulé la carte I/O du jeu, personne ne pourra y jouer
