### ISSUE TITLE
output flycast night builds

### ISSUE THREAD

**Issue by faluki1983** [argonlefou/DemulShooter#149]
It seems that the outputs do not work with the latest flycast night builds

**Comment by argonlefou** [comment]
It's specified on the wiki :
https://github.com/argonlefou/DemulShooter/wiki/Flycast

Compatible with v2.1 stable

Any recompilation of flycast binary will change the memory addresses and thus will break demulshooter compatibility.
And I can't spend hours to search everyday for new addresses to follow the Flycast rythm
