### ISSUE TITLE
Crosshairs for LE3 

### ISSUE THREAD

**Issue by unionjac13** [argonlefou/DemulShooter#152]
I know you’re busy, but if you have time, could you please look into adding crosshairs to LE3 please thank you so much

unionjac1313

**Comment by argonlefou** [comment]
Adding crosshair to a game needs a wrapper to hook DirectX API and insert drawing to the rendered picture.

There is none of this in DemulShooter, so it can't be done with it.

**Comment by unionjac13** [comment]
thx i know there are none in the game tp added just thought you could I
understand
