### ISSUE TITLE
Request - Rambo the video game

### ISSUE THREAD

**Issue by Dradyoz** [argonlefou/DemulShooter#156]
yes its a dodgey shooting game from about 100 years ago but its rambo the video game - https://archive.org/details/rambo-the-video-game  the mouse works well but doing it with a lightgun :( :( ;( is there some magic you can apply to this game for us ?  This is not the same as Rambo via Teknoparrot many thanks in advance for at least reading the request - your work is highly valued.

**Comment by argonlefou** [comment]
Duplicate : 
#140 
#125 
#43
