### ISSUE TITLE
Western 1849 reloaded and Panzer Dragoon: Remake

### ISSUE THREAD

**Issue by gustavoalara** [argonlefou/DemulShooter#157]
Hello Argonlefou,

 I was wondering if it's possible to add lightgun support to these two games: Western 1849 Reloaded and Panzer Dragoon: Remake. Both support mouse input, but not lightgun, and from what I've seen, they both use Unity, just like other games you've provided support for. That's why I thought it might not be too complicated for you.

As always, thank you so much in advance for your help and for your wonderful software.

**Comment by argonlefou** [comment]
Hello

I don't think any of these game has 2 players gameplay available, so there is no need to create a DemulShooter plugin to play.

A simple "Mouse" support plugin has been mentionned here for Panzer Dragoons : #119 
The important point in my answer was : 
>DemulShooter is only needed with the plugins when I have to handle multiples lightguns/devices and raw input for multiplayer
