### ISSUE TITLE
House of the Dead 2 PC

### ISSUE THREAD

**Issue by aguskapool** [argonlefou/DemulShooter#16]
Hello! Im new in here, i just want to ask how to make it work, i made it work in Sega Model 2 and Sega Naomi, im trying to play it with dual Wiimote, im using Touchmote configurated as a xbox joystick because that is the way a tutorial in YT was configurated for sega model 2, for sega naomi i just fallowed your guide, and now i tryed on House of the Dead 2 PC and nothing, the pointer, buttons and all just dont work.

**Comment by argonlefou** [comment]
Hello,
The first thing to do is to share your debug file.
Run :  demulshooter.exe -target=windows -rom=hod2pc  
And share your debug.txt file from demulshooter's folder

**Comment by aguskapool** [comment]
First thing, i dont have any debug file on my folder, i just have this.
[https://subefotos.com/ver/?6e46c1114790fd186b19357988ba8f14o.png](url)

**Comment by aguskapool** [comment]
And this is how i have my demulshoter.exe
[https://subefotos.com/ver/?72d0bc779fa742b0898fb693106cc112o.png](url)
this is how i have my HOTD2
[https://subefotos.com/ver/?d733462cbbba58f60600a0e87d5dd083o.png](url)
this is my touchmote config for hotd2
[https://subefotos.com/ver/?75862a85426b55acc26aa74c91c51ecao.png](url)
[https://subefotos.com/ver/?323c300b79b9d97e7ab6c0931b4ea673o.png](url)

**Comment by argonlefou** [comment]
sorry I forgot a thing in my previous command line : 
demulshooter.exe -target=windows -rom=hod2pc -v

And don't use DemulShooterX64.exe, it's not for this game

**Comment by aguskapool** [comment]
Its still not working, it doesnt make anything

**Comment by aguskapool** [comment]
For beeing more precise, it don't move the cursor, dont shot, dont anithing, its like you didnt connect anithing, one thing that i noted is that all the hod2 that i downloaded arent binded like you said on the rules... 
P1 Start = ENTER
P1 Trigger = R.SHIFT
P1 Reload = R.CTRL
P2 Start = TAB
P2 Trigger = L.SHIFT
P2 Reload = L.CTRL

and all the hod2 that i downloaded worked the same,
P1 Start = ENTER
P1 Trigger = Space Bar
P1 Reload = none (or at least i didnt find it)
P1 CURSOR WITH ARROWS
P2 Start = L.SHIFT
P2 Trigger = TAB
P2 Reload = L.CRTL
P2 CURSOR WITH NUM PAD

**Comment by argonlefou** [comment]
Yes, it's another release, which has been added in one of the latest release and should work perfectly.

But if you don't get a debug.txt file by running the command I gave you, there is something wrong in what you do (demulshooter may not be running at all or may not be hooking the game)
Without it, I can't help you

**Comment by aguskapool** [comment]
I dont know if the game its not be hooked to the game, because when i close the game the demulshooter icon on the bottom right part of the desk window closes inmediatly, and i wish to know how to get a debug file, but i dont know how to make it, i just have that things that i showed you, if you dont mind do you have a discord or something to contact you?

**Comment by aguskapool** [comment]
I dont know why but it appeared... take this... 
https://www.mediafire.com/file/kmcnvm6ih3ab4z3/debug.txt/file?fbclid=IwAR3O3gyLuxvyGDE_HCM5EqVTngThaibOdz-dfAmoQh-NTiM90J4juvslwIc

**Comment by argonlefou** [comment]
Thanks ! This helps a lot
This is something I sure will happen someday with this kind of games with multiples release/exe/patch.

To fix this, this is what you can try:  
1 - Go into Demulshooter's /MemoryData/windows/hod2pc subdirectory
2 - You should see 3 .cfg files, make a backup of them (or if you don't want to bother you'll find them in your demulshooter zip file)
3 - Rename **_fd53bc12b72958c819cf6931787df3cb.cfg_** to **_a54ec23a78d07a78653bbd31919db0b5.cfg_**
4 - Test again, hopefully this should work
5 - If not, another debug.txt file may help again

**Comment by aguskapool** [comment]
Ok... reload working, and shoot working, but not cursor working, here you have the link
http://www.mediafire.com/file/9de9uundtxzm6dd/debug.txt/file

**Comment by argonlefou** [comment]
You didn't do what I told you previously correctly, here's why (says the debug file) :

> _File not found : C:\Users\ARCADE\Downloads\DemulShooter_v8.7.0\MemoryData\windows\hod2pc\a54ec23a78d07a78653bbd31919db0b5.cfg_

Please read carrefully and try again

**Comment by aguskapool** [comment]
I did make what you said, look
[https://subefotos.com/ver/?8f001af7c3a66a9e4991f999bdba00ddo.png](url)

**Comment by aguskapool** [comment]
I mean... with your modification what worked was the reload and the gun... but not the cursor, and that snap show you that i did what you said me to do

**Comment by argonlefou** [comment]
Can you send me and e-mail to argonlefou@gmail.com ?

**Comment by aguskapool** [comment]
Yeah sure!

**Comment by argonlefou** [comment]
Issue solved : a .cfg file for that version of HOD2.exe will be added in future release
