### ISSUE TITLE
Spirits of Zeon revert controls to normal?

### ISSUE THREAD

**Issue by MrKillultra** [argonlefou/DemulShooter#160]
I read on the main website that the controls for Spirits of zeon was altered to best suit the aimtrack. Specifically the middle mouse button was used to fire the bazookas and as one of the buttons to activate the axe attack. This causes a serious incompatability issue with the MAYFLASH Wireless Sensor DolphinBar which acts a lightgun by emulating a mouse. Its trigger acts as left click and its A button acts as a right click. It operates fine without the control change but once demulshooter is activated and controls are altered it is no longer able to play the game. Is there a way to toggle or otherwise revert back to normal controls for non-aimtrak equipment?

![image](https://github.com/argonlefou/DemulShooter/assets/139000653/898aa7a6-9122-4706-b784-5f3c54d8624a)

**Comment by MrKillultra** [comment]
Nevermind found a fix. Just use the virtual mouse buttons and map it to the d-pads. Not sure if this works on other types of equipment though.

**Comment by argonlefou** [comment]
Hi
The part you quoted from the wiki explain precisely why controls can't be back to original. It's fine for a mouse but impossible to play for lightgun

Virtual buttons were indeed created for these matters, to let the user a way to swap controls.
If there is no way to map a button to one of the key, there are also a way to map them with autohotkey
