### ISSUE TITLE
Operation ghost

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#161]
Hello, j'ai le mode mitraillette qui marche pas avec mon gun ir. Ca vient de demulshooter ou de mamehooker? Sur mes gunalien c'est good
 Mais en gun4ir si je laisse appuyer sur la gachette ca n'use pas les balle et ca ne claque pas.
Merci

**Comment by argonlefou** [comment]
La réponse est dans la question : si DemulShooter fonctionne avec des gun aliens, le soucis est ailleurs
