### ISSUE TITLE
Virtua Cop 3 P1 and P2 Start Not Working

### ISSUE THREAD

**Issue by kim-sama** [argonlefou/DemulShooter#163]
I set the controller inputs to start the game, but when I run Demulshooter then the game, the start button doesn't work, no inputs at all. When I try to run cxbx.exe alone and load the rom from there, the inputs will work. But I don't get a single input when I run the game with cxbxr-ldr.exe

**Comment by argonlefou** [comment]
DemulShooter is not handling START button, the emulator does (what's why it's asked to set it inside the emulator controls settings).

Just tested DemulSHooter v11.1 with latest available cxbx : CI-e1ea10c (Sun, Sep 3, 2023 8:45 PM)
Everything is working fine : 
- Axis and gun buttons with DemulShooter
- START button with the Emulator
