### ISSUE TITLE
 typing of the dead overkill 

### ISSUE THREAD

**Issue by helshaks** [argonlefou/DemulShooter#164]
Hi , 
there s not target for demulshooter to hook on  typing of the dead overkill  in the wiki

**Comment by argonlefou** [comment]
Hi,

You can find the target [Here](https://github.com/argonlefou/DemulShooter/wiki/Windows-games#the-house-of-the-dead--overkill) for House of the Dead Overkill

I've just added a copy of that in the [House of the Dead : Overkill WIKI section](https://github.com/argonlefou/DemulShooter/wiki/Windows-games#the-house-of-the-dead--overkill)

**Comment by helshaks** [comment]
thank you for adding the command line : )

on a different note any chance of having a support from demulshooter for
windows blue estate   ?    : )

**Comment by argonlefou** [comment]
> on a different note any chance of having a support from demulshooter for windows blue estate ? : )

No

There is a patch existing somewhere on the internet to allow 2p with this game, made by Mystery Wizard.
You should find some explanations [Here](https://www.sindenwiki.org/wiki/Blue_Estate) 

Never tried it myself, so I can't help

**Comment by helshaks** [comment]
Yeah , I have tried that already...so far it only detect aimtrack or sinden
...on my cabinet a use Alien extraction gun usb there are like big
joystick,  so far demulshooter is the best tool for those

Thx anyway hope to see more game support in the future 🤟
