### ISSUE TITLE
Rcps3 2 player Lightgun Support

### ISSUE THREAD

**Issue by Rocamoyas** [argonlefou/DemulShooter#167]
Hello Argon!. Would it be possible to use demulshooter for RCPS3? I have Time Crisis 4 and Razing Storm configured and working very well. But the RPCS3 does not have support for 2 light guns. I'm also using demulshooter for System 357 and it works great. That's why it occurred to me that maybe something similar could be done for the other PS3 light gun games. Thank you very much for all your work!

**Comment by argonlefou** [comment]
Hello,

Duplicate from #141
