### ISSUE TITLE
gun4ir and retroshooter auto confi 

### ISSUE THREAD

**Issue by leo0626** [argonlefou/DemulShooter#168]
HI, sir 

I have 2 gun4 ir and 2 retroshooters,  
I just wander if i can make automation config and gun and plug and play., 
for example. If i already configed my gun1 is gun4ir vid_8042, gun2 is vid_8043, And I opened demulshooter gui, and select each. and then the config.ini is created. but If i creaste another set is retroshooter vid_5701 for p1 and Vip_5702_for p2. then I will create anther config,ini. 
My question is how can i make it plug and play if i switch the gun between gun4ir and retroshooter? 
Please hlep

cheers

**Comment by argonlefou** [comment]
You can simply create and store your 2 different config.ini files (using names like config_gun4ir.ini and config_retroshooter.ini)

Then use a script (.bat or .ahk) to copy and overwrite DemulShooter config.ini file with the desired one, before running DemulShooter command
