### ISSUE TITLE
Operation Wolf First Mission v11.2

### ISSUE THREAD

**Issue by Plaasvark** [argonlefou/DemulShooter#169]
Thank you so much for support this now. Unfortunately it does not seem to work.

The mouse input and light gun don't move or shoot for me. 

I have the GOG version.

**Comment by argonlefou** [comment]
It does work, but you need to make sure you properly installed the unity plugin.

And also make sure your firewall is not blocking demulshooter or the game 

Then, as usual, provide a [debug file](https://github.com/argonlefou/DemulShooter/wiki/Debugging)

**Comment by Plaasvark** [comment]
Hi there. Please find attached the debug file. 
[](url)
[Debug_2023-10-12_15-48-05.txt](https://github.com/argonlefou/DemulShooter/files/12883926/Debug_2023-10-12_15-48-05.txt)

**Comment by argonlefou** [comment]
Thanks
What guns are you using ?

**Comment by Plaasvark** [comment]
I'm using Gun4IR..

**Comment by argonlefou** [comment]
Ok, I'll give you some procedure to get log on unity's side on monday

**Comment by cmjdbb** [comment]
I also used Gun4ir and it didn't work either, the icon in the bottom right corner is green and shows it's ticked.
[Debug_2023-10-13_19-40-54.txt](https://github.com/argonlefou/DemulShooter/files/12893054/Debug_2023-10-13_19-40-54.txt)

**Comment by argonlefou** [comment]
> I also used Gun4ir and it didn't work either, the icon in the bottom right corner is green and shows it's ticked. [Debug_2023-10-13_19-40-54.txt](https://github.com/argonlefou/DemulShooter/files/12893054/Debug_2023-10-13_19-40-54.txt)

From your debug, unity plugin is not installed or blocked.
DemulShooter is not connected to the game plugin

**Comment by cmjdbb** [comment]
Thank you for your reply, I copy Unity to the game directory, can hook, but enter the game for a while automatically decoupled. That's what happened over and over again.
[Debug_2023-10-13_22-29-37.txt](https://github.com/argonlefou/DemulShooter/files/12894622/Debug_2023-10-13_22-29-37.txt)
[Debug_2023-10-13_22-30-51.txt](https://github.com/argonlefou/DemulShooter/files/12894625/Debug_2023-10-13_22-30-51.txt)

**Comment by carolis15** [comment]
I´m using Sinden, and Demul crashes when I pull the trigger
[Debug_2023-10-13_09-03-54.txt](https://github.com/argonlefou/DemulShooter/files/12900235/Debug_2023-10-13_09-03-54.txt)

**Comment by argonlefou** [comment]
> I´m using Sinden, and Demul crashes when I pull the trigger [Debug_2023-10-13_09-03-54.txt](https://github.com/argonlefou/DemulShooter/files/12900235/Debug_2023-10-13_09-03-54.txt)

What are you meaning by crashing ?
I see at least 2 trigger press in the debug si DS is still running after the 1st one

**Comment by jadflat** [comment]
Thanks for adding support.

I'm using Sinden guns and have copied the unity files across to the game's main directory and demul appears to be hooking with the green icon.
Soon after starting the first level the crosshair freezes after one or two shots. Here's a log for file.


[Debug_2023-10-14_20-00-09.txt](https://github.com/argonlefou/DemulShooter/files/12903883/Debug_2023-10-14_20-00-09.txt)

**Comment by carolis15** [comment]
> > I´m using Sinden, and Demul crashes when I pull the trigger [Debug_2023-10-13_09-03-54.txt](https://github.com/argonlefou/DemulShooter/files/12900235/Debug_2023-10-13_09-03-54.txt)
> 
> What are you meaning by crashing ? I see at least 2 trigger press in the debug si DS is still running after the 1st one

Sorry I wasn’t more specific, it crashes when I press the trigger into the first mission. There’s no problem in the menu

**Comment by rguisadoss** [comment]
I use aimtrak and when you are going to start shooting you shoot and after two seconds the sight freezes and you can't do anything

**Comment by cmjdbb** [comment]
When you press the right button to change the bullet, player 1 and player 2 are opposite, and player 1 will show that player 2 is changing the bullet. Players 1 and 2 cannot select the same gun at the same time, otherwise the cursor will not move.

**Comment by Plaasvark** [comment]
Could it these issues be caused by the operation system we using. I'm on windows 11.

**Comment by cmjdbb** [comment]
I was able to play normally at first, but after reinstalling the system, and also like you, after pulling the trigger a few times, the cursor stopped moving and all operations could not be operated

**Comment by Plaasvark** [comment]
I've notice something.. When you click on trigger it actually kills the demulshooter application.. That is why it stops working or freezes. 

Even though the application seems like it's still running on the taskbar it's not. If you click on the taskbar demulshooter icon it will disappear. Its no longer hooked.

**Comment by argonlefou** [comment]
DemulShooter crashing and causing control not working anymore after a couple of shots seem to be tied to a bug regarding Outputs.

For anyone having this issue (@rguisadoss , @Plaasvark , @carolis15 , @cmjdbb ), could you : 
- confirm that Outputs are disabled in DemulShooter_GUI in your current configuration
- confirm that enabling Outputs in DemulShooter_GUI removes the bug

thanks

**Comment by Plaasvark** [comment]
@argonlefou  YOU are a LEGEND!... It works. I can confirm controls are now working and no crashing.. Thank you...

**Comment by jadflat** [comment]
> DemulShooter crashing and causing control not working anymore after a couple of shots seem to be tied to a bug regarding Outputs.
> 
> For anyone having this issue (@rguisadoss , @Plaasvark , @carolis15 , @cmjdbb ), could you :
> 
> * confirm that Outputs are disabled in DemulShooter_GUI in your current configuration
> * confirm that enabling Outputs in DemulShooter_GUI removes the bug
> 
> thanks

thank you, this worked for me

**Comment by argonlefou** [comment]
Fixed in v11.3 update
