### ISSUE TITLE
Sinden Light gun Outputs

### ISSUE THREAD

**Issue by Rocamoyas** [argonlefou/DemulShooter#171]
Hello. I wanted to ask you if it is possible to use the outputs option in the sinden light gun? Thank you so much.

**Comment by argonlefou** [comment]
Outputs option enable outputs messaging with MAME protocol.
MameHooker is usually used to get Outputs and activate hardware, but any software understanding the protocol can also do it.

This is not targetting any specific lightgun, so output compatibility with your gun will depend on the device itself and how it can be controlled
