### ISSUE TITLE
Demul output

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#176]
Salut, sur les jeux demul j'ai mamehooker qui recoit bien une info mais jai pas de retour de force..je suis certain que ca marchait avant. J'ai loupé un truc? Merci

**Comment by argonlefou** [comment]
Si MameHooker reçoit bien les infos et qu'elles sont correctes (valeurs, etc...), le soucis se trouve dans la configuration de MameHooker / lightgun.
