### ISSUE TITLE
Virtua Cop3 - No start buttons

### ISSUE THREAD

**Issue by bdiederichs** [argonlefou/DemulShooter#177]
This game used to work fine, but I came back to it after a while and now I can't get the Start buttons to register.
I confirmed that the start buttons mapped in cxbx reloaded work when I launch the game through the GUI without Demulshooter.

But when I launch the game alongside Demulshooter,

Run, C:\DemulShooter_v10.11.1\DemulShooter.exe -target=chihiro -rom=vcop3

Run, cxbxr-ldr.exe /load "Virtual Cop 3\vc3.xbe"

 The start buttons for both player 1 and 2 no longer work
 
[Debug_2023-11-12_14-23-20.txt](https://github.com/argonlefou/DemulShooter/files/13328941/Debug_2023-11-12_14-23-20.txt)

**Comment by argonlefou** [comment]
Hi,

There was a similar issue opened here : #163 

What is the cxbx build you're using ?

**Comment by bdiederichs** [comment]
That sounds like my same issue.
I'm using Cxbx-Reloaded Version
74138d1 (June 2021)

I just downloaded the version you noted in the other ticket cxbx : CI-e1ea10c (Sun, Sep 3, 2023 8:45 PM) and tried that.
now my mapped buttons work again!

**Comment by argonlefou** [comment]
Nice !
