### ISSUE TITLE
suggestion for the next year = an Android port for the DemulShooter

### ISSUE THREAD

**Issue by Thetouchedjoe** [argonlefou/DemulShooter#178]
I think for this it's kinda impossible to port the game but is it possible to port DemulShooter to the Android like the features is example =
- there's an Arcade Stick to aim the crosshair with 2 buttons, one to Reload, one to Shoot with an Start button and the Service, Test and Credits button
- there's an Settings GUI like an Settings logo in the right side like example to remove crosshair, add patches and add plugins
- there's an button which to add games to the directory that opens in the file manager
(this for the future version of DemulShooter)

- when it's opens, there's a line like an X-Terminal which is you type the commands to add game in the directory that has the file in it and also for settings
(maybe the possible version of DemulShooter)

I guess that's it for the suggestion of the future

**Comment by argonlefou** [comment]
Hi,

Thanks for your suggestions.

Whereas a DemulShooter equivalent can be used in linux (in fact, it's already existing in a couple of linux-packed-vmware images I made years ago for Star Trek and Target Terror), Android is way too different to be able to do that.

Everything on the low-level (process handling, tasks, activities, hardware handling) is different

And everything on the OS side is too different too for that to be possible.

So, sorry but that won't be a possible things to do in the future
