### ISSUE TITLE
DemulShooter vs Flycast 2.2

### ISSUE THREAD

**Issue by baritonomarchetto** [argonlefou/DemulShooter#181]
Hello everybody, I am experiencing compatibility issues with Flycast 2.2 (no hook).

DemulShooter works good with the previous version (2.1) as stated in the wiki.

(Flycast 2.2 is a seminal release for positional gun users since it introduced joystick support for light games)

**Comment by argonlefou** [comment]
See #175

**Comment by baritonomarchetto** [comment]
thank you very much 👍

**Comment by argonlefou** [comment]
Added in Demulshooter v11.4 release

**Comment by baritonomarchetto** [comment]
I am sorry but it looks like it is still not working: MAMEHooker can hook, but only P1 and P2 lamps flash, all the "computed" outputs (i.e P1_CtmRecoil=) show no signs of life

**Comment by baritonomarchetto** [comment]
Made some more testing: it's actually lupinsho that doesn't work. mok works, ninnjaslt works. There must be something wrong with lupinsho then

**Comment by argonlefou** [comment]
Just tested right now with the release zip package downloaded : Lupinsho outputs are working good, just like other NAOMI games I tried (confmiss, ninjaslt)

**Comment by baritonomarchetto** [comment]
ok, there must be some error on my side, but I cannot spot it. I see Demulshooter correcly hook (green icon), MAMEHooker shows  all outs but only those related to lamps flash are reporting the state change, any other (even player damage) are not.
I will report if I find what I am doing wrong.

Thank you very much!

**Comment by baritonomarchetto** [comment]
Ok, works for me too after overwriting flycast's exe with the latest stable release. Maybe I used some nightly built doing my tests. 
Thank you very much for all your efforts!
