### ISSUE TITLE
DemulShooter_GUI displays abnormally

### ISSUE THREAD

**Issue by Ribingusim** [argonlefou/DemulShooter#182]
![11](https://github.com/argonlefou/DemulShooter/assets/146827072/a9b26b1a-7f0b-4c18-bae1-ae4f8d1b6ce6)

In the win10 Ltsc environment, the DemulShooter GUI screen displays abnormally when opening it. How to solve it?

**Comment by argonlefou** [comment]
Hello,

There are multiple options in Windows to change font size, zoom, text scaling for Display, you can try these options, even though it never had any impact on the application text rendering when I try to change them (it is just upscaling / zooming the whole application Window)

It looks like the good font is beeing used (MS Sans Serif) but the font size is too big.
I can see some foreign character on your screenshot (Chinese ?) so it may be tied to your OS settings for this country ?

Ultimately, you can try a right click on the DemulShooter_GUI exe and try to set compatibility mode with older windows (Xp, 7, etc.....) and check some options

**Comment by argonlefou** [comment]
1 year without answer, closing
