### ISSUE TITLE
Do you have any plans to add a dual wield railgun to Railbreak?

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#186]
Do you have any plans to add a dual wield railgun to Railbreak?

**Comment by argonlefou** [comment]
Hello,

According to [this message](https://steamcommunity.com/app/2587170/discussions/0/4042608198331785572/) , game is handling mouse, keyboard, lightguns and gamepads 

And according to [this one](https://steamcommunity.com/app/2587170/discussions/0/4031348734037664585/), they are explaining how to use Sinden in Joystick mode for dual player gameplay

So if you're railgun 's driver makes it behave like a gamepad (and this should be the case if DemulShooter can see it), you should hopefully use that to play Railgun

Now, if this is not the case : 
The game has been out for a couple of days, and Devs are seeking info to make things better so you better ask them to correct things.
Anyway, a game that recent, using Unreal Engine 5, is not something I can mod (at least not with my current skills/knowledge)... I'm sorry.

**Comment by popo69200** [comment]
dommage car ce jeu est top et la solution ne l'est pas du tout...avec un gunIR en mode joystick c'est injouable...peut etre que le dev qui a fait celui de bluestate essaiera de faire un petit patch...merci en tout cas pour le taf...on sait que tout prend du temps et tout n'est pas possible
