### ISSUE TITLE
Spirits of Zeon - DS not hooking

### ISSUE THREAD

**Issue by bojo5150** [argonlefou/DemulShooter#190]
When using teknoparrot (2 player split screen) I cannot get DS to hook the game. I tried both gsoz and gsoz2p with no luck. 

I’m just looking to configure outputs is all. (Maybe game doesn’t have any setup? Regardless of using TP?)

as always, thank you!

**Comment by argonlefou** [comment]
There's no specific support for TeknoParrot for games that are working fine on their own.
TP added these games long after their initial release to the public, and it sometimes needs some specific modified dump to work.  
Even with an unmodified dump, only TP dev knows what they changed and how they are altering the game's running process to make it work.

Same goes for Ring games, TTX games, etc...

Officially suported TP games with DemulShooter are the ones that really need TP to run (mostly, Linux games emulation : Lindbergh, Raw Thrill)

Now, back to Gundam : the game works fine standalone, even with dual split screen exe.
You just need to add the following custom resolution  to your Nvidia/AMD software panel : 1280x480 (as specified in the [wiki](https://github.com/argonlefou/DemulShooter/wiki/Taito-Type-X#gundam--spirit-of-zeon)

It's also 100% compatible with DgVoodoo to enhance graphics and ReShade to add bezels
