### ISSUE TITLE
Operation ghost

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#194]
Salut, operation ghost n'a plus de retour de force. Est ce due a une mise a jour? J'utilise tp et ca marchait avec demulshooter...ici demulshooter hook bien et passe au vert. Mamehooker voit la rom appelée Operation ghost
Dailleurs avant elle ne sappelait pas OG?
Et je n'ai pas de retour de force....
Merci pour ton aide.

**Comment by argonlefou** [comment]
Il n'y a pas eu de mise à jour impactant Operation Ghost depuis 8 mois.

Je viens de tester à l'instant avec Teknoparrot, tout fonctionne normalement et la rom est bien détectée en tant que "og" par MameHooker

![og](https://github.com/argonlefou/DemulShooter/assets/22789681/74089a4b-e9b3-4b5e-8865-c3df858f6f73)

**Comment by popo69200** [comment]
Cela sous-entend que je n'ai pas la bonne rom snif...
Merci pour ta réactivité

**Comment by popo69200** [comment]
Salut j'ai vraiment un soucis. Tu peux me donner ton gs2.ini stp?
