### ISSUE TITLE
Outputs Flycast 

### ISSUE THREAD

**Issue by carolis15** [argonlefou/DemulShooter#197]
Could it be possible to add output support for the newest version of Flycast (2.3)?

**Comment by argonlefou** [comment]
Hello, thanks for the info

I'll have a look at it in April, beeing away untill then

**Comment by argonlefou** [comment]
Untill the next release is packed and uploaded, unzipping the following config file into `/MemoryData/Flycast/` folder from DemulShooter should be enough to add flycast 2.3 compatibility :  

[d5e819796226078c6ce51dc8f304550b.zip](https://github.com/argonlefou/DemulShooter/files/14894575/d5e819796226078c6ce51dc8f304550b.zip)

**Comment by carolis15** [comment]
works great, the only problem I found is that HOTD2 is sending recoil outputs even before the game start and also in cutscenes

**Comment by argonlefou** [comment]
Hmmm.... I don't have any recoil events triggering like this on my computer. At least on hotd2 and hotd2o roms.
Haven't tested others for a long time

**Comment by carolis15** [comment]
It's weird, I can even empty the mag and reload in the cutscenes. I'm using hotd2 rom

**Comment by carolis15** [comment]
Maybe something is wrong with the ROM or with FC. Thanks

**Comment by argonlefou** [comment]
No no, thanks to your previous message (deleted or edited ?) 
`It's weird, I can even empty the mag and reload in the cutscenes. I'm using hotd2 rom`
I can confirm it's possible to do so

I first understood you had erratic recoil events firing alone during cut-scenes

I'll see if I can try to filter things a bit more to prevent the recoil to activate during cut scenes

But the fact that you can shoot and reload and empty the mag in that moment is game/emulation related
