### ISSUE TITLE
Walking Dead Raw Thrills

### ISSUE THREAD

**Issue by IntegrumRetro** [argonlefou/DemulShooter#198]
Was curious if you can provide output support for the new Walking Dead currently emulated on Teknoparrot?

**Comment by argonlefou** [comment]
I'll have a try, I still need to get back home and find all needed files ...and this will be on the top of the to-do (or to-try  😉) list

**Comment by argonlefou** [comment]
Walkind dead outputs added in v12.1 release

**Comment by IntegrumRetro** [comment]
And the world is a better place because of you! Thank you very much!
