### ISSUE TITLE
[Feature Request] Support for Flycast

### ISSUE THREAD

**Issue by adamgp** [argonlefou/DemulShooter#20]
Hi, I have discovered and been playing around with Flycast recently as a Demul alternative, as it is actively maintained, performs much better with fullscreen scaling as default and widescreen support. And lightgun support currently working for Player 1 via SDL input.

Therefore, is it possible to integrate DemulShooter with Flycast to allow control of the second Player? Support for LightGun and LightGunAsAnalog is now available - if that provides appropriate areas for hooking?

https://github.com/flyinghead/flycast/commit/98b2a32eae0b7a98d7652ba6c368986656c6d656

Thank you

**Comment by argonlefou** [comment]
Hi,
So far, Demul can still do a lot of things that Flycast can't (Mostly arcade games) and, even if I agree on the "non maintained anymore" sensation we can have on this emulator, there are a tons of things we can do to tweak display as wanted ( DgVoodoo for better 3d graphics, ReShade for everything else)

On the top of that, "actively maintained" program means a lot of builds and release and here are my 2 cents about that :  
1) I can't support a software which is going to break compatibility every 2 weeks with a new build.
2) As the Flycast  Devs are really working hard ( well, it seems to be the case at least), it's their job to add multiple lightguns support

So, I can change my mind in the future, maybe one day when FLycast will make Demul totally deprecated.
But for now Demul is still the way to go for Arcade gaming

**Comment by adamgp** [comment]
Thanks for your response, yes I totally agree regarding the active
development most likely breaking your compatibility regularly. I'll see
about pushing for native support of mouse devices Supermodel style whilst
development is still progressing strongly.

Thanks again.
