### ISSUE TITLE
Issues with "-noinput" parameter on Tomb Raider Arcade and Rabbids Hollywood Arcade

### ISSUE THREAD

**Issue by zenaro147** [argonlefou/DemulShooter#200]
Basically, when I try to run DemulShooter with the -noinput parameter for Tomb Raider or Rabbids, the program crashes as soon the game open and try to hook.

If I remove the parameter, DemulShooter still opens normally.

**Comment by argonlefou** [comment]
Oh yes, there's a thing with a lot of unity games with the **_-noinput_**

I'll fix that ASAP

**Comment by argonlefou** [comment]
Fixed in v12.2
