### ISSUE TITLE
Fix wiki ROM name for Jurassic Park Arcade

### ISSUE THREAD

**Issue by zenaro147** [argonlefou/DemulShooter#201]
on the wiki, for Jurassic Park, it says to use "jpark" as ROM, but using the -help parameter, is says to use "jp"

if you use jpark, it will say it's an invalid rom

**Comment by argonlefou** [comment]
Thanks for pointing this out, I just corrected it.

Wiki is manually edited so error (or missing items) can happen 😔

The _**-h**_ command is automatically filled with the code, so any time there's a difference, you should believe the program's help
