### ISSUE TITLE
Add support for Time Crisis Razing Storm Arcade RPCS3-gun

### ISSUE THREAD

**Issue by jcstahl1** [argonlefou/DemulShooter#202]
Is it possible to add support for Time Crisis Razing Storm Arcade running with RPCS3-gun yet?  I see that the option button is there but it is grayed out and there is not a profile in the folders for it.  I have the game itself running perfectly, just would love to have 2 player support.

**Comment by jcstahl1** [comment]
After searching a second time since I did not see them the first time, I see there are previously closed requests for this.  I suppose now we wait for the emulator team to officially make it playable and fully emulated.

**Comment by argonlefou** [comment]
Exactly !
