### ISSUE TITLE
Recoil output for Silent Hill Arcade always 0 (teknoparrot)

### ISSUE THREAD

**Issue by zenaro147** [argonlefou/DemulShooter#204]
[Debug_2024-04-19_11-25-25.txt](https://github.com/argonlefou/DemulShooter/files/15041849/Debug_2024-04-19_11-25-25.txt)

the recoil values on mame hook outputs for this game always still 0.
the lights values (only start and left/right) changes normally

**Comment by frizzo308** [comment]
I am having the same issue

**Comment by argonlefou** [comment]
Found a typo in the Output name, so P1/P2 custom recoil were never updated.
Fix will be added with the other ones you recently pointed out

**Comment by argonlefou** [comment]
Fixed in v12.2
