### ISSUE TITLE
Flycast Naomi F355 Challenge and Challenge 2 series (Twin versions) Output Lamp support

### ISSUE THREAD

**Issue by Francesco-75** [argonlefou/DemulShooter#205]
Can i ask if would be possible to have working Lamp outputs for the Naomi F355 Challenge and Challenge 2 Twin Series? I'm interested a lot on the race leader lamp support. Thanks in advance for your amazing work

**Comment by argonlefou** [comment]
Hello,
I'm not working on racing games, so the answer will be no.

**Comment by Francesco-75** [comment]
> Hello, I'm not working on racing games, so the answer will be no.

No problem, what you already do and for free is amazing. Thanks for the reply.
