### ISSUE TITLE
How to apply Update Demulshooter ? 

### ISSUE THREAD

**Issue by marcosgaming10** [argonlefou/DemulShooter#206]
Hi argonlefou,
Demulshooter it's incredible software!
I use version 12.00. I use it by a folder in my build launchbox on all platforms System and works perfectly with my 2 aimtrak....All preconfigured. 

Now I would update only version without Lose any settings on games.

How to do? I only want update version for support Walking dead and others news.

How to do? I ask you before. Thanks.

**Comment by argonlefou** [comment]
Hi, 
Just unpack the zip and overwrite old files.

Nothing id stored in register/appdata/temp folder on Windows

Just keep the config.ini file in DemulShooter folder, it holds all configuration items you set
