### ISSUE TITLE
Operation Ghost don't show crosshairs

### ISSUE THREAD

**Issue by marcosgaming10** [argonlefou/DemulShooter#208]
Hi guys, i use DemulShooter and Patch Resolution for full screen and the game works perfectly.
I would only see crosshairs of my light guns.
There is a fix ? Thanks..

**Comment by argonlefou** [comment]
Hi,
Sorry but I do not understand the question ?

**Comment by marcosgaming10** [comment]
Hi argo,
I can play with my 2 light guns but without crosshairs. I can only shot, not shows and move crosshair. Nothing. I don't apply path remove crosshair. I try clean dump too....

**Comment by argonlefou** [comment]
There is no options to remove crosshairs with demulshooter 
I did a no-crosshair patch, but this is a texture file to replace within the game folder.

So you may have downloaded a version with that file already replaced

But in that case there will be no croshair, with or without demulshooter
