### ISSUE TITLE
[Enhancement] Gamepad - do not go back to middle automatically

### ISSUE THREAD

**Issue by F3L1X79** [argonlefou/DemulShooter#21]
Bonjour à toi argonlefou,
Tout d'abord je tenais à te féliciter pour le travail de fou abattu sur les RIP émulation de manière générale - je viens de découvrir tous les launchers et les utilitaires que tu avais fait pour convertir les résolutions sur les jeux Arcade sur le forum d'Emuline - et maintenant ce fantastique soft DemulShooter ! Franchement bravo.

J'aurais une petite question concernant l'utilisation de DemulShooter avec un gamepad (une manette XBOX 360 pour être précis) n'ayant pas d'Aimtrak ou autre à la maison. Je me sers actuellement de DemulShooter pour pouvoir jouer à deux à la manette sur Haunted Museum 1 & 2 et ça marche sacrément bien ! 

Le truc que je me demandais c'est si c'était possible de désactiver l'auto center à la manette  ? Je m'explique , quand on relâche le stick, le crosshair retourne tout seul automatiquement au milieu de l'écran. Sur les versions PCs de House of the Dead (1 à 3), ça n'est pas le cas, et je trouve que c'est beaucoup plus pratique à jouer (En gros quand on relâche le stick, le crosshair reste là où il était). Est-ce une fonctionnalité qui serait envisageable de créer sur DemulShooter ?

J'ai la même souci avec les jeux MAME d'ailleurs. Je sais que ça ne te concerne pas mais si jamais tu connais la technique pour éviter ça je suis preneur....

Enfin, j'ai une dernière question concernant House of The Dead 4 de Lindbergh. Est-ce que DemulShooter peut permettre de rajouter un crosshair comme c'est le cas pour les jeux sur SEGA M2
 ou non ? J'imagine que c'est compliqué à faire et je pense que non, mais je préfère demander.

En tout cas bah merci d'avance pour ta réponse, et encore félicitations pour tes supers devs qui rendent des joueurs heureux. Bonne continuation ! :)

**Comment by argonlefou** [comment]
Salut,

Malheureusement ce que tu demandes pour la manette est impossible car c'est justement le but de DemulShooter que de fonctionner avec des coordonnées en mode "absolu".
Il faut garder en tête qu'à la base le programme est prévu pour les lightgun et que le support des manettes/joypad (bien qu'il soit prévu une grosse amélioration dans les jours qui viennent) est une conséquence collatérale du support des WiiMote converties en pad.
Donc tous les périphériques partageant la même gestion, un manette sera considérée comme un lightgun dont la position du stick sera l'equivalent de l'endroit ou un lightgun serait pointé sur l'écran.

Je n'utilise pas ce principe avec MAME mais pour corriger ton problème, il faut utiliser d'autres programmes. Peut être qu'un soft comme Joy2Pad (en mappant les axes de la manette sur les fleches du clavier) en parametrant MAME pour utiliser le clavier (avec les touches de direction pour les axes) pourrait marcher....

Pour ce qui est des crosshairs, ce n'est pas vraiment DemulShooter qui les ajoute : je ne fais que faciliter l'installation de scripts déjà existants et c'est surtout grâce à l'émulateur qui permet d’accéder à son moteur graphique via des scripts et y ajouter ce qu'on veut.
Ce n'est pas possible pour HOD4 donc ce système ne peut marcher. Il y a bien dans le code de Rambo un flag pour activer/desactiver le curseur mais je n'ai pas trouver de choses équivalente dans le code de HOD4 (ce qui ne veut pas forcement dire qu'il n'y en a pas au passage... ;))

Merci pour tout en tout cas, bon courage !

**Comment by F3L1X79** [comment]
Ok, merci pour toutes ces réponses claires et rapides !!
je comprends mieux pour les intégrations Joypad pas "prévues" mais en tout cas ça fonctionne bien quand meme et c'est très plaisant !! Tant mieux si tu as prévu une nouvelle amélioration dans les jours/semaines à venir, j'ai hâte de voir ça ! :)
Merci également pour l'explication concernant les crosshairs ! Pour HOD4, je pense que le crosshair est possiblement caché quelque part, car il apparaît à la fin sur l'écran de hi-scores; mais c'est une autre histoire du coup...
Je ferme le ticket :)
