### ISSUE TITLE
DemulShooter not work with Haunted Museum II

### ISSUE THREAD

**Issue by marcosgaming10** [argonlefou/DemulShooter#210]
Hi guys,
i'm setting all games of TeknoParrot with DemulShooter with 2 Lightguns. All it's perfect!
Why Haunted Museum II doesn't work ?

This is my script :
Run, D:\LaunchBox\ThirdParty\DemulShooter\DemulShooter.exe -target=ttx -rom=hmuseum2
and then launch directly game.exe not from TeknoParrot.

The game Crash soon. Seems that not works with "hmuseum2"
This game is very beautiful!

If i Launch only game.exe works only one LightGun. Second goes in conflict and appear always as first gun.
I need right connection with DemulShooter.exe

Please help me, other games are perfect with scripts and DemulShooter ...

**Comment by argonlefou** [comment]
The game crashing when DemulShooter is hooking it means it's either a wrong version of the game or totally the wrong game :

You need to be carefull as Haunted Museum 2 came in many different versions, one beeing called 'Fright Fear Land' from 'GlobalVR' distributor (see [Wiki](https://github.com/argonlefou/DemulShooter/wiki/Global-VR#fright-fear-land) and need to be used with a different demulshooter command

 A demulshooter  [Debug file](https://github.com/argonlefou/DemulShooter/wiki/Debugging#step-3) should be helpfull to get some information when your game is crashing

**Comment by marcosgaming10** [comment]
Argo you are the best !
In my case i have other version of game and works so :
-target=globalvr -rom=fearland
Thank you very much!
