### ISSUE TITLE
HOTD: Overkill (Steam) - No Outputs

### ISSUE THREAD

**Issue by PolybiusExtreme** [argonlefou/DemulShooter#211]
Hi, 
in the Steam-Version of HOTD: Overkill i have no outputs with DemulShooter. The game gets hooked with DemulShooter and Mamehooker. I can see the outputs in Mamehooker but the values don‘t change in-game.
Would be nice if you can fix it :)

**Comment by argonlefou** [comment]
Hi,
Can you provide a debug file ? 

https://github.com/argonlefou/DemulShooter/wiki/Debugging#step-3

**Comment by PolybiusExtreme** [comment]
[Debug_2024-05-29_12-10-02.txt](https://github.com/argonlefou/DemulShooter/files/15482744/Debug_2024-05-29_12-10-02.txt)
@argonlefou i uploaded a debug file for you

**Comment by argonlefou** [comment]
Thanks
It looks like the binary is different from the version I have.

I may need the exe to have a look at it, you can mail me (argonlefou@gmail.com) in order to talk about that part

**Comment by PolybiusExtreme** [comment]
@argonlefou i sent you a mail with the exe now

**Comment by argonlefou** [comment]
Should be fixed in latest v12.5 release
