### ISSUE TITLE
Missing outputs for some TeknoParrot games

### ISSUE THREAD

**Issue by PolybiusExtreme** [argonlefou/DemulShooter#212]
Hi, 
there are some TeknoParrot games that don‘t have outputs, but the standalone or jconfig versions have it.

Block King Ball Shooter (bkbs)
Friction (friction)
Gundam: Spirit of Zeon (gsoz)
Rabbids Hollywood Arcade (rha)
Time Crisis 5 (tc5)
Tomb Raider Arcade (tra)

Would be really nice if you can add the outputs for the TeknoParrot versions of the games too :)

**Comment by argonlefou** [comment]
Hi,

For the 2 unity games (Tomb Raider and Rabbids), I can't guarantee compatibility of my pluggins if TP is using modified versions (or even if it's using the common version and patching it at runtime) of the game.

For the other ones, it's either modding the common files at runtime or changing something somewhere, breaking the compatibility support.

Plus, all these game are fully working without the need of TP, so this is not something I'm planning to look into.
