### ISSUE TITLE
1st player trigger activates 2nd player recoil,outputs and Vise versa.

### ISSUE THREAD

**Issue by Prime91122** [argonlefou/DemulShooter#218]
Using Alien extermination guns with Mamehooker and  Demulshooter to get outputs/recoil for all gun games. I made a copy of my drive install into a new PC and all shooting games that are using Demul/MameHooker the recoils are inverted. Player one trigger activates player 2 recoil and vise versa. please help.

**Comment by argonlefou** [comment]
It's more of an issue with MameHooker like inverted COM port on the new computer, used in ini files commands to control your guns.
Copying drives to new computer without going through the hardware configuration is not without risks

It's not a DemulShooter issue, recoils are generated thanks to some game value, and is not related to any trigger press.
If the controls are not inverted (axis/trigger/reload) in-game, then it's not a DemulShooter issue.
