### ISSUE TITLE
Wiki Update: Gundam SOZ

### ISSUE THREAD

**Issue by adamgp** [argonlefou/DemulShooter#22]
I believe the docs are slightly inaccurate when it specifies about adding a customer resolution of 1280x640 when I believe it should be 1280x480 (as each screen is 640x480) so the dual EXE would require (2x640)x480.

Also the Japanese? documentation that comes with the Single or Dual screen EXEs specifies 1280x480 and this is the only custom resolution that worked for me.

**Comment by argonlefou** [comment]
Thanks for pointing out this unfortunate typo.
1280x480 is obviously the correct resolution to create, and the Wiki has been updated.
