### ISSUE TITLE
How do I use Network Outputs?

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#222]
How do I use Network Outputs? I first start DS, then launch pytty and enter 127.0.01 and port:8000, but nothing happens, and no files are generated. Does anyone have a working AHK script and example?

**Comment by SeongGino** [comment]
Not exactly sure what it is you're trying to do here to even offer help in this instance.

**Comment by argonlefou** [comment]
> How do I use Network Outputs? I first start DS, then launch pytty and enter 127.0.01 and port:8000, but nothing happens, and no files are generated. Does anyone have a working AHK script and example?

Make sure you start putty with Telnet protocol (not SSH as selected by default)

There will be no file created, but you'll see text in putty window changing according to the outputs that are sent.

Putty is just a way to check that outputs are sent, not the final way to use them.
For that you'll need a software to read outputs from the network (be it  local or distant) and associate actions to them, like MameHooker does

The one I know of today is [QMameHook](https://github.com/SeongGino/QMamehook), even if it's a young project

But the reasons I added that feature into DemulShooter is to make things easier if someone want to develop a future "MameHooker" replacement, as network dialing is way more reliable than the old outdated windows messaging events used by MameHooker
