### ISSUE TITLE
Feature request: add profile option

### ISSUE THREAD

**Issue by toccata10** [argonlefou/DemulShooter#223]
1st of all: a very big thank you for demulshooter. It has brought me countless hours of fun !
Maybe you could consider adding something like -profile="p1blue_p2red.ini" command line option to allow choosing between different configurations. I have one blue and one red gun. Depending on the game, P1 is either red or blue.
I would appreciate the ability to choose the setting profile from the cli.
Of course, a workaround is to include a copy command in an ahk script, but an option would be more straightforward.

**Comment by argonlefou** [comment]
Hello,
I've been asked that feature a couple of time, as it's not a lot of trouble to implement I'll add it in the next update.
(May be a few days or weeks from today depending on my available time )

**Comment by argonlefou** [comment]
Added in v12.8 update
