### ISSUE TITLE
Request: Display Point Blank X "∞" Ammo count as 99

### ISSUE THREAD

**Issue by SeongGino** [argonlefou/DemulShooter#225]
Title, pretty much. Currently, ammo count only updates at all if a given microgame has an assigned limited bullet count. Allowing "∞" bullet counts to be displayed as 99 would probably make more sense (at least in OpenFIRE, we clamp any ammo counts 100 and above to 99 with our double digit ammo counter display anyways). Preferably, this should only be shown in the actual games themselves and ignored in the menus, but I'm not particularly picky about this.

If possible, it would be nice to have this be reflected in conditional (i.e. "shoot x without missing a single shot") games as well, where ammo remains at 99 until the fail condition is met; then, jump to 0 when input is blocked for the game.

I understand this might be extremely nitpicky and absolutely a low priority issue, so no hard feelings if this isn't planned. I just think it would help make the implementation feel a bit more polished for the all of five users who will have OLEDs showing ammo counts. :)

**Comment by argonlefou** [comment]
Ammo value is get by using an already existing function in the game code.
It returns the ammo value, based on some inner-filtering algorythm.

I think it would be possible to analyse the game's code (Unity is easy to display as C# code) and search for some data to know what kind of mini game you're currently playing to create a different ammo value than the one given by the existing function.
But honestly .... way too long and I can't afford to do it for that reason

Same thing goes for the conditionnal part of the request.... just a bit longer and harder than the first part XD

Doable, but I'll pass for this one, sorry !

**Comment by SeongGino** [comment]
Fair enough! Perhaps a thought experiment for someone more able to go through the trouble, but not that I expected much immediate resolution at the moment. :)
