### ISSUE TITLE
Any way to get rid of framework 2.0 3.0?

### ISSUE THREAD

**Issue by Trihy** [argonlefou/DemulShooter#226]
Hi. Wonder if this is possible. Tried to update target to framework 4.8. Compiled. Demulshooter, Demulshooter64 and gui seems to launch fine. But tríed just one game (hotd remake) and doesnt seem to hook up to the game.

**Comment by argonlefou** [comment]
Hi, 
DemulShooter hooking or not has nothing to do with a Framework error.

If you can compile it ans start it without .Net dependency error box, then you're fine

By the way, .net 2 and 3 are obviously included in newer frameworks, for backward compatibility.

**Comment by Trihy** [comment]
Windows 10/11 ask to install framework 2.0 3.0 package to run demulshooter.

The compiled for framework 4.8 doesn't ask for that. But for some reason doesn't connect to the game as the other do. Will keep trying.

Thanks.
.
