### ISSUE TITLE
Recoil question for Aliens Armageddon and Terminator Salvation.

### ISSUE THREAD

**Issue by Prime91122** [argonlefou/DemulShooter#227]
Big fan of your work Argon, thank you for all that you do!
I'm currently set up with Alien extermination guns. I have almost all shooter games working with DemulShooter and Mamehooker I get recoil and other Outputs working Ammo/Life/Damage, works great. My issue is on certain games like Aliens Armageddon and Terminator Salvation: for example both games on the first mission recoil starts great then sometimes you pick up a shotgun in the game and the recoil outputs 1 shot/ I recoil which is perfect. Then sometimes you pick up a big Mini gun in Terminator Salvation and the recoil goes away no output at all, I hold on the trigger to burnout the ammo hoping that when I go back to my regular machine gun the recoil would return but it doesn't  at all for the rest of the game. I check MameHooker and it closes at that exact moment every time for both games. The exact same happens with Aliens Armageddon on the first mission shooting with the turret guns on the vehicle recoil/output dies. Any resolution or advice is most appreciated.       Thank you in advance.

**Comment by argonlefou** [comment]
Hello

If you want to know better where your issue comes from, I'd play the games again with an empty .ini file for MameHooker (i.e no gun /lamp action for any output) and see if it crashes again

- If it does not crash, then the issue comes from the gun actions (maybe trigger at high speed (?)) and not from DemulShooter

- If MameHooker is still crashing, then it's caused by something it gets from DemulShooter, with high probability

**Comment by Prime91122** [comment]
Thank you for responding so quickly. With your help I found something. I cleared out the INI file and realized what the problem was. Since I'm using the Rear Counter to display the number of Ammo code =ghd 1 &H04B4 &H6870 3 &h03:&h0X:&h0X it only displays 1-9 Ammo counter and it cycles over and over. In Terminator Salvation your regular machine gun that you start the game with only has 60 ammo and the shotgun is is about 20 and display and recoil perfectly but as soon as you pick up the Minigun it's 200 ammo and the counter and the outputcode only has room for 2 digits only. So Mamehooker crashes.If that makes sense to you. Removing the ammo code resolves the recoil issue and Mamehooker doesn't crash. By any chance do you have any output codes for the AE guns? Or where I can find any? Thank you again for all that you do.

**Comment by argonlefou** [comment]
Nice job finding out the issue 👍 

Unfortunately I do not own those guns, and I don't have any info regarding the way they work
