### ISSUE TITLE
Please add Outputs for Target Terror Gold

### ISSUE THREAD

**Issue by bojo5150** [argonlefou/DemulShooter#229]
The game was recently fixed (no more random crashing and video/audio glitches have all been fixed.)

In game you acquire several weapons throughout the levels so gun outputs would be a massive improvement to the experience.

Thank you!

**Comment by nixxou** [comment]
+1, it would be nice to have recoil support for this game

**Comment by argonlefou** [comment]
Should be working in v12.8 update
