### ISSUE TITLE
Elevator Action Death Parade fullscreen solution

### ISSUE THREAD

**Issue by adamgp** [argonlefou/DemulShooter#23]
After following your docs and multiple experiments I believe the following may be a simple solution to running the game fullscreen with the correct aspect ration for you to consider fullscreen support.

- Rather than ticking Dx Window Mode, leave unticked. *
- (Direct3D9 Wrapper remains ticked)
- Install the 6 dgVoodoo files** into the root of the game filepath (adjacent to the main exe)
MS\x86\D3D8.dll
MS\x86\D3D9.dll
MS\x86\D3DImm.dll
MS\x86\DDraw.dll
dgVoodoo.conf
dgVoodooCpl.exe
- Run dgVoodooCpl.exe and simply set to "Stretched - maintain Aspect Ratio" (+ remove the water mark if preferred)

The game will now respect the resolution set by Jconfig and run in fullscreen. dgVoodoo will correctly readapt the output to fill the screen, in the (horizontal) middle, whilst maintaining the AR.

In my case, the default JConfig resolution of 720x1280 is smoothly downstretched to fit my 1920x1080 monitor - whereas running in windowed mode I get jagged graphics.

Is it now possible for DemulShooter to support correct mouse positioning when in fullscreen with maintained AR? Currently running in the aforementioned setup means vertical alignment is fine - but I have to run the mouse cursor right into the black regions of the screen to aim along the horizontal. Perhaps an additional optional command line parameter for --aspectadjusted?

Thanks

* Tested with JConfigEA.exe (1.8)
** Tested with "dgVoodoo2_63.zip" - Probably also don't need all 4 DLLs.
http://www.dege.freeweb.hu/dgVoodoo2/dgVoodoo2.html

**Comment by argonlefou** [comment]
Hi, and thanks for your setup. 
I'm using DgVoodoo a lot, but I've never been able to make it work as you said wit Elevator Action.

Using DgVoodo with JConfig configured like this:
[ ] High Resolution
[ ] Directsound Wrapper
[v] Direct3D9 Wrapper
[ ] Dx Window Mode  
Dx Hertz : 60
Dx Resolution Width: 720
Dx Resolution Height : 1280

Always results in a "ERRO DIRECT3D!" popup when I start the game, whatever settings I choose for DgVoodoo2

I'll try again on another computer tomorrow, but I kind of recall having the same issue too. 

Are those settings correct, compared to your experiments ?

**Comment by adamgp** [comment]
Hi, slightly different for myself:
I left the default High Res enabled, so I dont know if that has a part to play:

[v] High Resolution
[v] Directsound Wrapper
[v] Direct3D9 Wrapper
[ ] Dx Window Mode
Dx Hertz : 60
Dx Resolution Width: 720
Dx Resolution Height : 1280

Regarding your error, I believe I have only ever witnessed the "ERRO DIRECT3D!" error when using the original Game.exe and not the modified JConfig Game.exe that comes with it.

I do some more testing and try to recreate your error.

**Comment by argonlefou** [comment]
I tried with another version of JConfig (I may have had an older one initially)
I don't know if it's the same as yours, the game.exe CRC is **72504D88** (md5 hash = **1BC36915AC4A4658FEECA80CA1B6CA10** )

This indeed removes the "ERRO DIRECT3D!" dialogbox at start, but I still can't properly align Logos and some 2d graphics wth the 3D viewport at the center of the screen (although in-game HUD is Ok)

**Comment by adamgp** [comment]
I did some testing, here are my results:

**Test 1**
Jconfig only

[v] High Resolution
[v] Directsound Wrapper
[ ] Direct3D9 Wrapper
[ ] Dx Window Mode
Dx Hertz : 60
Dx Resolution Width: 720
Dx Resolution Height : 1280

![print1](https://user-images.githubusercontent.com/2965239/83455486-e20e8800-a455-11ea-8631-db81388dc421.png)

**Test 2**
Jconfig only

[v] High Resolution
[v] Directsound Wrapper
**[v]** Direct3D9 Wrapper
[ ] Dx Window Mode
Dx Hertz : 60
Dx Resolution Width: 720
Dx Resolution Height : 1280

![print2](https://user-images.githubusercontent.com/2965239/83455519-efc40d80-a455-11ea-93ca-ddb42f4ffc7d.png)

Note: works perfectly with DemulShooter and aims align as fills entire screen. 

**Test 3**
Jconfig and **deployed dgVoodoo**

[v] High Resolution
[v] Directsound Wrapper
[v] Direct3D9 Wrapper
[ ] Dx Window Mode
Dx Hertz : 60
Dx Resolution Width: 720
Dx Resolution Height : 1280

![final](https://user-images.githubusercontent.com/2965239/83455650-331e7c00-a456-11ea-8732-bbd370903e3e.png)

Note: whilst DemulShooter works, the aiming is offset along the x axis (only) the further you deviate from the centre. However, we could get around this by recalibrating the guns in the test menu - native support would be welcomed.

![jconfig](https://user-images.githubusercontent.com/2965239/83455865-87296080-a456-11ea-9295-65404e4d336e.png)

![dg](https://user-images.githubusercontent.com/2965239/83455879-8b557e00-a456-11ea-890d-d744167d2d06.png)

Only change from default was Scaling mode: Stretched, keep Aspect Ratio.


I hope that helps?

**Comment by argonlefou** [comment]
I can confirm - now that I can test your setup on my 1080p compliant screen - that this is working great !
So thanks again for founding this fullscreen solution, this will be added in the Wiki along with the windowed solution. As it may highly depend on the monitor resolution, I'll keep the windowed mode explained too.

Now, as for direct support without In Game calibration :  
1 - As the game has a working calibration procedure, the "Wiki" way, for anyone, will be to run a calibration (just as it is needed for a lot of games, like Demul or Model2) because it's really usefull with some devices (I'm thinking of analog  Arcade gun not having full range in motion due to hardware/potentiometers beeing old)

2 - Now, off the grid, I've added recently an option similar to your idea, for personnal use. So it's undocumented for now and I'm not sure it will be one day. It's called _**forcexratio=**_ and support decimal values (1.33) or fractional values (4/3, 16/9)
I've added this because of intensive use of DgVoodoo with games I couldn't force real 4/3 resolution, so strecthing them back to 4/3 from 16/9 creates an offset
Not all games can use that, but I've added EADP in the last release (https://github.com/argonlefou/DemulShooter/releases/tag/v10.1.3) and the correct command is _**-forcexration=9/16**_

Please note that option #2 can be disturbing for anyone not understanding the idea and the purpose, that's why option #1 is officially the way to go

**Comment by adamgp** [comment]
Thanks for your response, that is fantastic news! And thank you for making me aware of the -forcexratio parameter, I will experiment with this tonight and report back.

Out of interest, what other games do you apply dgVoodoo, force the AR, and use the forcexratio command to adjust accordingly? (Or what games/emulators? are supported by this command - is this documented anywhere?)

Off subject; I would just like to relay my personal appreciation for your work, supporting these games, and entertaining not just mine - but all enthusiasts suggestions and comments to allow us to play these gun games with absolute ease and in a wide array of configuration. DemulShooter is a core feature of my cabinet and works flawlessly. So thank you again.

**Comment by argonlefou** [comment]
No documentation for this command, as I said it's based on personal needs and I'm pretty sure making it public will cause more trouble than good.

Here's (from memory, I hope I don't forget any) why I'm using it :  
- Silent Hill arcade : 
Resolution patched to 1920x1080, stretched back to 4/3 display with ReShade.
forcexratio=4/3

- Haunted Museum :  
Need original resolution in the .INI file to properly align 2d/3d graphics, and my screen is streching it over the full 1080p display. Same usage than Silent Hill

- Aliens Extermination :  
Whatever the resolution is, my screen is - again - stretching it to the full display.
So again, stretched back with ReShade, and forcexratio=4/3

- Vcop3:
CxBx exclusive fullscreen mode is stretching the video to the full diplay. Here again stretched back to 4/3

- Hod2pc / hod3pc
Using DgVoodoo to enhance graphics + Reshade for a few others things.
There again my screen is streching the video to full display, stretched back to 4/3 for hotd2 and 4/3 or 1.20 for hotd3

Other games have this screen issue but usually the in-game calibration procedure is there to correct the aim

**Comment by adamgp** [comment]
Hi, confirmed works perfectly - please consider this issue closed thank you.

Also the trick worked great for Cxbx and vcop3. I did note however my 2nd and 3rd tests with vcop failed to apply to forcexratio adjustment. But I find Cxbx and DS can be quite temperamental anyway, sometimes (rarely) DS fails to hook Vcop entirely, rebooting the game solves this.
