### ISSUE TITLE
Change rom name for jurassic park in Rawthrills page of the wiki

### ISSUE THREAD

**Issue by ProfgLX** [argonlefou/DemulShooter#231]
Just need to make the change you did in the Raw Thrills page, Output page is already ok.

https://github.com/argonlefou/DemulShooter/wiki/Raw-Thrill#Jurassic

this:
DemulShooter.exe -target=rawthrill -rom=jpark

should be this:
DemulShooter.exe -target=rawthrill -rom=jp

Thanks Argon

**Comment by argonlefou** [comment]
Done !

Thanks
