### ISSUE TITLE
LRA - Next Gen Lightguns 

### ISSUE THREAD

**Issue by Bazzy-DE** [argonlefou/DemulShooter#232]
Hi, I don’t know how to write you. 
I want to thank you for your work!
Without we wouldn’t have such an awesome lightgun experience🥰 
I want to ask if you are up for HD haptic feedback support for Gun4IR (Sinden and other too)?
That kind of PS5 controller LRAs are? (linear resonance vibration actuators). Many controllers these days are using them. They are way better than annoying solenoids or slow rumble motors in my opinion. It’s hard to hold such heavy mods for hours too.
More realistic gun sound, feedback plus damage would be crazy🤗 
AHKs are needed anyway and editing/loading sound profiles could be easy.
Is this nearly possible? What do you think? 
I have a working wiring diagram for Arduino plus script. Only how to handle sound frequencies and a direct connection would be needed. 
Later it could be possible to connect (in addition with amplifier to split more audio channels) with Woojer Strap or bhaptic X40 for body hits. Or bass shaker in general too. 
Should I contact somebody else or is MameHooker capable to convert DemulShooter outputs in specific low frequency sounds?
Greetings Bazzy

**Comment by argonlefou** [comment]
> Hi, I don’t know how to write you.
I see you're mentionning Gun4Ir in your text, so the easiest way to have some technical chat would be on Discord. You'll find me on Gun4IR discord

 > I want to ask if you are up for HD haptic feedback support for Gun4IR (Sinden and other too)? That kind of PS5 controller LRAs are? (linear resonance vibration actuators). Many controllers these days are using them. They are way better than annoying solenoids or slow rumble motors in my opinion. It’s hard to hold such heavy mods for hours too. More realistic gun sound, feedback plus damage would be crazy🤗 AHKs are needed anyway and editing/loading sound profiles could be easy. Is this nearly possible? What do you think? I have a working wiring diagram for Arduino plus script. Only how to handle sound frequencies and a direct connection would be needed. Later it could be possible to connect (in addition with amplifier to split more audio channels) with Woojer Strap or bhaptic X40 for body hits. Or bass shaker in general too. Should I contact somebody else or is MameHooker capable to convert DemulShooter outputs in specific low frequency sounds? Greetings Bazzy

I wasn't aware these haptics parts were so cheap and already available everywhere.
But, even if I like these electronics projects, I don't see really much how DemulShooter would help in that: It's just outputing a pulse to trigger the signal

Signal handling on the hardware side (powering a recoil, a motor, haptic sensor or a led) is done by other systems (gun4ir firmware, mamehooker, serial commands, etc...)

**Comment by Bazzy-DE** [comment]
Yes, I prefer Gun4IR, but I think other lightgun users want LRAs too. Especially for upgrading non recoil models like Sinden. 
It should be easy to add this kind of small speakers plus a headphone jack. And they are cheap (~4 USD for a used PS5 one)
For me (and other too) lightweight, 
balanced handling, LRAs and fast triggers are desired for accuracy and high score gaming. 
The LRA has to be managed by software for wide range application like these body straps/vests and the capability to load gun sound dictionaries by starting a game. (Btw bHaptics X40 for VR can simulate shoots, explosions, sword hits and drinking heal potions)
The only question is will there be a delay if solenoid is activated too. And how to translate DemulShooter outputs in different gunshots and body damage. That’s out of my business. 
Maybe the Gun4IR can handle LRAs one day. But updates take a long time and the ESP is over the limit to hold one more SD card. A stand-alone version is better I think.
I hope Mamehooker is the way to go with a small Arduino and amplifier for more power if needed in the future. Ok, I will publish everything on discord. Cya

**Comment by argonlefou** [comment]
> Yes, I prefer Gun4IR, but I think other lightgun users want LRAs too. Especially for upgrading non recoil models like Sinden. It should be easy to add this kind of small speakers plus a headphone jack. And they are cheap (~4 USD for a used PS5 one) 

Having only experienced  the usual smartphone / PS5 haptic systems, I'd be curious to test what effect could be created in a lightgun to simulate the recoil power, and how different it would be from a regular motor

> For me (and other too) lightweight, balanced handling, LRAs and fast triggers are desired for accuracy and high score gaming.

True, but what you gain in weight and precision is lost in movements and "spectacle" (seeing the gun recoil moving).
But the more solutions, the better for the end user with larger choices

>  The LRA has to be managed by software for wide range application like these body straps/vests and the capability to load gun sound dictionaries by starting a game. (Btw bHaptics X40 for VR can simulate shoots, explosions, sword hits and drinking heal potions) The only question is will there be a delay if solenoid is activated too. And how to translate DemulShooter outputs in different gunshots and body damage. That’s out of my business.

I don't really understand the link between the jacket haptic when a palyer is beeing hit and a recoil delay when a player is shooting ?

As for translating outputs to different gunshots : 
- Can be done as you said per game by loading stringer/longer bullet effect according to the type of weapon used
- Is already (almost always) in synch with fired bullets in game, whatever the speed is, thanks to demulshooter

But separating different body parts for damage is not possible : there's almost no way for any game I added support to, to know where a player is hit.
It's just.....well, hit. Less life. That's all

>  I hope Mamehooker is the way to go with a small Arduino and amplifier for more power if needed in the future. Ok, I will publish everything on discord. Cya

MameHooker can send COM messages, so you just need an arduino (or equivalent) and your own COM protocol to send messages based on recoil/damage events

Or - if you go that way - you can make your own tools to replace MameHooker by reading DemulSHooter outputs on a TCP socket
