### ISSUE TITLE
I hope to play games with a mouse and a light gun? Can it be achieved?

### ISSUE THREAD

**Issue by fsxiyu** [argonlefou/DemulShooter#238]
I only have one light gun, but I hope to play in pairs (one light gun and one mouse). I've been tinkering for a long time, but I still can't achieve it.

**Comment by argonlefou** [comment]
Short answer is no.

As for more details :
- Lightgun raw absolute data is read directly by DemulShooter and transposed to the game screen/coordinates

- This can't be done with a mouse, as the device only sends relative movement (no absolute position)

- So to bypass that issue, DemulShooter can be used with a mouse thanks to the `-usesinglemouse` options: In that case DemulShooter is using the Windows mouse cursor position.
Unfortunatelly Windows does not know how to separate pointing devices, so every pointing devices (mouse or lightgun) will be merged to move the mouse cursor and also move it.
