### ISSUE TITLE
Cross hairs for P1 and P2 are locked side by side of each other for all 3 games of Namco 357

### ISSUE THREAD

**Issue by Prime91122** [argonlefou/DemulShooter#239]
Thank you for all that you do.
Cross hairs for P1 and P2 are locked side by side with each other for all 3 games of Namco 357 Dark escape, Dead storm Pirates, and Sailor Zombie.  Using gun4ir/Demulshooter. I have already linked Demulshooter to each of the game files Patch. Still no change. Please help

**Comment by argonlefou** [comment]
Hello,

I do not provide help on the setup/configuration part of DemulShooter on this github part, which is reserved for bugs and requests.

Please follow carrefully what is explained in the [Wiki](https://github.com/argonlefou/DemulShooter/wiki/System-357)

You can then also seek help on Gun4IR discord chat, where a lot of people (including myself) will be glad to help you directly
