### ISSUE TITLE
Request: Ghost Squad Evolution on Teknoparrot

### ISSUE THREAD

**Issue by bro007-eng** [argonlefou/DemulShooter#240]
Hi amazing Argon - just wondering if you could now do an update on demulshooter to include Ghost Squad Evolution that is now fully working in Teknoparrot (and with sound) to support 1 and 2 player aiming and mamehooker/outputs.  Thanks so so much for all you do.

**Comment by argonlefou** [comment]
I'd like to (for outputs) but I never was able to start the game : It keeps crashing when the window is created (be it with elfloader 1 or 2)

There will be no input support anyway, ask TP for better aiming

**Comment by bro007-eng** [comment]
Lol will ask re: better aiming - a bunch of updates were recently pushed through, along with the shader fix files its pretty stable. Can attach those files if u need them.

**Comment by argonlefou** [comment]
I couldn't get my hands on those shaders, links are old dead so yeah, if it can make the game boot i'd be pleased :)

**Comment by bro007-eng** [comment]
Ok here is a pack that worked for me. The shader files (amd or nvidia) - the sound drive file (in case you get no sound) and the dump I have that has shaders applied. TP dropped some updates so aiming is fine if you do calibration within the service menu.  I"ll keep this link live for a few hours and drop it off - https://mega.nz/folder/9uEgVDDb#atdbsRpkUHkReDXlJG5Aew  Just let me know once you've got it/them.

**Comment by argonlefou** [comment]
Thanks, 
I got the files, I'll try later

**Comment by argonlefou** [comment]
Still same results, impossible to start the game

**Comment by bro007-eng** [comment]
Really odd heaps have it working. PCB and dongle set to USA?

**Comment by aac197** [comment]
There are 2 versions of the game listed in TP: GSEVO & GSEVOELF2 - Have you added the ELF2 (Subscription) version - I think the game files are the same.

**Comment by argonlefou** [comment]
Finally found a NVIDIA gpu computer to test it !
Added in v13.0 update

**Comment by bro007-eng** [comment]
awesome thanks argo appreciate it

**Comment by aac197** [comment]
Amazing - Thank you so much!
