### ISSUE TITLE
Friction not hooking with teknoparrot 

### ISSUE THREAD

**Issue by covachero** [argonlefou/DemulShooter#241]
Hi, even with latest version downloaded (v12.9) demulshooter stills not hooking.

from ahk:

Run, \Emulators\DemulShooter_v12.9\DemulShooter.exe -target=windows -rom=friction
Run, \Emulators\Teknoparrot\TeknoParrotUi.exe --profile=Friction.xml
![FrictionDSCapture](https://github.com/user-attachments/assets/b4d6a43c-75b2-4e82-91f9-0f85f3de5ba5)

Thank you

**Comment by argonlefou** [comment]
Please make sure you followed all the following steps, and share a debug file

https://github.com/argonlefou/DemulShooter/wiki/Debugging

**Comment by argonlefou** [comment]
Sorry I misread the title

You won't be able to hook Friction using Teknoparrot

Only the standalone version is compatible with DemulShooter
