### ISSUE TITLE
Flycast not hooking in either 2.2 or 2.3 with latest demulshooter 

### ISSUE THREAD

**Issue by bro007-eng** [argonlefou/DemulShooter#242]
Hi there . Followed coding wiki guide with ahk but whilst demulshooter recognised the code it stays red and won't hook. Is there something I'm missing or a flycast setting required. Game does fire up and checked rom version.

**Comment by argonlefou** [comment]
Please make sure to follow the following steps and provide a debug file

https://github.com/argonlefou/DemulShooter/wiki/Debugging

**Comment by bro007-eng** [comment]
Can close this thanks brother the debug file and steps actually troubleshooted it for me confirm 2.3 flycast works with 12.9 thanks for the guidance.
