### ISSUE TITLE
Some bugs in version 12.9

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#243]
12.9 The following problems are found: 1: If the Elevator Action Invasion is used together with mamehook, the game cannot be started by pressing the Start button. 2: House of the Dead: Scarlet Dawn There are no outputs using TeknoParrot. 3: Bug Buster's wiki is not updated, rom is still bbusters.

**Comment by Armstrongstreener123** [comment]
> 12.9 The following problems are found: 1: If the Elevator Action Invasion is used together with mamehook, the game cannot be started by pressing the Start button. 2: House of the Dead: Scarlet Dawn There are no outputs using TeknoParrot. 3: Bug Buster's wiki is not updated, rom is still bbusters.

I just tested and invasion start button no longer works with or without mame hooker and demulshooter so must be the latest teknoparrot thats at fault

**Comment by cmjdbb** [comment]
I used a translator. I may have misexpressed it. Elevator Action Invasion use a DemulShooter, not a teknoparrot

**Comment by cmjdbb** [comment]
Version 12.9, House of the Dead: Scarlet Dawn has no Outputs using TeknoParrot and MameHooker, but there will be Outputs using versions below 12.6.

**Comment by argonlefou** [comment]
> 12.9 The following problems are found: 1: If the Elevator Action Invasion is used together with mamehook, the game cannot be started by pressing the Start button. 

I have no issue starting the game and playing with Demulshooter
![ooo_EAI](https://github.com/user-attachments/assets/74bd2a86-4224-4352-818e-78ad962ac602)




>2: House of the Dead: Scarlet Dawn There are no outputs using TeknoParrot. 

I didn't use TP for this one recently, and trying now just give me a IO board error on start.
I was able to go to TEST menu though, and testing LAMP outputs showed that outputs are working fine
![ooo_HODSD](https://github.com/user-attachments/assets/bbad5fb6-b936-47f3-8778-bbfc8fedb55e)




>3: Bug Buster's wiki is not updated, rom is still bbusters.

Thanks, I corrected it
