### ISSUE TITLE
Had issue #114

### ISSUE THREAD

**Issue by Hedrocks** [argonlefou/DemulShooter#247]
Hi 
I had a very similar issue to #114 wild west shootout. I downloaded the unmodified "WWS_Unmodified Assembly-CSharp.dll" file and placed it into the folder. It's now made the game one player only. I'm very much a novice to .dll files and i'm not sure what to do to get 2 players working. I have demulshooter v12.11

**Comment by argonlefou** [comment]
Hi

You can start by following the wiki :
https://github.com/argonlefou/DemulShooter/wiki/Coastal#wild-west-shoutout

Then to share a debug file if you still have issue
https://github.com/argonlefou/DemulShooter/wiki/Debugging#step-2

**Comment by Hedrocks** [comment]
Hi argonlefou

Thanks for your help I have running good now
