### ISSUE TITLE
Drakons Realm Keepers fatal error in gc

### ISSUE THREAD

**Issue by Armstrongstreener123** [argonlefou/DemulShooter#248]
Since adding demulshooter the game will get "Fatal error in gc, collecting from unknown thread" after around 10 minutes gameplay

I done some testing, started again with a fresh dump and played the game right through 1 player no problem. 

Then added the demulshooter unity folder files and the same error again so must be a problem from there. Any help would be great. Thanks

**Comment by argonlefou** [comment]
hello,

I'm honestly doing it "blind", without knowinf if it has anything to do with what you noticed, but I made one changed to test.
If you want to try
[[ThreadTest]Drakon_BepInEx_IL2CPP_DemulShooter_Plugin.zip](https://github.com/user-attachments/files/16647352/ThreadTest.Drakon_BepInEx_IL2CPP_DemulShooter_Plugin.zip)

You just need to replace the dll file in /BepInEx/plugins/ folder

**Comment by Armstrongstreener123** [comment]
> hello,
> 
> I'm honestly doing it "blind", without knowinf if it has anything to do with what you noticed, but I made one change to test. If you want to try [[ThreadTest]Drakon_BepInEx_IL2CPP_DemulShooter_Plugin.zip](https://github.com/user-attachments/files/16647352/ThreadTest.Drakon_BepInEx_IL2CPP_DemulShooter_Plugin.zip)
> 
> You just need to replace the dll file in /BepInEx/plugins/ folder

Thank you for this, its now fixed! Keep up the great work you do :)

**Comment by argonlefou** [comment]
The updated plugin will be packed in the next release for everyone

Thank you for your feedback
