### ISSUE TITLE
Add support for Guncon 3

### ISSUE THREAD

**Issue by Jonathan7299** [argonlefou/DemulShooter#253]
Can you add compatibility to play lightgun games with the Namco Guncon 3 lightgun (and also add the option to calibrate it too) please?

**Comment by argonlefou** [comment]
DemulShooter is not a driver, it's a software that can only read hardware once it's properly installed on windows

I don't know if any working Windows driver exist to make have a GunCon3 recognized by windows, but _**if**_ such a thing exist, you will have no trouble finding it in the supported device list once it's recognized and exported as a joypad or a mouse by Windows
