### ISSUE TITLE
Request. Akuma - Mortis Immortal when using jconfig

### ISSUE THREAD

**Issue by Armstrongstreener123** [argonlefou/DemulShooter#254]
Hi, any chance of taking a look at akuma when using jconig please. Shots are stuck in the centre of the screen. Thanks

**Comment by argonlefou** [comment]
Hi,
As far as I remember, Akuma is running perfectly without using JConfig.

So - and it's usually the case for similar cases - I don't think I'll add support for multiple launcher when they are not needed to run the game.

**Comment by Armstrongstreener123** [comment]
On windows 11 it doesnt run without jconfig for me anyway. On windows 10 without jconfig it runs in fast motion, most people have this issue

**Comment by argonlefou** [comment]
I can't speak for win11, I do not plan to install it at all.

As for the game speed, you should be able to limit the fps of the game thanks to Nvidia control panel or AMD equivalent

Jconfig has embedded d3d hook but you can get the same results with dgvoodoo or dxwnd or any similar d3d/rendering tool
