### ISSUE TITLE
House of the dead remake 2P Issue

### ISSUE THREAD

**Issue by Cavatapp98** [argonlefou/DemulShooter#257]
[Debug_2024-09-20_15-24-23.txt](https://github.com/user-attachments/files/17075918/Debug_2024-09-20_15-24-23.txt)
Hi,
I'm here to ask some Help because when i play with 2 gun i can activate the second Player in the game but the 2 light guns are recognise only with player 1 when they shoot.

thanks for all of your work

**Comment by Cavatapp98** [comment]
Hi,
I'm using the GOG game version and I used the Arcade mod plugin with DEMULSHOOTER but it doesen't work.
If there are any other information that you need to fix this problem say something to me 

Thank for all

**Comment by argonlefou** [comment]
There is no problem to fix unfortunatelly. The mod has been working without issues for months/years and I just re-tested with the latest version.

So it has to be a configuration issue on your side: either a faulty plugin install/configuration (you did not answer : did you follow all the steps to properly configure the plugin for multiplayer ? ) or with DemulShooter

To help you find out, here's an easy test to know if you set up the plugin as it should :
- Run the game, don't run DemulShooter. You should just be able to add credits and press start. Guns crosshairs and shoot/reload will not be possible at all with your mouse 

If you can shoot/reload without demulshooter, then you have nit configured the plugin correctly
