### ISSUE TITLE
Deadstorm Pirates Special edition demulshooter Error

### ISSUE THREAD

**Issue by Dark14543** [argonlefou/DemulShooter#258]
![image](https://github.com/user-attachments/assets/1efc6968-c603-4a84-bd95-71d6f6f5ed99)
![image](https://github.com/user-attachments/assets/7e95a2c8-1edb-4d80-b92b-da9260fd26ca)

When I want to install a demulshooter in the Deadstorm Pirates special edition game, I get this error. I entered and exited the game several times, but it still doesn't work. Also, it wants rpcs3.gun.exe.

**Comment by argonlefou** [comment]
What is the rpcs3 version you're trying to use ?

**Comment by Dark14543** [comment]
> What is the rpcs3 version you're trying to use ?

![image](https://github.com/user-attachments/assets/3dce6d01-1228-4e45-aee3-c251dbd664a3)

**Comment by argonlefou** [comment]
As stated in the [System 357 wiki page](https://github.com/argonlefou/DemulShooter/wiki/System-357) , only the specific arcade rpcs3-gun.exe release build is supported 

Using any other build will result in DemulShooter hack not working
