### ISSUE TITLE
Let's Go Jungle Rev. A Outputs

### ISSUE THREAD

**Issue by carolis15** [argonlefou/DemulShooter#259]
Would it be possible to add outputs to Let's Go Jungle Rev. A? It seems that it is not compatible with the first version.

**Comment by argonlefou** [comment]
I'm not a pro when it comes to arcade version of games, and I was not following very close the hype when those games where initially added,  so it might sound stupid but I don't even know different versions of LGJ where out.

I remember both `Rev. A` and `Rev. C` version beeing worked in DemulShooter for House of the Dead 4
But as far as LGJ is concerned I just know I have 2 different separate targets for LGJ and LGJ:Special

I'll take any info on that (please do not post any copyrighted material here)

**Comment by Armstrongstreener123** [comment]
> I'm not a pro when it comes to arcade version of games, and I was not following very close the hype when those games where initially added, so it might sound stupid but I didn't even know different versions of LGJ were out.
> 
> I remember both `Rev. A` and `Rev. C` version beeing worked in DemulShooter for House of the Dead 4 But as far as LGJ is concerned I just know I have 2 different separate targets for LGJ and LGJ:Special
> 
> I'll take any info on that (please do not post any copyrighted material here)

RevA is the new dump you must use with the latest teknoparrot. The old dump will no longer work. Of you need this dump fire me a message ill send you a link 🙂

**Comment by argonlefou** [comment]
Thanks for the tips

I was not able to start that new version with latest Teknoparrot (game is crashing) so it would be nice if you could test this update on your system in order to know if the changes are working (or not) :

[DemulShooter_v13.2_beta_test.zip](https://github.com/user-attachments/files/17362087/DemulShooter_v13.2_beta_test.zip)

Command is unchanged:
`DemulShooter.exe -target=lindbergh -rom=lgj`

**Comment by Ginsonic66** [comment]
Thanks Argon, you're not only the greatest, but the fastest too :-)!

I just did a quick test: LampStart output work, Damage and Life do not change yet (all stay at zero).
Since I tested remotely, I can not tell, if Recoil works, can test this in the evening.

**Comment by Armstrongstreener123** [comment]
> Thanks for the tips
> 
> I was not able to start that new version with latest Teknoparrot (game is crashing) so it would be nice if you could test this update on your system in order to know if the changes are working (or not) :
> 
> [DemulShooter_v13.2_beta_test.zip](https://github.com/user-attachments/files/17362087/DemulShooter_v13.2_beta_test.zip)
> 
> Command is unchanged: `DemulShooter.exe -target=lindbergh -rom=lgj`

Thank you, just done a quick test. It hooks but recoil and damage dont work, it also stops you being able to shoot enemys for some reason lol

**Comment by argonlefou** [comment]
As stated in the [Lindbergh wiki page](https://github.com/argonlefou/DemulShooter/wiki/Lindbergh), it's better to use the `-noinput` switch to get Outputs only without messing with TP inputs. Especially with versions I can't test myself (for now)

would anyone be able to get a [Debug file](https://github.com/argonlefou/DemulShooter/wiki/Debugging#step-3) so that I can try to see if there's something going wrong for damage/recoil ?

I hope to be able to run the game on another computer tonight.....but untill then I'm in the dark

**Comment by Armstrongstreener123** [comment]
> As stated in the [Lindbergh wiki page](https://github.com/argonlefou/DemulShooter/wiki/Lindbergh), it's better to use the `-noinput` switch to get Outputs only without messing with TP inputs. Especially with versions I can't test myself (for now)
> 
> would anyone be able to get a [Debug file](https://github.com/argonlefou/DemulShooter/wiki/Debugging#step-3) so that I can try to see if there's something going wrong for damage/recoil ?
> 
> I hope to be able to run the game on another computer tonight.....but untill then I'm in the dark

Hi, this is with using the -noinput. Ill try the debug file when im back home. Thanks

**Comment by argonlefou** [comment]
Should be better with this :
[DemulShooter_v13.2_beta_testv2.zip](https://github.com/user-attachments/files/17368474/DemulShooter_v13.2_beta_testv2.zip)

If you can confirm it working, I can update the public build

**Comment by Armstrongstreener123** [comment]
> Should be better with this : [DemulShooter_v13.2_beta_testv2.zip](https://github.com/user-attachments/files/17368474/DemulShooter_v13.2_beta_testv2.zip)
> 
> If you can confirm it working, I can update the public build

Can confirm this is working 🙂 thank you

**Comment by argonlefou** [comment]
Added in v13.02 update
