### ISSUE TITLE
Enhancement: Time Crisis 5 support

### ISSUE THREAD

**Issue by thatman84** [argonlefou/DemulShooter#26]
As im sure your aware TC5 has been released, currently working with mouse and Xbox controllers but Aimtrak is not compatible.

Aimtrak mouse tracking is fine on selection menu but in-game it goes haywire.

Emu-line forum has details if needed.

Fingers crossed you get around to adding this game. :+1:

**Comment by kim-sama** [comment]
And support for Lost Land Adventure

**Comment by argonlefou** [comment]
done !
