### ISSUE TITLE
Rabbids Hollywood Arcade Black Screen

### ISSUE THREAD

**Issue by adamtaylor6** [argonlefou/DemulShooter#261]
[Debug_2024-10-23_07-30-00.txt](https://github.com/user-attachments/files/17483173/Debug_2024-10-23_07-30-00.txt)
[LogOutput.log](https://github.com/user-attachments/files/17483174/LogOutput.log)

Thanks for developing such a useful tool. I'm trying to get Rabbids Hollywood Arcade to launch and use Sinden Light guns but it goes to a black screen. Log files are attached. I suspect USB port conflict issue, but I have tried removing all USB devices including mouse and keyboard, uninstalling from device manager, rebooting and VNCíng in and it still won't launch. Demulshooter seems to hook correctly and I can see/use the guns in DSDiag. Demulshooter output seems normal (coordinate issues are because guns were pointing at floor, but the Rabbids log output seems to loop on the following output. All help greatfully received!

[Debug  :RHA DemulShooter Plugin] DemulSHooter_Plugin.Update() => PlayerList.Length =  : 4

**Comment by argonlefou** [comment]
Based on DemulShooter log, I can just say that you're using a known binary/dll couple so it's not the issue.
DemulShooter itself is not needed to boot the game, it just controls Input/Outputs once the game is running.

For the plugin part, the loop log is somewhat normal, as there's nothing more than this line to print on screen, and the function is called at each Frame.
At least, it also means that the process/plugin is running and not bricked/killed

As for COM issue, the LogOutput.log show a couple of COM port tests but they all were denied access and it doent look like the game is still trying to open them in a loop as the log goes on after that.

There are a couple of 'savefile' issue at the end of the game startup ( starting at line n° 1350 of your LogOutput.log) 
You can try to remove the %appdata% folder content ( in : `C:/Users/[MyUserName]/AppData/LocalLow/Sarbakan/RabbidsShooter` )

Also, more important is an error just after (line 1354) : 
`[Error  : Unity Log] Failed to load 'C:/Rabbids Hollywood Arcade/Game_Data/Plugins/sxCore.dll' with error 'The specified module could not be found.
'.`

I tried with a fresh downloaded Dump of the game, applied DS plugin and all was running as intented.
Then, removing the `sxCore.dll` file resulted in a black screen at start.....
