### ISSUE TITLE
openfire The light gun can recognize the device, but any button is in a disabled state

### ISSUE THREAD

**Issue by starmisszhang** [argonlefou/DemulShooter#263]
Normal recognition of the light gun, but all buttons fail. Choosing a regular mouse can recognize it normally. Is this an incompatible issue?
![screenshot-1731599399800](https://github.com/user-attachments/assets/7698cf0f-bb9d-40a1-ac88-d9925d18ac05)

**Comment by argonlefou** [comment]
The picture is showing a device working in a Joystick mode (where you can choose from different axis)

I don't know how OpenFire is working, but on other guns (Aimtraks, etc...) the device can appear more than once in the device list (one for mouse, one for joystick, etc...) so you need to choose the correct one to have axis/buttons working when using the gun as a mouse
