### ISSUE TITLE
Friction Arcade Trigger Fix

### ISSUE THREAD

**Issue by IronMaiden2k** [argonlefou/DemulShooter#267]
Hi, my name is Mark and I've been encountering a problem with Friction Arcade for Teknoparrot. I have two Sinden Lightguns, they're both configured to the interface. As I play each gun individually, ie: solo.. each gun works fine in solo mode, the moment I try to play 2 player, the trigger button on one of the guns stops working immediately, depending on which gun started the game first. In other words, either player one gun or two, the trigger stops working.

**Comment by IronMaiden2k** [comment]
Argonlefou, is there a Demullshooter for House of the Dead Overkill PC version? I have two Sinden Light guns and they both seem to share trigger, reload and grenade buttons. I’d like to have a decent two player game instead of both guns sharing the same buttons. -MarkSent from my iPhoneOn Dec 10, 2024, at 7:29 AM, argonlefou ***@***.***> wrote:﻿
Hi,
DemulShooter support (for inputs) is only with the standalone version of the game and it's modified DLL (https://github.com/argonlefou/DemulShooter/wiki/Windows-games#friction)
You won't be able to use DS with Teknoparrot (and you shouldn't need it)

**Comment by argonlefou** [comment]
> Argonlefou, is there a Demullshooter for House of the Dead Overkill PC version? I have two Sinden Light guns and they both seem to share trigger, reload and grenade buttons. I’d like to have a decent two player game instead of both guns sharing the same buttons. -M

As far as I know the only available version of Hod Overkill is the one embedded in The Typing Of The Dead Overkill game from Steam

That version does not offer local coop gameplay (only network gameplay), so there's no DemulShooter support possible at all
