### ISSUE TITLE
Hi brother, can you add input and output to the new light gun game Skylanders?

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#268]
Hi brother, can you add input and output to the new light gun game Skylanders?

**Comment by argonlefou** [comment]
Hi

Skylander - cloud patrol (if it is that game you're talking about) is not a lightgun game, but a touch-and-swipe game.

This is not something to play with a Lightgun, it's more a smartphone/tablet/mouse game
