### ISSUE TITLE
Cxbx and Virtua Cop 3 aim issue

### ISSUE THREAD

**Issue by bromlecornu** [argonlefou/DemulShooter#271]
Hi,

I try to play Virtua Cop 3 with sinden, it works for P1 but P2 aim doesn't follow gun moves

Demulshooter launch great and green icon.

My ahk script

`#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

#SingleInstance Force

Run, E:\LaunchBox\DemulShooter\DemulShooter.exe -target=chihiro -rom=vcop3, E:\LaunchBox\DemulShooter
sleep, 1000

Run, E:\LaunchBox\Emulateurs\CxbxReloaded-Release-VS2019\cxbxr-ldr.exe /load "E:\LaunchBox\Games\Rail Shooter\Virtual Cop 3\vc3.xbe"
sleep, 3000

Send !{Enter} ; send Alt+Enter to make it fullscreen

ESC::
Send !{f4} ; send ALT+F4 to close the emu when pressing ESC
Run,taskkill /im "DemulShooter.exe" /F
ExitApp ; Close this script
return`

Any idea ?

Thx

**Comment by argonlefou** [comment]
Hi,

Please have a look at all the 3 stepds [here](https://github.com/argonlefou/DemulShooter/wiki/Debugging)

**Comment by bromlecornu** [comment]
Thx, finally now it works

Strange!!!!
