### ISSUE TITLE
Tombe Raider - no gun

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#272]
hello on TB without TP my pistols are detected in green but I can't shoot and when I press the trigger it shows me cheat code options.
On TP I see the target but i can't shoot also.....

**Comment by argonlefou** [comment]
When running the game with TP, DemulShooter won't work for inputs.

When not using TP, you have to make sure that the dump is not modded/hacked for TP, and that DemulShooter plugin is properly installed

So if you have troubles in both scenarios, you should check your settings
