### ISSUE TITLE
Diving into dolphin hotd2/3 Wii aimtraks.HELP!!

### ISSUE THREAD

**Issue by teeceds** [argonlefou/DemulShooter#28]
Heya!

Can I get some clarification on step 5 of the instructions?

5. In the "Device List" dropdown list, search for your Player2 Lightgun (ex : DInput/0/ATRAK Device #2 for Aimtrak with ID=2) and note the exact name. Now close Dolphin, edit manually with a text editor the WiimoteNew.ini file on your computer and replace all occurence of "DInput/0/ATRAK Device #2" by your DeviceName (4 lines to modify : number 36,37,38,39) and go back to Dolphin

What is the "device name" I should be putting in for the aimtrak player 2? Is it the device ID I see in demulshooter? The long "pid_1602..............." Number?

Can you show me an example somehow? Like what the .ini should look like?

Sorry for any inconvenience

Thank you very much

**Comment by teeceds** [comment]
Played around with this all day today and I can't figure it out. If anyone can share their wiimotenew.ini with me that has set up 2 aimtraks that would be much appreciated. I'm starting to think it's demulshooter that's not working for the dolphin emulator at this point

Thanks

**Comment by argonlefou** [comment]
Hi,

First and foremost, if you're using a couple of Aimtrak you should be able to skip Step 5 (as specified, you should have a success message for step 2 and jumping to step 6 directly)

Anyway, if you really have to do Step 5, you'll have to change the default name in the ini file (which will be DInput/0/ATRAK Device #2) to the one you want. It can be DInput/0/ATRAK Device #3 or DInput/0/ATRAK Device #9 or whatever according to your Aimtrak configuration.
Again, if it's already DInput/0/ATRAK Device #2, you should not have to do step 5

Finaly, here are a few WiiMote configs (the one I'm using)
[Wiimote_configs.zip](https://github.com/argonlefou/DemulShooter/files/5407098/Wiimote_configs.zip)

**Comment by teeceds** [comment]
Thanks for the email mate. I'll give it a go over the weekend. You're a
legend!!

**Comment by thatman84** [comment]
@argonlefou is it possible to use your method for player 2 with a different device (sinden gun). I'm assuming not as sinden doesn't present in the device dropdown list in Dolphin

**Comment by argonlefou** [comment]
Indeed, as the sinden guns are not listed in the device list, there is no way to use this method with this kind of device.
As for now, the only working devices (as far as I now) areaimtraks.

By the way, I'm closing the ticket as original issue seems to be answered
