### ISSUE TITLE
Model 2 Scripts replacement issue

### ISSUE THREAD

**Issue by thatman84** [argonlefou/DemulShooter#29]
Hi argonlefou,
Excited to see you found the whiteflash removal scripts for model2 recently.
Is there are way to combine existing scripts rather than replace them?

The scripts are kind of complicated for myself to edit, currently my setup requires some specific scripting for displaying a Sinden lightgun border and theres also the fun additions of cheats, widescreen scripts and if egregiousguy releases his fun score counter mods for hotd (https://www.youtube.com/watch?v=MtFO8gJG0oM&list=PLnoINYMhyuGSMMTSJ_6svymGdnOfs96YT&index=10&t=83s) combining all the scripts together could get rather interesting!

Maybe there is no "easy" solution but some advise from a programmer would be a help.

**Comment by argonlefou** [comment]
Hi
There is indeed no easy solution to merge existing script. 
That would mean : open existing scripts, read and parse them and try to add/remove thing on the fly.....etc...

This is not the purpose of Demulshooter so you'll have to dive a little bit into LUA to be make your own "mix-them-all" script : save your original scripts, export DemulShooter's one and merge manually what is done on both side to make your own script.
