### ISSUE TITLE
not work using mouse with 1.93 Hotd4？

### ISSUE THREAD

**Issue by dorminirko** [argonlefou/DemulShooter#3]
I check all of your information，but if i running the game，game is work fine，and mouse crosschir is freedom，but shoot point is locked on screen left-up center，its cannot synchronize with mouse crosschir

**Comment by dorminirko** [comment]
or if you have a enough times，wish you can update your HOTD4_MouseFix software for TP v1.0.0.112 also make LGJ_MouseFix too thanks

**Comment by dorminirko** [comment]
I get error like this Error converting screen location to client location
-------------------- Program Start ----------------------
P1 device = \\?\HID#VID_093A&PID_2510#6&11ab0ac3&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
P1 Device Handle = 720953
P2 device = \\?\HID#VID_093A&PID_2510#6&11ab0ac3&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
P2 Device Handle = 720953
Cmdline arg 1 : -target=lindbergh
Cmdline arg 2 : -rom=hotd4
Cmdline arg 3 : -v
Waiting for Lindbergh hotd4 game to hook.....
Cannot read memory at address 0x0817FE50
Cannot read memory at address 0x00000000
PlayerData_Base_Address = 0x139D63E4
Attached to Process BudgieLoader.exe, ProcessHandle = 1276
BudgieLoader.exe = 0x009A0000
Memory Hack complete !
-
RawData event for Device #1:
Device rawinput data (Hex) = [ FFFFFFFE, 0000 ]
PrimaryScreen Size (Px) = [ 1680x1050 ]
OnScreen Cursor Position (Px) = [ 0, 0 ]
OnClient Cursor Position (Px) = [ -33, -55 ]
Game client window resolution (Px) = [ 1280x768 ]
Game Position (Hex) = [ 0000, 0000 ]
Game Position (Dec) = [ 0, 0 ]
MouseButton (Hex) = 0x0000
-
...
Error converting screen location to client location
BudgieLoader.exe closed

**Comment by argonlefou** [comment]
> I check all of your information，but if i running the game，game is work fine，and mouse crosschir is freedom，but shoot point is locked on screen left-up center，its cannot synchronize with mouse crosschir

> or if you have a enough times，wish you can update your HOTD4_MouseFix software for TP v1.0.0.112 also make LGJ_MouseFix too thanks

Latest build (8.5.5) is now compatible with Tp 1.0.0.112
The mouse fix is also done

**Important note :**
As for now, Tp will have a lot of updates and it seems that each one of them may break Lindbergh support with DemulShooter.
DemulShooter will not be updated every 2 days just for Tp, unless some progress is made and/or new games added (in lightgun category)
