### ISSUE TITLE
Crash when reloading P2 with Act labs Guns

### ISSUE THREAD

**Issue by hellsass** [argonlefou/DemulShooter#30]
Hi, thanks for your great work.
I use 2 Act labs guns on a CRT wells Gardner D9400. I have CRT emudrivers installed on a windows 10 uptodate. I have an issue with Demulshooter when reloading with Player 2 Act Labs Gun5message box error). With Dsdiag.exe I have the same message when I shoot outside the screen with the gun 2. No Problem when reloading with the P1 Gun. With the old versions of demulshooter, no problem at all (V8). I have no issues with my guns in mame. Let me know if you want me to make some tests. Thanks

[debug.txt](https://github.com/argonlefou/DemulShooter/files/5439133/debug.txt)

**Comment by argonlefou** [comment]
Hi,
This must be an issue with the new way to handle data, and the way CRT emudriver is outputing it.
Not easy to debug without the actual hardware device but we'll see....

The debug file and it's message error is a good start to now where it's bugging. I just need to find what.
First thing to help would be a screenshot of DsDiag for P1 gun and P2 gun

**Comment by hellsass** [comment]
Hi,
Thanks for your support. Here are the files. The gun buttons are turning green, no problem with that. The guns have 2 buttons each (A Trigger and a button to send right click). I don't know why four buttons appears for the gun1 with Dsdiag when only two are usable. The problem is with the gun2. When I shoot off the screen or if I use the second button the message box appear. Demullshooter is still running but I have to validate the message. If not, the two guns are not responding anymore. Thanks ;)
[Act Labs Issues.zip](https://github.com/argonlefou/DemulShooter/files/5483731/Act.Labs.Issues.zip)

**Comment by argonlefou** [comment]
Thanks for the files.
You said you were using 2 Act Labs gun, but they are not sharing the same VID and P1 lightgun is reffered as "GLOBAL VR PC USB Light Gun". So - at least - the inner parts (= electronics) are not the same.

What happen if you swap P1/P2 gun and try again ? It should now crash when shooting with P1 in theory ?

**Comment by hellsass** [comment]
Woow, sorry for the false trail. I thought that the problem came from player 2 but after some tests it seems to come from the hardware itself (therefore from the driver because even if I connect only one gun (the one with the problem) and I set it for player1 the problem persists). The VGA boxes that I use have identical shells but as you said, it must not be the same electronic model. And so there is one of the two models that is problematic. I imagine it is the older model because it only support 2 mouse buttons. The other VGA box model support 4 buttons even if the guns only have 2. It was perhaps planned for future multi-function pistols...
Thanks again for your support for my exotic hardware :)

**Comment by argonlefou** [comment]
So far this totally make sens based on the debug files.

The error itself does not, though ....if you can come back in a few days I'll post another reply with a new binary for you to test (with enhanced debug information. I can only do that because I have no access to the real hardware...you'll be my "eyes")

**Comment by hellsass** [comment]
Ok, thanks ;)
I'll be your "eyes" and you'll be my "brain". Between us, we will be a sort of frankenstein debugger lol

**Comment by argonlefou** [comment]
Hi,
I finally found the bug in the code, but I'll have some issue to correct it....
To be short, it's the fact that your Gun only has 2 buttons available, whereas all other one have a driver that may output at least 3 bttons (left, middle, right)

To be sure this is the real reason, I'd need you to open DsDiag, select your faulty gun in the list, and click the "export device data" button on the right.
And share the result here

Thanks !

**Comment by hellsass** [comment]
Thanks again for your support. Here's the export device data
[DsDiag_Report_2020-11-17_21-18-43.txt](https://github.com/argonlefou/DemulShooter/files/5556244/DsDiag_Report_2020-11-17_21-18-43.txt)

**Comment by argonlefou** [comment]
Thanks !
there is a few in in progress in DemulShooter right now and I can't publish a new release yet, but you can try this WIP version, this should resolve the crash issue 
[DemulShooter_wip.zip](https://github.com/argonlefou/DemulShooter/files/5579346/DemulShooter_wip.zip)

Just for information : in DsDiag in DemulShooter_GUI, you'll still see only 2 buttons for this gun and, RightButton/OutOfScreen beeing the 3rd, this will not display any blinking square for this action but this will perfectly work in-game

**Comment by hellsass** [comment]
Thank you so much for fixing this. All is perfect again, my 2 Guns ar working perfectly ;)
