### ISSUE TITLE
Transformes Human Aliance JVS I/O error 6401

### ISSUE THREAD

**Issue by amosico2018** [argonlefou/DemulShooter#31]
Hi There,
i Also Experienced this issue with JVS I/O Error 6401,
i noticed it's jump right on the startup video, if you press on 1P start button it skip the video and let you start the game,
but after the first level, it got stuck on this error message..

i'm using Alien Extermination USB Guns. 

Thanks !

**Comment by argonlefou** [comment]
Hi, 
You're a bit short on details....are you running Transformers with TeknoParrot ? (if yes, which version ?) or with Jconfig ?

DemulShooter is not handling JVS I/O protocol, it's the emulator job so I highly doubt I can be helpfull on this one, but I can give advice according to your answer
