### ISSUE TITLE
Question:- OpGhost middle mouse original button

### ISSUE THREAD

**Issue by thatman84** [argonlefou/DemulShooter#34]
Just wondering if the middle mouse (change weapon) is bound to a different original key or it is in fact middle mouse by default in operation ghost.

**Comment by argonlefou** [comment]
Initially, if you're setting _**EnableInputDevices=1**_ in the ini file to be able to play the game with a mouse without any JVS emulator, the controls are :
- Left Mouse : Shoot
- Right Mouse : Change Weapon
- Middle Mouse : Action
- Move the cursor to the border of the screen : Reload

The mapping for DemulShooter is slightly different to keep the "shoot offscreen to reload"  function like many other lightgun games.

On the other hand, if you're using Jconfig or TeknoParrot with JVS emulation for the game, the mouse won't work natively.
