### ISSUE TITLE
Buck Hunter support?

### ISSUE THREAD

**Issue by bdiederichs** [argonlefou/DemulShooter#37]
Buck Hunt Arcade PC is listed as a supported windows game  for DemulShooterX64, but I just can't get it to work.
The game is Buck Hunter Arcade - for windows (copyright 2016)
The executable is Buck.exe
The game acts the same with or with out DemulShooterX64 running.
DemulShooterX64.exe -target=windows -rom=bhap

**Comment by bdiederichs** [comment]
[debug.txt](https://github.com/argonlefou/DemulShooter/files/5922157/debug.txt)

**Comment by argonlefou** [comment]
Hi,
Buck Hunt is not supported, there is indeed an error in DemulShooterX64 help command, which should not list the game as supported.

This game has long been as WIP but never worked, and thus is not listed on the wiki
I'll remove the game from the display in the next update

**Comment by bdiederichs** [comment]
Thanks!
