### ISSUE TITLE
2nd player not working in Virtua Cop using Sinden lightguns

### ISSUE THREAD

**Issue by danhermle** [argonlefou/DemulShooter#38]
Tested: hotd and vcop2 and I have both working perfectly with two Sinden lightguns.  When I run vcop the second controller is not properly recognized.  The first lightgun works as expected but the second acts like a clone of player one that can't shoot.  Are there any logs or debug info I can provide?

Here is my command line:
DemulShooter.exe -target=model2 -rom=vcop

Using:
model2 1.1a
DemulShooter_v10.1.5
Windows 10

**Comment by argonlefou** [comment]
Hi,
You can add a -v option in DemulShooter command line and it will create a debug.txt file

**Comment by danhermle** [comment]
This was user-error.  You have to run two instances of the Sinden software to enable both guns and I had the same device selected in both which caused the weird behavior.  You have to make sure to click "save" once you change the device or it won't persist between launches of the software.
