### ISSUE TITLE
Virtua Cop 3 .net framework exception

### ISSUE THREAD

**Issue by luffytam** [argonlefou/DemulShooter#4]
i am using windows10 ver.1903
i was setup following DemulShooter wiki and run `DemulShooter.exe -target=chihiro -rom=vcop3`, 
 when I move mouse or click, an exception **Object reference is not set to an instance of an object** from .net framework appear:

**System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 DemulShooter.Game_CxbxVcop3.SendInput(MouseInfo mouse, Int32 Player)
   在 DemulShooter.WndParam.ProcessInput(MouseInfo mouse, Int32 player)
   在 DemulShooter.WndParam.ProcessRawInput(IntPtr hDevice)
   在 DemulShooter.WndParam.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)**

debug info:
23:09:51.197003 : -------------------- Program Start ----------------------
23:09:51.231922 : P1 device = \\?\HID#VID_1D57&PID_FFA4&MI_00&Col01#7&338cd673&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
23:09:51.307877 : P1 Device Handle = 65593
23:09:51.351950 : P2 device = 
23:09:51.407061 : P2 Device Handle = 0
23:09:51.475366 : P3 device = 
23:09:51.520393 : P3 Device Handle = 0
23:09:51.551402 : P4 device = 
23:09:51.596436 : P4 Device Handle = 0
23:09:51.651414 : Cmdline arg 1 : -target=chihiro
23:09:51.696592 : Cmdline arg 2 : -rom=vcop3
23:09:51.751558 : Cmdline arg 3 : -v
23:09:51.825515 : Waiting for Global VR vcop3 game to hook.....
23:10:03.342793 : Attached to Process Cxbx.exe, ProcessHandle = 1272
23:10:03.397761 : Cxbx.exe = 0x00010000
23:10:03.467722 : MainWindowHandle = 2755002
23:10:03.515694 : Testing process #0
23:10:03.556671 : Process ID = 7916
23:10:03.599646 : bTest = 0x89, 0x6E, 0x0C
23:10:03.655614 : b = 0x30, 0x9F, 0x07
23:10:03.699589 : Not the good one...
23:10:03.745563 : Testing process #1
23:10:03.788538 : Process ID = 2800
23:10:03.832513 : bTest = 0x89, 0x6E, 0x0C
23:10:03.877487 : b = 0x00, 0x00, 0x00
23:10:03.943449 : Not the good one...
23:10:03.988423 : RawData event for Device #1:
23:10:04.032398 : Device rawinput data (Hex) = [ 0001, 0003 ]
23:10:04.076374 : using alternative way of Screen size
23:10:04.121347 : PrimaryScreen Size (Px) = [ 1920x1080 ]
23:10:04.166322 : OnScreen Cursor Position (Px) = [ 0, 0 ]
23:10:04.210296 : OnClient Cursor Position (Px) = [ -640, -300 ]
23:10:04.255271 : Game client window resolution (Px) = [ 640x480 ]
23:10:04.298246 : Game client window location (Px) = [ 632 ; 249 ]
23:10:04.343221 : Game Position (Hex) = [ FFFFFEC0, 00F0 ]
23:10:04.387196 : Game Position (Dec) = [ -320, 240 ]
23:10:04.420177 : MouseButton (Hex) = 0x0000
23:10:04.476145 : -
23:10:04.548105 : RawData event for Device #1:
23:10:04.587081 : Device rawinput data (Hex) = [ 0001, 0003 ]
23:10:04.631056 : using alternative way of Screen size
23:10:04.676030 : PrimaryScreen Size (Px) = [ 1920x1080 ]
23:10:04.752986 : OnScreen Cursor Position (Px) = [ 0, 0 ]
23:10:04.841935 : OnClient Cursor Position (Px) = [ -640, -300 ]
23:10:04.886910 : Game client window resolution (Px) = [ 640x480 ]
23:10:04.930885 : Game client window location (Px) = [ 632 ; 249 ]
23:10:04.974859 : Game Position (Hex) = [ FFFFFEC0, 00F0 ]
23:10:05.019833 : Game Position (Dec) = [ -320, 240 ]
23:10:05.063808 : MouseButton (Hex) = 0x0000

**Comment by argonlefou** [comment]
Which Cxbx-Reloaded build are you using ?

**Comment by luffytam** [comment]
the Cxbx version i use is `9c4836f6`

**Comment by luffytam** [comment]
I fixed .net exception because i run everything as administrator
but here's another problem, the game cursor always in left top and cannot move with mouse but i can fire reload etc.

**Comment by futuration** [comment]
Yes, same problem here. The cursor is always frozen at the top-left.

**Comment by Catarax** [comment]
It's probably the mice not supported at all, the software seems only designed for PC light gun.

**Comment by argonlefou** [comment]
Issue continues [here](https://github.com/argonlefou/DemulShooter/issues/13)
