### ISSUE TITLE
Gundam: S.O.Z 2P Controls

### ISSUE THREAD

**Issue by bdiederichs** [argonlefou/DemulShooter#40]
Trying to play Gundam: S.O.Z 2-players
The game starts, and the debug looks like the game is recognized and hooking, but neither gun is working and the test menu shows no triggers being pressed for either player (no matter what buttons I try).

I'm using a pair of analog pedestal guns that each has three buttons.
I know your program doesn't 100% support them but I've been able to make them work in 99% of games and the problems I do have are usually just with calibration, not overall function.

In this game, the buttons have been re-mapped as P1 trigger is not responding to any mouse-clicks But the guns buttons do nothing in game

[
[debug.txt](https://github.com/argonlefou/DemulShooter/files/6192643/debug.txt)
](url)

**Comment by bdiederichs** [comment]
UPDATE!

I just tried this using an older version of DemulShooter and it works!
I'm not 100% sure how to check the version that this works with as it's just an older copy I kept after updating, but it's not *that* old as it still includes the DemulShooterGUI program

**Comment by bdiederichs** [comment]
working:
https://youtu.be/zlyJDcSzJgI

Not sure if there is a bug in the newer version or if this is just a known thing. I have noticed some other games that don't play well with the the newer DemulShooters
Example: Lupin II The Shooting crashes if I use anything newer than 8.7.0

**Comment by popo69200** [comment]
Gundam: S.O.Z 2P Controls can play 2 players on the same screen? confirm?

**Comment by bdiederichs** [comment]
Yeah, you can run the game in two player mode and it will split the screen allowing each player to have half the screen

**Comment by argonlefou** [comment]
> Gundam: S.O.Z 2P Controls can play 2 players on the same screen? confirm?

Yes, just follow the [Wiki](https://github.com/argonlefou/DemulShooter/wiki/Taito-Type-X#gundam--spirit-of-zeon) and make sure you're using the correct DemulShooter command corresponding to the correct exe file (1P or 2P).
There are 2 different exe and you have to use the one corresponding to your needs.
Unfortunatelly the source website quoted in the Wiki regarding the game's installation is dead for now, you'll have to find the files by yourself

> Yeah, you can run the game in two player mode and it will split the screen allowing each player to have half the screen
> 
> https://youtu.be/zlyJDcSzJgI

If by any chance you could confirm that the latest version of DemuShooter does work well for you, I may be able to  close this ticket ;-)

**Comment by ProfgLX** [comment]
Confirmed working on v10.9.6 @argonlefou.
