### ISSUE TITLE
[Feature Request] Adding a second input source

### ISSUE THREAD

**Issue by sm32x** [argonlefou/DemulShooter#44]
Hi argonlefou,

Thanks for the fantastic project. I was always using Aimtraks but once I got my Sindens in, I decided to built out a full cab for shooters. I took a look at the DS code (RawInputController) and it looks like this may not be easy to do, but with games that use pedals (TC5, Vcop3), it would be great if we could source the alt buttons (i.e. action, etc.) to another input like a keyboard. It would be harder to wire/solder pedals to the lightgun's inputs than to just plug them into an ipac and call it a day.

Any thoughts, even if it is not the most elegant solution?

**Comment by sm32x** [comment]
Actually it looks like it may be pretty easy to do (at least one-off) by overriding KeyboardHookCallback in both of those games' source files. But that wouldn't be an extensible method without a whole bunch of other changes for the project.

**Comment by argonlefou** [comment]
Hi,
I'm not sure to correctly understand the request, but sourcing buttons to keyboard is already an existing feature.
In DemulShooter_GUI, if your device is of lightgun type (Sinden, Aimtrak, Top gun....any mouse device) you just have to enable virtual buttons and set them to whatever keyboard key you want

**Comment by sm32x** [comment]
Hi argonlefou,

I have my pedals mapped to an ipac/keyboard. I modified the source code locally for DemulShooter's vcop3 file so that it handles the T and Y keys for bullet time for p1 and p2 by removing the handler from the rawinput portion of the code and moving it into your keyboard hook procedure. Since it is not extensible for others as written, I did not make a pull a request.

This config allows the pedals to work as intended in both vcop3 and time crisis, and also still keeps the middle button available in time crisis for weapon switching (and right button for reloading).

Have I misunderstood the feature you've described?

**Comment by argonlefou** [comment]
Again, what you're describing is already a part of the program : this feature is called "virtual mouse button" and is available for all mouse devices in DemulShooter_GUI : you can choose to enable them and select a keyboard key that will act just like the corresponding mouse button.

So you just need to open DemulShooter_GUI and activate virtual mouse buttons for both devices (P1 & P2).
Then set T keys for P1 middle button, and Y key for P2 middle button, this will act just like you want to for vcop3

And this will work for TC5 too as DemulShooter is only handling axis coordinates (no buttons hacking/handling)
