### ISSUE TITLE
Mayflash Dolphinbar modes

### ISSUE THREAD

**Issue by xchwarze** [argonlefou/DemulShooter#45]
first of all I wanted to tell you your software really is amazing!
what if it can not be clear in what way I have to put the dolphinbar to use it correctly 
in which modes does the dolphinbar work?
in the arcadecontrols forum there are users who speak of mode 2, others of 4. from what I saw the best would be 3 but it cannot read the cursor

**Comment by Smanar** [comment]
There is a mode with 2 dolphinbars and 2 wiimote (joypad emulation), and a mode for 1 dolphinbars + 2 wiimote (wiimote emulation)

**Comment by xchwarze** [comment]
I am seriously thinking of using some updated fork of the Touchmote and using a normal bar
https://github.com/SeongGino/Touchmote/releases/tag/1.0b15-ViGEm

**Comment by Smanar** [comment]
IDK, I m using the last official from 16 Feb 2018
