### ISSUE TITLE
demulshooter.exe disappears after launching game

### ISSUE THREAD

**Issue by 0uro** [argonlefou/DemulShooter#46]
Hello,

I'm using demulshooter to make it work with Sinden Lightgun and HOTD2 on Windows.

I configured everything and the program works for both guns, but.... After launching the game demulshooter.exe simply disappears !

I start it with a shortcut + game launcher (no anyhotkey)

Will try to get some error messages or logs
I have no clue, what should I do ?

**Comment by argonlefou** [comment]
To get a debug file, run Demulshooter with the "-v" option added in the command line and you'll get a debug.txt file in Demulshooter folder

**Comment by mooock** [comment]
> 

It might be misunderstanding of how the program works. when you start the program, it waits for a specific exe to be started, and will not launch anything by itself. it will be clear to see from the debug log. i am also using sinden. but expected something to happen when running the exe.

**Comment by argonlefou** [comment]
In this case (OP message : the demulshooter.exe closing after running the game), it usually means that the game crashed because of the memory hook (hod2 has many different exe and the wrong hook will crash the game by writing in a wrong part of the memory), and as the game process has closed so will demulshooter.

I don't think this was a "waiting for something to happen issue"
But not getting log of what happened, I can't confirm it

**Comment by mooock** [comment]
> In this case (OP message : the demulshooter.exe closing after running the game), it usually means that the game crashed because of the memory hook (hod2 has many different exe and the wrong hook will crash the game by writing in a wrong part of the memory), and as the game process has closed so will demulshooter.
> 
> I don't think this was a "waiting for something to happen issue" But not getting log of what happened, I can't confirm it

For me it was not knowing how to use the program correctly, but using the debug it was clear what i needed to do, and can confirm it works on Windows 11 + Sinden Lightgun.

I also tested it with Legacy Terminal, and powershell 7 command line.

**Comment by argonlefou** [comment]
> Hello I have the same pb with 2 games. For one the last update is ok...for the other Museum2....I change the name of the rom in my commande...and it work fine : fearland and not museum2....

Hello,

I'm not sure to understand the problem you have, as there are 2 different issues mentioned in this topic.

Do you have DemulShooter disapearing after you run it ? (Meaning : no red or green icon in the notify icon menu next to window clock) ? If so, is the game closing itself too ?

I can only assume this is the case for hmuseum : it's the "same" game than fearland but with different .exe file (not published by the same editor) and applying the wrong hack (by not selecting the corresponding target between fearland and hmuseum2) will cause the game to crash and demulshooter closing itself

**Comment by popo69200** [comment]
Yes. When i start the game demulshooter stop...

**Comment by argonlefou** [comment]
Then run demulshooter with the "-v" option added in the command line, this will create a text debug file in demulshooter's folder that you can share

If demulshooter is really crashing when trying to hook the game, this should be written somewhere inside

**Comment by argonlefou** [comment]
continues on #78
