### ISSUE TITLE
HOTD3 crashes with demulshooter

### ISSUE THREAD

**Issue by jfree427** [argonlefou/DemulShooter#48]
HOTD3 (pc) starts up fine with demulshooter in the background.  However, once I hit "survival mode" from the menu, it immediately crashes.  The game does not crash when demulshooter is not running in the background.

**Comment by argonlefou** [comment]
could you test this version with your game and tell me if it's working better ?
[DemulShooter_test.zip](https://github.com/argonlefou/DemulShooter/files/7504450/DemulShooter_test.zip)

**Comment by jfree427** [comment]
It works! You rock!!!

**Comment by argonlefou** [comment]
Thanks, I will add this to the next release
