### ISSUE TITLE
PCSX2/Supermodel (SEGA Model 3) support

### ISSUE THREAD

**Issue by RavenMacDaddy** [argonlefou/DemulShooter#50]
I saw your post on the forums for Aimtrak on PCSX2.

Personally I'm trying to use wiimotes.

Are there plans to support these emulators, or is there an easier way to do this even without DemulShooter - specifically multiple wiimotes/players?

Especially since PCSX2 is moving away from plugins making Nuvee unusable.

**Comment by RavenMacDaddy** [comment]
Thinking about it, Flycast would also be of interest since it's an active and stable emulator supporting Naomi, atomiswave and dreamcast.

**Comment by argonlefou** [comment]
For Supermodel (model 3) : This emulator has already been supporting RawInput natively for a long time

For PCSX2 : No plan to support.
1) This is a console emulator, not an arcade emulator and this causes a lot of issues (regarding the need for too many controls for simple lightgun usées, mostly)
2) The emulator is under active development, so it  would be better to focus on them making lightgun support directly

For Flycast: 
Last time I checked it was nowhere close to Demulshooter for Naomi/atomiswave compatibility. But this was a long time ago.
Anyway, same answer as #2 for PCSX2 should apply for now

**Comment by RavenMacDaddy** [comment]
Understandable, and I got it working with two dolphinbars using said raw input - closing
