### ISSUE TITLE
Virtua Cop 1 on Model 2 no Player 2 Trigger

### ISSUE THREAD

**Issue by rpegelectronics** [argonlefou/DemulShooter#52]
both guns control player 1 shot only, player two cannot shoot. thanks youre the best!

**Comment by argonlefou** [comment]
Demulshooter didn't hooked the emulator or you didn't set your guns properly.
Start by carrefully reading the Wiki, and are other places on internet where you can find/ask for configuration advices (mainly BYOAC forum)

This isn't a bug or demulshooter-related issue issue (which is the main purpose of Github Issue reporting), so the ticket is now closed
