### ISSUE TITLE
HODT4

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#60]
Hello Demulshooter not Hook with the game on your last version why?

**Comment by argonlefou** [comment]
HOTD4 is working perfectly with current release of DemulShooter and the following (not last release though) Teknoparrot :  
TeknoParrot UI v1.0.0.713
OpenParrotWin32 1.0.0.511
OpenParrotx64 1.0.0.511
OpenSegaAPI 1.0.0.124
TeknoParrot 1.0.0.629

You can still share a demulshooter debug file to have a look

**Comment by popo69200** [comment]
Hello Where can I found the 713 version? because I test Previous but not good....
tks

**Comment by argonlefou** [comment]
I don't know how to get specific version of TP, the software is updating itself from the GUI when you want to...

The point is, this has been working with every version from the time I started untill this specific release which is the last I can test with. This usually means yhay previous version are working also. Question is usually on more recent releases

**Comment by popo69200** [comment]
I test previous version but not fonctional....I can test with old version demulshooter you think?

**Comment by argonlefou** [comment]
You can test with any version of DemulShooter, but there has been absolutely no change regarding HOD4 for almost 2 years...

If you want to know what is going wrong, as I already said, you better run DemulShooter with the "-v" option and share your debug file

**Comment by popo69200** [comment]
ok...for information V10.14 is ok with 1.0.0.597 is ok
but last version demulshooter with 1.0.0.597 is not ok
[Debug_2022-02-07_19-52-20.zip](https://github.com/argonlefou/DemulShooter/files/8017946/Debug_2022-02-07_19-52-20.zip)

**Comment by argonlefou** [comment]
Thanks for the file. There's nothing wrong with it, at least nothing obviously wrong.

There is no v10.14 for DemulShooter, I don't know what version you're using exactly but you can keep it for Teknoparot if this is the only one working...

On my side I can just confirm that last available version is working with almost last TP version for Lindbergh games

**Comment by popo69200** [comment]
Ok. Very tks for your job! You re the best!!!
