### ISSUE TITLE
Lost land adventure

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#62]
Hello boss!
Do you know if a version for this game is possible ?
Is a very good game and demulshooter permit to play with alien arcade gun FFB.
Please tks

**Comment by argonlefou** [comment]
Hello,
This game is not on the to-do list for some technical reasons (dome screen/display causes me issue with aim alignment on a flat screen gun)
And I don't want to go into geometric calculation

**Comment by popo69200** [comment]
Ok. Actualy i play patreon with alien gun and i have problem

**Comment by argonlefou** [comment]
If it's just outputs I can have a look but there are no guarantee that the game has them enabled
