### ISSUE TITLE
HOTD4 - shooting is not accurate

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#64]
Hello
when I play without demulshooter shooting is accurate. but when I use demulshooter the shooting is completely shifted why just with this game?
please
I play with TP. Does I play without?.

**Comment by argonlefou** [comment]
Aim shifting may be the result of some graphics tweak (like resolution change) or other things with TP
I believe now TP has built-in raw input support for multiple players so Demulshooter may not be needed anymore (to be confirmed)

**Comment by popo69200** [comment]
I play with alien gun
And this gun need output like demulshooter fot force feed back and mame hooker

**Comment by argonlefou** [comment]
A new option (-noinput) has been added to DemulshooterX64 to disable input hack while keeping output system

This is planned for regular Demulshooter very soon, exactly for this kind of situation

**Comment by popo69200** [comment]
en laissant la resolution par defaut la precision est meilleur. mais pas parfaite. etrange...par ailleurs la mitraillette tire toute seule....pouvons nous lancer HODT4 sans teknoparrot?

**Comment by argonlefou** [comment]
> you're the best!!!!! you have the time to do the same with other emulator :) ?
When the -noinput option will be available for regular DemulShooter, this will be for all targets/games


> en laissant la resolution par defaut la precision est meilleur. mais pas parfaite. etrange...par ailleurs la mitraillette tire toute seule....pouvons nous lancer HODT4 sans teknoparrot?
Non,  Teknoparrot est à ce jour le seul émulateur pouvant faire tourner les jeux Lindbergh (Linux) sous windows.
Tout comme le précédent ticket ouvert [#60](https://github.com/argonlefou/DemulShooter/issues/60) je peux juste confirmer que non seulement DemulShooter fonctionne avec Teknoparrot/HOD4 et qu'il n'y a pas de soucis de précision ou mitraillette lorsque le fonctionnement est nominal

**Comment by popo69200** [comment]
tu es francais :)
EN faite tu as raisons d'un coté...si je lance TP avec HOTD4 ca marche nickel
si j'utilise Démulshooter ca ne marche pas top. J'ai retelechargé la derniere version de HOTD4 au cas ou. mais deja demulshooter reste rouge alors qu'il marche bien....il y a donc quelques chose qui cloche. est ce que quelqu'un peut essayer et me valider que sur la denriere de TP et Demulshotter ca passe au vers? avec quel EXE precisement?
faut il peut etre mettre le jeux à un certain endroit pour que ca marche?
Ca marche avec tous les jeux sauf lui...apres...il faut prendre en compte que j'utilise mamehooker qui via ajouter peut etre un probleme dans tout ca pour me faire le choc sur les 2 guns alien....
deja sans cocher la resolution personalisée ca marche avec un leger décalage...il me reste le probleme du gun qui tir sans cesse quasi...c'est pas du coup a coup mais du tir continu.....
si ca peut aider....
J'attend avec impatience ne NOinput....tu penses que cela sous entend que sur Dolphin j'aurai un output?
Celui qui serait top ca serait BLue estate...mais je me perd dans la conversation :)
Merci encore de prendre du temps à repondre

**Comment by argonlefou** [comment]
> mais deja demulshooter reste rouge alors qu'il marche bien....il y a donc quelques chose qui cloche. 

Ce n'est pas possible: si l’icône est rouge c'est que DemulShooter n'est pas activé avec le jeu, donc il ne peut pas "bien marcher".

>est ce que quelqu'un peut essayer et me valider que sur la denriere de TP et Demulshotter ca passe au vers? avec quel EXE precisement? 

Testé ce matin avec la dernière mise à jour de TP, et les deux versions disponibles de HOD4 (Rev.A et Rev.C), tout fonctionne parfaitement avec DemulShooter.
Il n'y a pas d'exe, ce sont des binaires linux. J'utilise en general hod4M.elf

>faut il peut etre mettre le jeux à un certain endroit pour que ca marche? 

Le repertoire du jeu n'a ucun impact sur DemulShooter

>Ca marche avec tous les jeux sauf lui...apres...il faut prendre en compte que j'utilise mamehooker qui via ajouter peut etre un probleme dans tout ca pour me faire le choc sur les 2 guns alien....

Mamehooker n'a aucun impact sur DemulShooter.

> il me reste le probleme du gun qui tir sans cesse quasi...c'est pas du coup a coup mais du tir continu..... 

C'est le fonctionnement du jeu....pas du coup par coup

> J'attend avec impatience ne NOinput....tu penses que cela sous entend que sur Dolphin j'aurai un output?

Déjà répondu sur ton ticket [#63](https://github.com/argonlefou/DemulShooter/issues/63) : il n'y aura pas d'output sur Dolphin
Le -noinput permet seulement de recuperer les outputs (pour les jeux où çà existe déjà avec Demulshooter) sans activer les modifications en input

 > Celui qui serait top çà serait BLue estate...

J'ai testé beaucoup de choses il y a longtemps avec ce jeu mais ça ne marchera pas de par sa conception.


Du coup je clôture ce ticket, cet espace n'a pas vocation à être un forum mais une interface pour les dysfonctionnements du logiciel
Je te renvoie vers d'autre forum/discord pour le support d’installation et configuration des émulateurs

**Comment by popo69200** [comment]
Je comprend merci
