### ISSUE TITLE
HODT3 version PC

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#67]
Salut booss.je viens de tester le jeux sur PC
Quand je tire avec le player 1 c'est le pistolet 2 qui tire dans le jeux
Idem pour le la recharge.
Le mouvement est bon
Pour le player 1 le mouvement est bon mais je peux pas tirer du coup ni recharger avec aucun des guns pour le P1

une idée?

**Comment by argonlefou** [comment]
Sans plus d'infos, non.

Pour commencer, il faudrait partager un fichier debug de demulshooter :
Lance demulmshooter avec l'option _**-v**_ dans la ligne de commande (lancer le jeu ensuite pendant quelques secondes le temps de tester les commandes) puis une fois terminé, partager le fichier debug crée dans le répertoire de DemulShooter

Plus bien sur les habituels conseils : lancer demulshooter/hod3 directement sans script pour debuguer, executer en admin et bien configurer hod3 dans le menu pour les controles....

**Comment by popo69200** [comment]
justement pour les controles on doit mettre souris ou gamepad?
j'ai testé les deux mais pas mieux...normalement demulshooteur passe outre les controles non? ok je te fais ca j'espere dans soirée pour avancer. merci

**Comment by popo69200** [comment]
https://we.tl/t-1N2wg54iy7
voila le fichier debug

**Comment by argonlefou** [comment]
> justement pour les controles on doit mettre souris ou gamepad? j'ai testé les deux mais pas mieux...normalement demulshooteur passe outre les controles non? ok je te fais ca j'espere dans soirée pour avancer. merci

Aucun des 2....clavier pour les 2 joueurs
Tout est expliqué ici : https://github.com/argonlefou/DemulShooter/wiki/Windows-games#the-house-of-the-dead-iii

Si ça ne fonctionne pas, il me faudra ton executable hod3 pour verifier que c'est une version compatible avec les hacks deja existants (sinon je dois ajouter une m.a.j)

**Comment by popo69200** [comment]
du coup tu avais raison...j'avais une autre version et ca marche.
Celle qui marche pas avait un Exe deja tout paramétré pour lancer le jeux. La j'ai lancé le laucher puis le jeux et ca marche ...me reste a trouver pour passer en plein ecran
