### ISSUE TITLE
vcop 3 not hooked V10.4.3 & V10.4.4

### ISSUE THREAD

**Issue by ginzu2077** [argonlefou/DemulShooter#68]
Hi Argonlefou,

I just retried to play vcop3 and the 2 latest version of demulshooter (new hook) , but it doesn't work in game. (no hook at all).
I tried with 2 wiimotes + mayflash dolphin bar.
The icon in the task bar say vcop 3 [hooked]...
When i tried with my old version V 10.1.4 of demulshooter, everything is working nicely...
i added admin rights on the demulshooter.exe....
An idea ?  thx

**Comment by argonlefou** [comment]
Hi,

Can you give me the version of Cxbx used, and also a demulshooter debug file ?

**Comment by ginzu2077** [comment]
Off course! 

This is the CxbxReloaded-Release-VS2019  (latest)

[Debug_2022-03-16_22-50-04.txt](https://github.com/argonlefou/DemulShooter/files/8274655/Debug_2022-03-16_22-50-04.txt)

**Comment by popo69200** [comment]
De mon côté  je viens de tester ca marche nickel.
Avec la dernière version de lemulateur et de demulshooter
Jai meme le retour de force avec les guns aliens

**Comment by popo69200** [comment]
JE PEUX UPLOAD mon dossier GINZU si tu veux?

**Comment by argonlefou** [comment]
> Off course!
> 
> This is the CxbxReloaded-Release-VS2019 (latest)
> 
> [Debug_2022-03-16_22-50-04.txt](https://github.com/argonlefou/DemulShooter/files/8274655/Debug_2022-03-16_22-50-04.txt)

Thanks for the file, unfortunatelly there's nothing wrong in it :(  

The hook itself is still the same, only the buttons handling has changed. Axis should work the same....but I don't know what can cause this for you

**Comment by cangarujack** [comment]
> Virtua Cop 3 verified working - 2 Sinden guns with very accurate shooting:
> 
> Cxbx-Reloaded cdb3b13 (Aug 21 2020) Demulshooter v10.2
> 
> **Somewhere after these versions it the hook got broke** *Cxbx-Reloaded must have controller Port 1 mapped as "MS Controller S" Controller port 1 mappings to change: Back=X Start = 1
> 
> Be warned using different versions of either Cxbx-Reloaded or Demulshooter will most likely break the hook. I found out the hard way by upgrading and then reverting back to these versions!
> 
> **Using a newer version of Cxbx-Reloaded will give you a cxbxr-ldr.exe error when running cxbx.exe in a AHK/bat and the hook is broken**

Hi Mark, can you explain me how to add a sinden player 2 on virtua cop 3 ?

thanks

**Comment by KaiSSeRToRiuS** [comment]
Hi all! Sorry for reopen but... I was playing flawlessly VCOP 3 win DS 10.7.3 and Cxvx-R (some July ver...). I stopped to play for a few weeks and today I wanted to play it again with my brother and now DS won't hook. Tryed many versions od DS and Cxbx but nothing is working... I remember last week, Windows 10 was updated. May be can make fail the hook a Win update? Tomorrow I'll do a rollback to test. Thanks in advance!

**Comment by argonlefou** [comment]
> I stopped to play for a few weeks and today I wanted to play it again with my brother with dual Sinden and now DS won't hook. Won't hook, like DS icon stays red in the tray or like it just doesn't work as intended ?

You can also share a debug file (https://github.com/argonlefou/DemulShooter/wiki/Debugging)

**Comment by KaiSSeRToRiuS** [comment]
Hi! First at all, thanks for your response, later, please excuse my english. Well, here is the debug file. 

Used DS 10.7.3 and CXBX last version downloaded and configured for the test with two sinden. Win 10 version 21H2 (SO compilation 19044, 1889) 

[Debug_2022-08-16_16-12-07.txt](https://github.com/argonlefou/DemulShooter/files/9351803/Debug_2022-08-16_16-12-07.txt)
!

**Comment by KaiSSeRToRiuS** [comment]
This is the .ahk script I use to launch the game. Use the cxbxr-ldr.exe to launch it or get an error. Anyway, launching the game from the same emulator doesn't hook DS either. I don't know if it is mandatory to launch it from script. I have tried everything. Trying to give all info as possible.

Run, C:\Users\RoLLeR\Desktop\UTILS\DemulShooter\DemulShooter.exe -target=chihiro -rom=vcop3 -v
sleep, 1000
Run, C:\Cxbx\cxbxr-ldr.exe /load "C:\Cxbx\VC3\vc3.xbe"
sleep, 1000
Send !{Enter}
ESC::
Sendinput, !{f4}
ExitApp

**Comment by argonlefou** [comment]
You don't need a script to launch the emulator/demulshooter

But the version you're using is a recent one, and they changed the executable name to cxbx-ldr.exe and demulshooter is looking for the older cxbx.exe

Some recent versions were not working anymore with Vcop3 (it may goes from good to not good according to nightly build and changes) so either use the last supported version from demulshooter's wiki (https://github.com/argonlefou/DemulShooter/wiki/Chihiro) or keep yours and try to make it work by renaming _cxbxr-ldr.exe_ to **_cxbx.exe_**

**Comment by KaiSSeRToRiuS** [comment]
I've found the problem when you posted it. Thanks for the fix. Let's try right now.
