### ISSUE TITLE
Added a "-noinput" 

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#69]
Hello, est ce que cette nouvelle option permet d'utiliser demulshooter avec des jeux non listés ?

**Comment by argonlefou** [comment]
Non.
Si un jeu n'est pas listé, il n'y aura pas d'output générées de manière magique

Le -noinput permet seulement d'utiliser DemulShooter pour des jeux où l'utilisateur veut les Outputs sans toucher aux input qui marcheraient correctement sans DemulShooter

**Comment by popo69200** [comment]
snif :) mais je comprend....j'attend avec impatience d'avoir un retour de force sur Lost Adventure comme sur l'original....un jour peut etre.
Merci pour ta disponibilité en tout cas
