### ISSUE TITLE
Lets Go Island

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#70]
Salut, je n'arrive pas avec TP a faire fonctionner demulshooter pour les deux jeux..LGI et LGI3D
Est ce qu'il faut savoir qq chose de spécial pour que demulshooter trouve bien le jeux quand il demarre? car pour moi l'icone reste rouge

**Comment by Smanar** [comment]
De mon coté je demarre TP, puis je lance demulshooter avec un fichier qui contient la ligne de commande.

**Comment by popo69200** [comment]
Smanar je n'ai pas compris ta reponse....toi ca marche ? mais avec quoi? GL? 
Oui avec TP le jeux marche.
Mon pb avec GL c'est pour les output....je n'arrive pas a faire marcher le FFB des Gun...je dois utiliser TP

**Comment by Smanar** [comment]
Ben il faut lancer le jeu dans TP et apres lancer demulshooter avec
`DemulShooter.exe -target=ringwide -rom=lgi -parrotloader`

**Comment by popo69200** [comment]
a quoi sert parrotloader en fin de ligne de commande?

**Comment by Smanar** [comment]
Bonne question, ca n'a plus l'air de servir, c'est un vieux truc

> Some keyboard keys you can set in TeknoParrotUi.exe won’t work (mainly P2 Start, and some others)
> While this issue remains, you can run DemulShooter like this :
> DemulShooter.exe -target=ringwide -rom=lgi -parrotloader
> This will block ALL inputs from ParrotLoader, and you will have access to these buttons on the keyboard
> (hardcoded on DemulShooter):
> [1] -> P1 Start
> [2] -> P2 Start
> [8] -> Service
> [9] -> Test

**Comment by popo69200** [comment]
Ecoutes avec cette cmd maintenant ca marche
