### ISSUE TITLE
House of Dead Remake

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#71]
Salut, penses tu faire quelque chose pour ce nouveau jeux? 
Merci pour ton retour...je ne doute pas de la complexité du taf.

**Comment by argonlefou** [comment]
House of Dead Remake est : 
1- un jeu PC
2- un jeu 64 bits
3- un jeu Unity

1 & 2 rendent les choses beaucoup plus complexes mais pas impossible
3 (la gestion de l'espace mémoire du moteur Unity) rend l'utilisation des procédures habituelles non viables

Donc en résumé : pour le moment, non
