### ISSUE TITLE
Version 10.6

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#74]
Salut, en quoi consiste la nouvelle version stp? Jai pas compris. Merci

**Comment by argonlefou** [comment]
Rien d'utile pour les non-développeurs

Par contre, pour la **dernière fois** : ce n'est **pas** ici un forum de discussion ni un chat, mais un espace consacré à des soucis de développement et de bugs.

Donc merci d'arrêter ce genre de message. Je t'ai déja indiqué que pour les questions diverses, le paramétrages et les aides au fonctionnement il y a des des forums spécialisés, à commencer par le topic DemulShooter sur arcadecontrols dont le lien est dans la première page du Wiki

**Comment by popo69200** [comment]
ok chef!
