### ISSUE TITLE
Graphic issue with Wild West Shootout

### ISSUE THREAD

**Issue by jazzynight** [argonlefou/DemulShooter#75]
DemulShooter_V10.7.0

I've just saw ending of this game. All functions include crosshair on/off option and auto fire works well. But there a graphical glitch after the bonus stage.

The saloon doors of the bonus stage backgroung graphic do not disappear after the bonus stage. The door still remains and disturb my sight until the ending. Also the word "Bonus stage" in the middle of the screen below.

**Comment by jazzynight** [comment]
https://youtu.be/SBGCEg4X1ww  08:25~

**Comment by argonlefou** [comment]
Thanks for the video it's a clear description.

Unfortunately I was not the one who actually made the game, I only did the I/O part and is the target/aiming is not at fault I can't really do anythind for the graphics and animation.

I don't know if the game was developped to be used correctly in 1920p or 4k or else.
By looking at the code I'd say 1920p would be the native resolution

**Comment by jazzynight** [comment]
Yeah I know you haven't made this game. I found that the glitch doesn't happen if I play this game at the native resolution of its own game.

**Comment by jazzynight** [comment]
> Thanks for the video it's a clear description.
> 
> Unfortunately I was not the one who actually made the game, I only did the I/O part and if the target/aiming is not at fault I can't really do anything for the graphics and animation.
> 
> I don't know if the game was developped to be used correctly in 1920p or 4k or else. By looking at the code I'd say 1920p would be the native resolution

Yeah I know you haven't made this game. I've just found that the glitch doesn't happen if I play this game at the native resolution of its own game.

**Comment by argonlefou** [comment]
Thanks for the info, i'll put a note on the wiki.
I'm on a phone only for a few days and didn't see a previous mention about the 4k but this is confirming what I though about the 1920p beeing native resolution
