### ISSUE TITLE
DemulShooter GUI slow to open, DemulShooter slow to hook

### ISSUE THREAD

**Issue by cor094** [argonlefou/DemulShooter#77]
On my arcade PC with lightguns, Demulshooter GUI takes about 20 seconds to open. Also, games take at least 20 seconds to hook. I always thought this was normal over the past year (it has persisted throughout multiple updates, including fresh install of newest 10.7.1), until I tried DemulShooter on my older, slower PC and DemulShooter GUI opens almost immediately and games hook quickly. Any ideas what could be slowing demulshooter down on my main arcade PC? Once it hooks/opens, games work fine. It is just annoying to have to wait a while before the buttons kick in, or for example, Operation Ghost will flash "insert coins" and it will take another ~10 seconds or so before it changes to "Freeplay" upon demulshooter hooking. It is already in an antivirus excluded folder, so it's not that. The demulshooter gui exe shows up in the task manager immediately, just doesn't actually appear until 20 seconds. Thanks! - Cory

**Comment by argonlefou** [comment]
An interrrsting thing would be to run demulshooter_gui with a -v option by command line to create a debug file and share it here

Same thing for operation ghost

Debug files data are timestamped, it may point in a direction. Overwise I gave no idea

**Comment by cor094** [comment]
I thought it may be getting hung up scanning my devices, so after some trial and error, I was able to figure out it is my USB encoders. With both plugged in, I get a delay of 20 seconds. With one plugged in, I get a delay of 10 seconds. With both unplugged, it loads right away.

[debug-plugged.txt](https://github.com/argonlefou/DemulShooter/files/8686861/debug-plugged.txt)
[debug-unplugged.txt](https://github.com/argonlefou/DemulShooter/files/8686862/debug-unplugged.txt)

**Comment by argonlefou** [comment]
Sorry for the late delay, but I couldn't find something to help on the software side.
I'm closing the ticket, do not hesitate if you have more information
