### ISSUE TITLE
Haunted Museum 2 - Crash

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#78]
Hello when I start Haunted Museum 2, I can PLay
But when I start Demulshooter for my ALien GUn, THe Game Crash.
See my log please 
[Debug_2022-05-13_21-27-17.txt](https://github.com/argonlefou/DemulShooter/files/8690857/Debug_2022-05-13_21-27-17.txt)

**Comment by popo69200** [comment]
Je peux parler Français c'est plus simple pour moi.:)
Donc quand je lance le jeux avec deulshooter il plante. pur moi ca plante au bout de 1sec...mais peut etre que le jeux reste executé encore qq sec en arriere plan.
Si je fais la meme chose avec a commande fearland la ca marche sauf que je n'ai pas le retour de force....donc pas de output.
Je voulais voir si avec la commande haunted2 le FFB marchait

**Comment by argonlefou** [comment]
2 differents sujets : 
1) avec la commande **_-target=globalvr -rom=fearland_** tout fonctionne, mais il faut le jeu de la bonne version (même si le contenu est le même, ce sont deux jeux différents, compilés par 2 éditeurs differents et ce sont deux .exe completement differents pour Demulshooter)

2) avec la commande **_-target=ttx -rom=hmuseum2_** tout fonctionne aussi, **_MAIS_** il y a une multitude de versions de l'executable qui trainent. En effet je viens de télécharger le dernier pack Jconfig et aucun des 3 exe contenus ne fonctionne avec DemulShooter. Je rajoute ça pour vérifier plus tard
Il y a ausii une autre release qui traine sur le net où la compatibilité n'est pas assurée

En attendant, la façon la plus sûre d'avoir un set-up qui fonctionne est d'utiliser la release de base du jeu (dont le checksum md5 du fichier game.exe est _**ede2a10fe37221d3994f31553b3a4ef5**_ ) et ne pas oublier de configurier le HAUNTED2.INI comme expliqué dans le wiki

Je mettrai à jour ce post lorsque les autres versions auront ete intégrées dans DemulShooter

**Comment by popo69200** [comment]
Merci encore pour ton professionnalisme.  Je vais passer pour un mauvais mais " checksum md5 du fichier game.exe est ede2a10fe37221d3994f31553b3a4ef5" ca veut dire quoi. Tu sais ou je peux le trouver?

**Comment by argonlefou** [comment]
https://www.lecoindunet.com/comment-verifier-hash-md5-fichier-1765

https://lecrabeinfo.net/verifier-integrite-calculer-empreinte-checksum-md5-sha1-sha256-fichier-windows.html

**Comment by argonlefou** [comment]
La v10.7.2 qui vient d'être publiée devrait prendre en compte toutes les versions les plus récentes des différents exe disponibles.

Bien les renommer en _**game.exe**_ si le nom est différent !

Bien penser à modifier le fichier _**HAUNTED2.INI**_ pour : 
GUNENABLE    0
JVSENABLE    0

Bref....suivre le Wiki...
