### ISSUE TITLE
Demulshooter Preventing Virtua Cop 3 from Changing Weapons

### ISSUE THREAD

**Issue by cor094** [argonlefou/DemulShooter#80]
Using demulshooter (10.7.1) and 
the cxbx-reloaded version mentioned on DS wiki as last tested, gamepad X assignment does not change weapon.  The p1 and p2 start assignments work fine. If I run the game without demulshooter, the gamepad X binding does switch weapons appropriately, so it's as if demulshooter is blocking the input. I have been binding gamepad X to 5 during my testing.

**Comment by argonlefou** [comment]
Confirmed
This is settled and will be available later today in a newest release I have to push

**Comment by argonlefou** [comment]
Fixed in 10.7.2 release

**Comment by cor094** [comment]
Amazing! Thank you so much for all you do!
