### ISSUE TITLE
Reload does not work for House of the Dead 3 Windows version

### ISSUE THREAD

**Issue by MarceloF1000** [argonlefou/DemulShooter#81]
DemulShooter 10.7.2.0 with House of The Dead 3 Windows version:
DemulShooter.exe -target=windows -rom=hod3pc

Reload button (right-mouse click) does not work.

Reload works fine when running the game without DemulShooter.

**Comment by RevEric** [comment]
When the input device in the HotD3 configuration is set to keyboard (which should be the case when using DemulShooter), reload is by default bound to "z". Either hit z on the keyboard to reload or bind your normal reload button/offscreen shoot to z and reloading should be good to go!

**Comment by MarceloF1000** [comment]
Thanks!
