### ISSUE TITLE
Haunted Museum - Recoil output going to GunMotor instead

### ISSUE THREAD

**Issue by MarceloF1000** [argonlefou/DemulShooter#82]
Using Demulshooter 10.7.2.0 and GUN4IR.

Monitoring Mame Hooker while playing Haunted Museum I noticed recoil feedback maps to P1_GunMotor instead of P1_CtmRecoil.

P1_GunMotor is also used to produce effects in the game such as the bumpy rail cart ride, so using it for recoil in GUN4IR is not practical.

P1_CtmRecoil never outputs anything. Is it possible to fix this?

Also, P1_Damaged produces an output once every second trigger pull. Might be by design, or maybe not. Would be nice if it did not produce any output at all whenever the trigger is pulled.

**Comment by argonlefou** [comment]
Hi,
This is not by design, this was (another) lazy copy/paste bug in DemulShooter's code messing with recoil/damage address

The game is using the original rumble (only output available on the gun) for gun recoil and all other status (damage, bumpy ride, etc...). The whole idea with DemulShooter is to split these signal to create separated recoil and dammage outputs

I just published v10.7.3 update and this should work as expected

The only thing I'm not sure of, because don't have the time to try that far, is wether the "bumpy rail cart ride" rumble effects will appear as P1_Damaged/P2_Damaged output or not

**Comment by MarceloF1000** [comment]
Great job. Recoil is now going to P1_CtmRecoil

Rumble effects are going to P1_GunMotor, regardless of whether they are in response to events in the environment such as the cart ride or in response to a trigger pull. This is actually a good thing. I wouldn't want these to be output as damage. Actual damage is correctly going to P1_Damaged, which I tweak to have a more intense and longer effect by sending more pulses to the gun.

Here is the Mame Hooker INI file. My gun in on COM 3. I'm sending to the gun 1 pulse for recoil from P1_CtmRecoil, 1 pulse for rumble effects from P1_GunMotor and 4 pulses for the damage rumble effect from P1_Damaged. I'm pretty happy with the results.

[General]
MameStart=cmo 3 baud=9600_parity=N_data=8_stop=1, cmw 3 S6
MameStop=cmw 3 E, cmc 3
StateChange=
OnRotate=
OnPause=
[KeyStates]
RefreshTime=
[Output]
P1_LmpStart=
P2_LmpStart=
P1_Lmp_R=
P1_Lmp_G=
P1_Lmp_B=
P2_Lmp_R=
P2_Lmp_G=
P2_Lmp_B=
P1_GunMotor=nll |cmw 3 F1x2x1
P2_GunMotor=
P1_CtmRecoil=nll |cmw 3 F0x2x0
P2_CtmRecoil=
P1_Life=
P2_Life=
P1_Damaged=nll |cmw 3 F1x2x4
P2_Damaged=
Credits=

**Comment by argonlefou** [comment]
Thanks for the feedback !

> Rumble effects are going to P1_GunMotor, regardless of whether they are in response to events in the environment such as the cart ride or in response to a trigger pull. This is actually a good thing. I wouldn't want these to be output as damage.

**_Px_GunMotor_** is only the genuine copy of how the game is controlling original hardware, mostly to be used if someone wants to reproduce the original behavior with original gun. this is why it's triggered by everything, as the original gun only has a rumble motor for everything.

**Comment by MarceloF1000** [comment]
Got it. Thanks for looking into this issue so quickly.
