### ISSUE TITLE
autofire problem with 2 players on Wild West Shootout (Sinden)

### ISSUE THREAD

**Issue by toccata10** [argonlefou/DemulShooter#83]
Hi,
1st of all: thanks for your incredible job on Demulshooter.
My issue: if I configure 2 Sinden Lightguns with Demulshoter on Wild West Shootout and pull the trigger continuously, it's either player 1 or player 2 who shoots continuously (autofire enabled in the service menu), but not both at the same time: the other player doesn't shoot unless the trigger is released. Autofire is fine when using only 1 player. It's when both want to use it that the problem arise.
Maybe there's something wrong when sending both triggers (left mouse click) at exactly the same time, because I never noticed any problem when rapidly triggering both guns. Maybe slightly delaying player2 for example could solve this problem ?
Not sure if it's related to Sinden lightguns, because it works perfectly fine with Let's go Island with demulshooter: both guns send bullets when continuously pressing on the trigger.

**Comment by argonlefou** [comment]
Hi,

There is no comparison possible between let's go island and Wild West shootout. More generally between any game supported, as each one needs a specific hack to work

Based on what you said I think we can rule out sinden problem.
I did not try with autofire on so it's highly possible that the hack does not work with that option

I'll have to re-install the setup and re-test that so I'm keeping this ticket open, but I can't guarantee any delay or any change

**Comment by argonlefou** [comment]
Replying to myself : would you want to try this updated Demulshooter plugin for WWS game ?

You need to unpack the file and overwrite the dll in "\wws\NTFS extd - Game\BepInEx\plugins" subdirectory of the game : 

[WWS_BepInEx_DemulShooter_Plugin.zip](https://github.com/argonlefou/DemulShooter/files/9282956/WWS_BepInEx_DemulShooter_Plugin.zip)

**Comment by toccata10** [comment]
I've just tested your dll and it seems to work perfectly: autofire now works for both players at the same time and I didn't notice any side effect.
You did an incredible job once more ! Thanks so much.
I suppose you'll close this ticket when you merge the patch to mainline.

**Comment by argonlefou** [comment]
Updated dll in the v10.7.4 release
