### ISSUE TITLE
House of the Dead 4 - Gun firing by itself

### ISSUE THREAD

**Issue by MarceloF1000** [argonlefou/DemulShooter#84]
House of the Dead 4 + Teknoparrot (latest) + Demulshooter (latest)

This happens only when Demulshooter is involved and I have seen Youtube comments on people having this same issue, so it's not just me. The gun sometimes fires by itself until the clip is empty. I have also had cases where the trigger did not respond immediately and the grenade would arm, but not throw.

Using Demulshooter is the only way I can get the recoil output, so not being able to use it really ruins the experience for me.

Please have a look into this issue if you have time. Thanks!

**Comment by argonlefou** [comment]
DemulShooter support for TeknoParrot has been deprecated a few months ago, when TP added their own RawInput system.
Wiki has been updated.

You can still use DemulShooter to get outputs, without messing with TP input system, thanks to the _**-noinput**_ command :  
**_DemulShooter.exe -target=lindbergh -rom=hotd4 -noinput_**

I just uploaded a new release to fix a bug with this -noinput option regarding hotd4 by the way
