### ISSUE TITLE
Time Crisis 5 Autofires the Machine Gun

### ISSUE THREAD

**Issue by Bommel24** [argonlefou/DemulShooter#85]
Since this game has aim issues in game (not in menu) i need demulshooter to make it work. However once you select the machinegun in game it just autofires and drains all bullets even while not pulling the trigger.

**Comment by Bommel24** [comment]
I fixed it myselft by changing "TC5\TimeCrisisGame\Config\DefaultInput.ini"
lines to;
Bindings=(Name="RightMouseButton",Command="StartFire | OnRelease StopFire")
Bindings=(Name="LeftMouseButton",Command="StartAltFire | OnRelease StopAltFire | OnRelease StopFire")


and commenting "TC5\Engine\Config\BaseInput.ini"
;Bindings=(Name="LeftMouseButton",Command="Fire")
;Bindings=(Name="RightMouseButton",Command="AltFire")

**Comment by argonlefou** [comment]
Thanks, for the fix
I'll have a couple of things to check out again in TC5. I'll look at this too when I'll have time to do that
