### ISSUE TITLE
House of the Dead III trigger not working in game

### ISSUE THREAD

**Issue by uppermezzanine** [argonlefou/DemulShooter#86]
Hi,
Using DemulShooter v10.7.4 running with administrator privileges, House of the Dead III (EU) is working fine in menus - using Sinden gun the cursor moves normally and the trigger selects menu items. In game however, trigger does nothing.

I've started DemulShooter first like normal and also tried using sleep 10000 in the AHK script to delay the start up of DemulShooter until after HotD3 starts but I still cannot fire in game.

I've checked in the system tray whilst game is running and DemulShooter is green and says hod3 is hooked.

**Comment by argonlefou** [comment]
Please try to get a demulshooter debug file (https://github.com/argonlefou/DemulShooter/wiki/Debugging)

It's almost certainly either an unsopported ISO or some config issue

**Comment by uppermezzanine** [comment]
Thanks argonlefou. You're right - my config was wrong. I'd recently updated DemulShooter and hadn't yet run the GUI and added my gun as P1 device in the new version... Game is working as intended now. Sorry, for wasting your time. Thank you for the help!
