### ISSUE TITLE
Terminator 

### ISSUE THREAD

**Issue by popo69200** [argonlefou/DemulShooter#87]
Salut.  Pour moi avec terminator et mamehooker je n'ai pas l'effet mitraillettes.  Ça tire coup par coup. Une idée?
Merci

**Comment by argonlefou** [comment]
Je ne gère pas comment MameHooker s'interface avec les gun de chacun.

Dans la fenêtre de MameHooker il y a la liste des outputs du jeu en cours.
Comment réagi le recoil ? Les 0 et les 1 s'enchaînent ou c'est aussi du coup par coup

**Comment by popo69200** [comment]
On est sur du coup par coup.
Si je param tp mamehooker sans demulshooter .ca marche mais je reste en mitraillette et sa tire même si j'ai plis de munition car n'est pas lié au jeu après

**Comment by argonlefou** [comment]
Juste pour être clair :  
Avec DemulShooter, en jeu, gachette enfoncée : dans la fenêtre de MameHooker, comment evolue la valeur **_P1_Ammo_** ?
Elle est diminue et est correcte ? Même avec une arme automatique ?

**Comment by popo69200** [comment]
J'arrive pas à ouvrir Mamehooker en même temps que le jeu est ouvert par contre si je bascule sur demulshooter dans output trois millisecondes ou 5 millisecondes j'ai déjà un effet bien meilleur est-ce normal. D'interrogation est-ce que cela peut poser un problème ?

**Comment by argonlefou** [comment]
Pour ouvrir MameHooker il suffit de lancer le jeu en mode fenetre et non plein ecran....et il suffit de cliquer sur l'icône MameHooker a coté de l'horloge...

Et non passer le delai de 5ms à 3ms ne pose pas de soucis :
Plus le delai sera court, plus les valeurs seront mises à jour souvent. Par contre le CPU va tourner un peu plus.
