### ISSUE TITLE
Haunted Museum 2 (FrightFearLand) - GunMotor and Damaged outputs are mixed

### ISSUE THREAD

**Issue by MarceloF1000** [argonlefou/DemulShooter#89]
Using DemulShooter 10.7.4.0 and GUN4IR.

Outputs for P1_GunMotor and P1_Damaged are mixed. I get environment rumble effects and damage effects on both outputs.

Would you be able to split these effects so that P1_Damaged outputs only the damage effect?

As for P1_GunMotor, it should not output damage effect, but only environment rumble effects.

Thanks!

**Comment by argonlefou** [comment]
I'll check again and report later

**Comment by MarceloF1000** [comment]
Yes, the very first mission to the left, named "Adventure" has several environment effects. At the beginning the gate to the cave will close, causing P1_Damaged to produce output (should be P1_GunMotor instead). Your character then opens the gate, which again triggers an output. There are other effects later in this mission such as when the bridge collapses and you go down the wooden slide. These are all environment effects.

**Comment by argonlefou** [comment]
Corrected in v10.7.9 today's release.

Original gunmotor will still rumble like it should, only custom damaged outputs have been filtered

**Comment by MarceloF1000** [comment]
Tested and working. Thanks!
