### ISSUE TITLE
Better Mapping for LGI3D

### ISSUE THREAD

**Issue by Catarax** [argonlefou/DemulShooter#9]
When played as a mouse, right click is start button and middle click is 3D OFF option.

Since the game has automatic reload, could theses buttons being mapped instead of nothing for them? The Start button is really needed for gameplay.

Virtual button didn't work also on this title.
Thank you!

**Comment by argonlefou** [comment]
Hello,
Sorry but the purpose of DemulShooter is not to replace "management" buttons.

There are a lot of other system/games where you still need other buttons/keyboard keys to manage the game (Coin, Start, Service, Test menu etc....) and TeknoParrot is perfectlly capable to manage that
