### ISSUE TITLE
Lupin the 3rd crashing with newer DemulShooters

### ISSUE THREAD

**Issue by bdiederichs** [argonlefou/DemulShooter#91]
Lupin III The Shooting crashes the Demul emulator whenever you try to launch it alongside any Demulshooter newer than version 8.7.0.

I am still using an instance of DemulShooter 8.7.0 to play this game but I can't get outputs with this version

**Comment by argonlefou** [comment]
I have no issue with **_demul07_280418_** with lupinsho rom (lupinsho0zip + gds-0018.chd) and latest release of DemulShooter

There might be something wrong on your setup, as lupinsho is sharing the same hack than confmiss, deathcox, hotd2 and mok so any crash on DemulShooter's startup should do the same with these other games.

You can still get a [debug file](https://github.com/argonlefou/DemulShooter/wiki/Debugging) file and share it here, in case of something obvious...

On a side note, FlyCast is slowy growing solid for Naomi and Atomiswave emulation (with integrated raw input support and enhanced graphics capability)
I'm currently adding output support for the last release (FlyCast v2.0) and at the same time as I'm finishing what was not yet done on some  Demul games (including Lupin, which had no custom outputs untill today)

**Comment by bdiederichs** [comment]
Thank for the info!
It’s good to know this is just me then. 
I had the hardest time getting this game to work before I started trying older versions of Demulshooter 

I’ll post a debug file just in case (tomorrow)
haven’t tried flycast before, will also look into that!

**Comment by bdiederichs** [comment]
[Debug_2022-10-02_21-07-30.txt](https://github.com/argonlefou/DemulShooter/files/9693982/Debug_2022-10-02_21-07-30.txt)


not sure if this shows anything useful as demul just closes but it happens on all 3 PC's I've tried this on.

demul crashes if I try to launch it alongside any demulshooter newer than 8.7.0

the attached debug was me trying demulshooter 10.7.8

**Comment by argonlefou** [comment]
This was very helpfull : You never mentionned that you were using demul 0.5.82 !

Do you have ant reason to keep this 10+ year old release instead of the last one ?(which is already old)

**Comment by bdiederichs** [comment]
Confirmed!
It took me a little while to get my rom set updated where I could play these games on the latest demul (I was using the older one for so long I hadn’t even thought about trying newer versions)
But the games don’t crash with the newer DemulShooter’s now

thanks for your help!

**Comment by bdiederichs** [comment]
Just in time for the new update with Lupin outputs!
I love ya, man!
