### ISSUE TITLE
Rabbids Hollywood Attract Mode

### ISSUE THREAD

**Issue by cor094** [argonlefou/DemulShooter#93]
The latest Ducon patch added the attract mode to this game, and it works great. Once either demulshooter or your launcher is added, the crosshair no longer automatically moves in attract mode, and instead follows my guns. I don't have a way to test outputs, so im not sure if they are activating during attract mode. It's really not a big deal though, just thought I would mention it.

**Comment by argonlefou** [comment]
Thanks for pointint this out

I'll see if that can be ajusted later, I can't for now

As for outputs, the rimble output is not triggered during attract mode

But again, I'll check that in a couple of weeks

**Comment by argonlefou** [comment]
You can replace demulshooter plugin with this one for the crosshair issue :
[RHA_BepInEx_DemulShooter_Plugin.zip](https://github.com/argonlefou/DemulShooter/files/9908413/RHA_BepInEx_DemulShooter_Plugin.zip)

This will be integrated on v8.2 release, I just pushed 8.1 this morning

**Comment by cor094** [comment]
Awesome! I appreciate all the work you do. Thanks!

**Comment by argonlefou** [comment]
Plugin is now part of the 10.8.2 release
