### ISSUE TITLE
[Feature Request] Outputs for Flycast

### ISSUE THREAD

**Issue by gustavoalara** [argonlefou/DemulShooter#95]
Hi again Argon

I wonder if it is possible to add support to Demulshooter for the outputs of the arcade games that flycast handles in the same way that Demulshooter handles Demul, Model 2, PC Games and ArcadePC. The latest versions of flycast have added support for network outputs but the outputs that those games show are very poor and the custom outputs that are done through demul or the other games are really unbelievable.

What do you think? Do you think is possible?

**Comment by argonlefou** [comment]
I've started some work on Flycast last month, it worked for most games but I had no time to polish this to be good enough for a public release.

There are still some drawbacks (like addresses changing sometimes and, of course, hack tied to a specific version on the exe) that need to be addressed...but I won't be able before december

**Comment by gustavoalara** [comment]
Fantastic news!

Take your time, there are more important things in our lives. For me to know you're working on it is enough to be happy

**Comment by shiryu55** [comment]
Perfect, incredible news, take all the time you need, thank you very much for your dedication.

**Comment by argonlefou** [comment]
Flycast outputs now available in DemulShooter_v10.9.0 update
