### ISSUE TITLE
Heavy Fire Swap aiming Left and Right when covering

### ISSUE THREAD

**Issue by thefrozncity** [argonlefou/DemulShooter#98]
Hello,
Firstly, Thank you for your all great work.
Really appreciated.

One suggestion for heavy fire A and SS

When covering, it is more realistic and makes sense aiming opposite side. because "body(especially Back)" need to be faced to covering wall "not a muzzle of a gun". Kindly add option to swap this if it is easy to update.

Thanks a lot.

**Comment by argonlefou** [comment]
Hello,
That's not a crazy idea, it's kind of logical.

I'll put it on the stack for next updates

**Comment by thefrozncity** [comment]
Thanks so much!! 

I am so glad to here that! 

Have a nice day there and Happy new year! 

나의 iPhone에서 보냄

**Comment by argonlefou** [comment]
Added (finally) to the v10.15 update

Should work as intended hopefully, I could not test it on the games
