### ISSUE TITLE
Virtua Cop 3, crazy aim

### ISSUE THREAD

**Issue by bromlecornu** [argonlefou/DemulShooter#99]
Hi, 
I'm setting up my cxbx reloaded (version approuved on wiki) and when I launch my game, the aim is crazy. I put the no crosshair patch.

When I control my demulshooter tray icon during the game, it's red.

My ahk script
`#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
#SingleInstance Force ; prevents multiple copies of this script to be running at the same time

Run, D:\LaunchBox\Demulshooter\DemulShooter.exe -target=chihiro -rom=vcop3
Process, Wait, DemulShooter.exe, 10 ; Wait for demulshooter to start, or 10 seconds max
Run, D:\LaunchBox\Emulateurs\Cxbx shoot\cxbxr-ldr.exe /load "E:\Games\Xbox\Virtual Cop 3\vc3.xbe"
WinWaitActive, ahk_exe cxbx.exe ; Wait until CXBX has started and the window is active
Send !{Enter} ; send Alt+Enter to make it fullscreen

ESC::
Sendinput, !{f4} ; send ALT+F4 to close the emu when pressing ESC
    Process,Close,Demulshooter.exe
    Run,taskkill /im "Demulshooter.exe" /F
ExitApp ; Close this script` 

If you have an idea pls

Thx

**Comment by argonlefou** [comment]
DemulShooter is currently looking after "cxbx.exe" process running to hook it, so using "cxbxr-ldr.exe" will cause the hook to never happen.

I've updated DemulShooter to be working with recent releases (the ones with cxbxr-ldr.exe), the next release should be available within a couple of days. And wiki will be updated.

Untill then, I've been told that renaming cxbxr-ldr.exe to cxbx.exe would work

**Comment by argonlefou** [comment]
Cxbx support updated in DemulShooter_v10.9.0 release
